// Generated by scripts/generate-design-tokens.mjs — do not edit.
// Source: packages/design-tokens/tokens.json

import Foundation

public enum DesignTokens {
  public struct RGB: Sendable, Equatable {
    public let red: Double
    public let green: Double
    public let blue: Double

    public init(red: Double, green: Double, blue: Double) {
      self.red = red
      self.green = green
      self.blue = blue
    }
  }

  public struct AdaptiveRGB: Sendable, Equatable {
    public let light: RGB
    public let dark: RGB

    public init(light: RGB, dark: RGB) {
      self.light = light
      self.dark = dark
    }
  }

  public enum Color {
    public static let brandAccent = AdaptiveRGB(
      light: RGB(red: 8.0 / 255.0, green: 116.0 / 255.0, blue: 86.0 / 255.0),
      dark: RGB(red: 130.0 / 255.0, green: 221.0 / 255.0, blue: 184.0 / 255.0)
    )

    public static let quotaHealthy = AdaptiveRGB(
      light: RGB(red: 8.0 / 255.0, green: 116.0 / 255.0, blue: 86.0 / 255.0),
      dark: RGB(red: 130.0 / 255.0, green: 221.0 / 255.0, blue: 184.0 / 255.0)
    )

    public static let quotaWarning = AdaptiveRGB(
      light: RGB(red: 180.0 / 255.0, green: 83.0 / 255.0, blue: 9.0 / 255.0),
      dark: RGB(red: 240.0 / 255.0, green: 180.0 / 255.0, blue: 41.0 / 255.0)
    )

    public static let quotaCritical = AdaptiveRGB(
      light: RGB(red: 159.0 / 255.0, green: 29.0 / 255.0, blue: 29.0 / 255.0),
      dark: RGB(red: 240.0 / 255.0, green: 168.0 / 255.0, blue: 168.0 / 255.0)
    )

    public static let meterTrack = AdaptiveRGB(
      light: RGB(red: 229.0 / 255.0, green: 229.0 / 255.0, blue: 229.0 / 255.0),
      dark: RGB(red: 51.0 / 255.0, green: 51.0 / 255.0, blue: 51.0 / 255.0)
    )

    public static let textPrimary = AdaptiveRGB(
      light: RGB(red: 0.0 / 255.0, green: 0.0 / 255.0, blue: 0.0 / 255.0),
      dark: RGB(red: 244.0 / 255.0, green: 244.0 / 255.0, blue: 244.0 / 255.0)
    )

    public static let textSecondary = AdaptiveRGB(
      light: RGB(red: 107.0 / 255.0, green: 107.0 / 255.0, blue: 112.0 / 255.0),
      dark: RGB(red: 196.0 / 255.0, green: 196.0 / 255.0, blue: 196.0 / 255.0)
    )

    public static let textMeta = AdaptiveRGB(
      light: RGB(red: 107.0 / 255.0, green: 107.0 / 255.0, blue: 107.0 / 255.0),
      dark: RGB(red: 143.0 / 255.0, green: 143.0 / 255.0, blue: 143.0 / 255.0)
    )

    public static let surfaceCanvas = AdaptiveRGB(
      light: RGB(red: 255.0 / 255.0, green: 255.0 / 255.0, blue: 255.0 / 255.0),
      dark: RGB(red: 17.0 / 255.0, green: 17.0 / 255.0, blue: 17.0 / 255.0)
    )

    public static let surfaceContent = AdaptiveRGB(
      light: RGB(red: 250.0 / 255.0, green: 250.0 / 255.0, blue: 250.0 / 255.0),
      dark: RGB(red: 27.0 / 255.0, green: 27.0 / 255.0, blue: 27.0 / 255.0)
    )

    public static let borderSubtle = AdaptiveRGB(
      light: RGB(red: 229.0 / 255.0, green: 229.0 / 255.0, blue: 229.0 / 255.0),
      dark: RGB(red: 42.0 / 255.0, green: 42.0 / 255.0, blue: 42.0 / 255.0)
    )

    public static let activity0Fill = AdaptiveRGB(
      light: RGB(red: 239.0 / 255.0, green: 239.0 / 255.0, blue: 239.0 / 255.0),
      dark: RGB(red: 42.0 / 255.0, green: 42.0 / 255.0, blue: 42.0 / 255.0)
    )

    public static let activity0Border = AdaptiveRGB(
      light: RGB(red: 229.0 / 255.0, green: 229.0 / 255.0, blue: 229.0 / 255.0),
      dark: RGB(red: 42.0 / 255.0, green: 42.0 / 255.0, blue: 42.0 / 255.0)
    )

    public static let activity1Fill = AdaptiveRGB(
      light: RGB(red: 198.0 / 255.0, green: 237.0 / 255.0, blue: 220.0 / 255.0),
      dark: RGB(red: 19.0 / 255.0, green: 77.0 / 255.0, blue: 58.0 / 255.0)
    )

    public static let activity1Border = AdaptiveRGB(
      light: RGB(red: 47.0 / 255.0, green: 163.0 / 255.0, blue: 122.0 / 255.0),
      dark: RGB(red: 81.0 / 255.0, green: 179.0 / 255.0, blue: 145.0 / 255.0)
    )

    public static let activity2Fill = AdaptiveRGB(
      light: RGB(red: 130.0 / 255.0, green: 221.0 / 255.0, blue: 184.0 / 255.0),
      dark: RGB(red: 26.0 / 255.0, green: 122.0 / 255.0, blue: 88.0 / 255.0)
    )

    public static let activity2Border = AdaptiveRGB(
      light: RGB(red: 47.0 / 255.0, green: 163.0 / 255.0, blue: 122.0 / 255.0),
      dark: RGB(red: 81.0 / 255.0, green: 179.0 / 255.0, blue: 145.0 / 255.0)
    )

    public static let activity3Fill = AdaptiveRGB(
      light: RGB(red: 47.0 / 255.0, green: 163.0 / 255.0, blue: 122.0 / 255.0),
      dark: RGB(red: 47.0 / 255.0, green: 163.0 / 255.0, blue: 122.0 / 255.0)
    )

    public static let activity3Border = AdaptiveRGB(
      light: RGB(red: 47.0 / 255.0, green: 163.0 / 255.0, blue: 122.0 / 255.0),
      dark: RGB(red: 81.0 / 255.0, green: 179.0 / 255.0, blue: 145.0 / 255.0)
    )

    public static let activity4Fill = AdaptiveRGB(
      light: RGB(red: 8.0 / 255.0, green: 116.0 / 255.0, blue: 86.0 / 255.0),
      dark: RGB(red: 130.0 / 255.0, green: 221.0 / 255.0, blue: 184.0 / 255.0)
    )

    public static let activity4Border = AdaptiveRGB(
      light: RGB(red: 47.0 / 255.0, green: 163.0 / 255.0, blue: 122.0 / 255.0),
      dark: RGB(red: 81.0 / 255.0, green: 179.0 / 255.0, blue: 145.0 / 255.0)
    )

    public static let chartInput = AdaptiveRGB(
      light: RGB(red: 8.0 / 255.0, green: 116.0 / 255.0, blue: 86.0 / 255.0),
      dark: RGB(red: 130.0 / 255.0, green: 221.0 / 255.0, blue: 184.0 / 255.0)
    )

    public static let chartCache = AdaptiveRGB(
      light: RGB(red: 57.0 / 255.0, green: 144.0 / 255.0, blue: 120.0 / 255.0),
      dark: RGB(red: 45.0 / 255.0, green: 147.0 / 255.0, blue: 116.0 / 255.0)
    )

    public static let chartOutput = AdaptiveRGB(
      light: RGB(red: 8.0 / 255.0, green: 116.0 / 255.0, blue: 86.0 / 255.0),
      dark: RGB(red: 130.0 / 255.0, green: 221.0 / 255.0, blue: 184.0 / 255.0)
    )
  }

  /// Apple system colour roles recorded in tokens.json. QuotaTheme / QuotaPalette map these;
  /// this file stays Foundation-only.
  public enum AppleSystemColor {
    public static let textPrimary = "label"
    public static let textSecondaryDark = "secondaryLabel"
    public static let textMeta = "tertiaryLabel"
    public static let meterTrack = "tertiarySystemFill"
    public static let activity0Border = "separator"
    public static let chartOutput = "label"
    public static let chartOutputOpacity: Double = 0.85
  }

  public enum Threshold {
    public static let quotaHealthyPercent: Double = 40
    public static let quotaWarningPercent: Double = 15
  }

  public enum Spacing {
    public static let space4: Double = 4
    public static let space8: Double = 8
    public static let space12: Double = 12
    public static let space16: Double = 16
    public static let space24: Double = 24
    public static let space32: Double = 32
    public static let space48: Double = 48
  }

  public enum Radius {
    public static let control: Double = 8
    public static let group: Double = 12
    public static let card: Double = 20
  }
}
