// Generated by scripts/generate-provider-catalog.mjs — do not edit.
// Source: packages/provider/catalog.json

import QuotaWire

extension ProviderID {
  /// Catalog asset name for this provider's template mark in QuotaBrandIcons.
  public var brandIconAssetName: String {
    switch self {
    case .`codex`: "openai"
    case .`claude`: "claude"
    case .`grok`: "grok"
    case .`openrouter`: "openrouter"
    case .`deepseek`: "deepseek"
    case .`kimi`: "kimi"
    case .`litellm`: "litellm"
    case .`cursor`: "cursor"
    case .`gemini`: "gemini"
    case .`copilot`: "copilot"
    case .`antigravity`: "antigravity"
    case .`opencode_go`: "opencode-go"
    case .unknown(let rawValue): rawValue
    }
  }
}
