// Generated by scripts/generate-provider-catalog.mjs — do not edit.
// Source: packages/provider/catalog.json

import Foundation

/// A provider the managed Account accepts, or one this build has never heard of.
///
/// A reader may be older than the Relay answering it, so an id outside the catalog is kept as the
/// text it arrived as, rather than discarding the reading it came with. See
/// [ADR 0023](../../../../docs/decisions/0023-strict-writes-tolerant-reads.md). That text is a wire
/// id and never a name: `displayName` comes from the catalog, and a provider the catalog does not
/// name says so.
public enum ProviderID: RawRepresentable, Codable, CaseIterable, Hashable, Identifiable, Sendable {
  case `codex`
  case `claude`
  case `grok`
  case `openrouter`
  case `deepseek`
  case `kimi`
  case `litellm`
  case `cursor`
  case unknown(String)

  /// Every provider this build knows. An unknown id is not one of them.
  public static let allCases: [ProviderID] = [
    .`codex`,
    .`claude`,
    .`grok`,
    .`openrouter`,
    .`deepseek`,
    .`kimi`,
    .`litellm`,
    .`cursor`,
  ]

  public init?(rawValue: String) {
    guard let known = Self.allCases.first(where: { $0.rawValue == rawValue }) else { return nil }
    self = known
  }

  public init(from decoder: Decoder) throws {
    let rawValue = try decoder.singleValueContainer().decode(String.self)
    self = ProviderID(rawValue: rawValue) ?? .unknown(rawValue)
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.singleValueContainer()
    try container.encode(rawValue)
  }

  public var rawValue: String {
    switch self {
    case .`codex`: "codex"
    case .`claude`: "claude"
    case .`grok`: "grok"
    case .`openrouter`: "openrouter"
    case .`deepseek`: "deepseek"
    case .`kimi`: "kimi"
    case .`litellm`: "litellm"
    case .`cursor`: "cursor"
    case .unknown(let rawValue): rawValue
    }
  }

  public var id: String { rawValue }

  /// What a person calls this provider. The catalog is the only place a provider is named, so
  /// one it does not list has no name to give and is not introduced by its id.
  public var displayName: String {
    switch self {
    case .`codex`: "Codex"
    case .`claude`: "Claude Code"
    case .`grok`: "Grok"
    case .`openrouter`: "OpenRouter"
    case .`deepseek`: "DeepSeek"
    case .`kimi`: "Kimi Code"
    case .`litellm`: "LiteLLM"
    case .`cursor`: "Cursor"
    case .unknown: "Unknown provider"
    }
  }

  public var sortOrder: Int {
    switch self {
    case .`codex`: 0
    case .`claude`: 1
    case .`grok`: 2
    case .`openrouter`: 3
    case .`deepseek`: 4
    case .`kimi`: 5
    case .`litellm`: 6
    case .`cursor`: 7
    case .unknown: Int.max
    }
  }
}
