// Generated by scripts/generate-provider-catalog.mjs — do not edit.
// Source: packages/provider/catalog.json

import Foundation

public enum ProviderID: String, Codable, CaseIterable, Identifiable, Sendable {
  // Current managed Account/Relay v3 IDs.
  case `codex`
  case `claude`
  case `grok`
  case `openrouter`
  case `deepseek`
  case `kimi`
  case `litellm`
  case `cursor`

  public var id: String { rawValue }

  public var displayName: String {
    switch self {
    case .`codex`: "Codex"
    case .`claude`: "Claude Code"
    case .`grok`: "Grok"
    case .`openrouter`: "OpenRouter"
    case .`deepseek`: "DeepSeek"
    case .`kimi`: "Kimi Code"
    case .`litellm`: "LiteLLM"
    case .`cursor`: "Cursor"
    }
  }

  public var sortOrder: Int {
    switch self {
    case .`codex`: 0
    case .`claude`: 1
    case .`grok`: 2
    case .`openrouter`: 3
    case .`deepseek`: 4
    case .`kimi`: 5
    case .`litellm`: 6
    case .`cursor`: 7
    }
  }

  /// First managed-data protocol that accepts this provider. Every case in this enum
  /// syncs; a provider that does not is absent from it.
  public var accountSyncProtocol: Int {
    switch self {
    case .`codex`: 2
    case .`claude`: 2
    case .`grok`: 2
    case .`openrouter`: 2
    case .`deepseek`: 2
    case .`kimi`: 2
    case .`litellm`: 2
    case .`cursor`: 3
    }
  }

  public func syncsToAccount(protocolVersion: Int) -> Bool {
    accountSyncProtocol <= protocolVersion
  }
}
