// Generated by scripts/generate-provider-catalog.mjs — do not edit.
// Source: packages/provider/catalog.json

import Foundation
import QuotaWire

struct BrowserSessionSpec: Equatable, Sendable {
  let loginURL: String
  let cookieHosts: [String]
  let cookieNames: [String]
  let browserPriority: [String]
  let exclusive: Bool
}

// The cases, id, displayName, and sortOrder come from QuotaWire's ProviderID, which is the
// same catalog. What follows is behavior only the macOS app has: Settings fields, browser
// session acquisition, and Agents visibility.
extension ProviderID {
  /// Menubar Agents toggle default (catalog.default_visible).
  var defaultVisible: Bool {
    switch self {
    case .`codex`: true
    case .`claude`: true
    case .`grok`: true
    case .`openrouter`: false
    case .`deepseek`: false
    case .`kimi`: false
    case .`litellm`: false
    case .`cursor`: false
    case .unknown: false
    }
  }

  /// Auth/setup action for Settings/Overview.
  var setupAction: String {
    switch self {
    case .`codex`: "codex login"
    case .`claude`: "claude auth login"
    case .`grok`: "grok login"
    case .`openrouter`: "Configure in QuotaBar"
    case .`deepseek`: "Configure in QuotaBar"
    case .`kimi`: "Configure in QuotaBar"
    case .`litellm`: "Configure in QuotaBar"
    case .`cursor`: "Sign in with browser"
    case .unknown(let rawValue): rawValue
    }
  }

  var brandIconAssetName: String {
    switch self {
    case .`codex`: "openai"
    case .`claude`: "claude"
    case .`grok`: "grok"
    case .`openrouter`: "openrouter"
    case .`deepseek`: "deepseek"
    case .`kimi`: "kimi"
    case .`litellm`: "litellm"
    case .`cursor`: "cursor"
    case .unknown(let rawValue): rawValue
    }
  }

  /// Providers that store secrets via service configuration.
  static var configurableCases: [ProviderID] {
    [.`openrouter`, .`deepseek`, .`kimi`, .`litellm`]
  }

  var isConfigurable: Bool {
    Self.configurableCases.contains(self)
  }

  var requiresBaseURL: Bool {
    switch self {
    case .`codex`: false
    case .`claude`: false
    case .`grok`: false
    case .`openrouter`: false
    case .`deepseek`: false
    case .`kimi`: false
    case .`litellm`: true
    case .`cursor`: false
    case .unknown: false
    }
  }

  var supportsBaseURL: Bool {
    switch self {
    case .`codex`: false
    case .`claude`: false
    case .`grok`: false
    case .`openrouter`: false
    case .`deepseek`: false
    case .`kimi`: false
    case .`litellm`: true
    case .`cursor`: false
    case .unknown: false
    }
  }

  var browserSession: BrowserSessionSpec? {
    switch self {
    case .`codex`: BrowserSessionSpec(
      loginURL: "https://chatgpt.com/",
      cookieHosts: ["chatgpt.com", "www.chatgpt.com"],
      cookieNames: ["__Secure-next-auth.session-token", "__Secure-next-auth.session-token.0", "__Secure-next-auth.session-token.1", "__Secure-next-auth.session-token.2", "__Host-next-auth.session-token", "__Secure-authjs.session-token", "authjs.session-token", "_account"],
      browserPriority: ["safari", "chrome", "edge", "brave", "arc", "dia", "chromium", "firefox"],
      exclusive: false)
    case .`claude`: BrowserSessionSpec(
      loginURL: "https://claude.ai/",
      cookieHosts: ["claude.ai", "www.claude.ai"],
      cookieNames: ["sessionKey", "lastActiveOrg"],
      browserPriority: ["safari", "chrome", "edge", "brave", "arc", "dia", "chromium", "firefox"],
      exclusive: false)
    case .`grok`: BrowserSessionSpec(
      loginURL: "https://grok.com/",
      cookieHosts: ["grok.com", "www.grok.com"],
      cookieNames: ["sso", "sso-rw"],
      browserPriority: ["safari", "chrome", "edge", "brave", "arc", "dia", "chromium", "firefox"],
      exclusive: false)
    case .`openrouter`: nil
    case .`deepseek`: nil
    case .`kimi`: BrowserSessionSpec(
      loginURL: "https://www.kimi.com/code/console",
      cookieHosts: ["www.kimi.com", "kimi.com"],
      cookieNames: ["kimi-auth"],
      browserPriority: ["safari", "chrome", "edge", "brave", "arc", "dia", "chromium", "firefox"],
      exclusive: false)
    case .`litellm`: nil
    case .`cursor`: BrowserSessionSpec(
      loginURL: "https://authenticator.cursor.sh/",
      cookieHosts: ["cursor.com", "www.cursor.com", "cursor.sh", "authenticator.cursor.sh"],
      cookieNames: ["WorkosCursorSessionToken", "wos-session", "__Secure-wos-session"],
      browserPriority: ["safari", "chrome", "edge", "brave", "arc", "dia", "chromium", "firefox"],
      exclusive: true)
    case .unknown: nil
    }
  }
}
