// Generated by scripts/generate-provider-catalog.mjs — do not edit.
// Source: packages/provider/catalog.json

import Foundation

enum ProviderID: String, Codable, CaseIterable, Identifiable, Sendable {
  case `codex`
  case `claude`
  case `grok`
  case `openrouter`
  case `deepseek`
  case `kimi`
  case `litellm`

  var id: String { rawValue }

  var displayName: String {
    switch self {
    case .`codex`: "Codex"
    case .`claude`: "Claude Code"
    case .`grok`: "Grok"
    case .`openrouter`: "OpenRouter"
    case .`deepseek`: "DeepSeek"
    case .`kimi`: "Kimi Code"
    case .`litellm`: "LiteLLM"
    }
  }

  /// Menubar Agents toggle default (catalog.default_visible).
  var defaultVisible: Bool {
    switch self {
    case .`codex`: true
    case .`claude`: true
    case .`grok`: true
    case .`openrouter`: false
    case .`deepseek`: false
    case .`kimi`: false
    case .`litellm`: false
    }
  }

  /// Auth/setup action for Settings/Overview.
  var setupAction: String {
    switch self {
    case .`codex`: "codex login"
    case .`claude`: "claude auth login"
    case .`grok`: "grok login"
    case .`openrouter`: "Configure in QuotaBar"
    case .`deepseek`: "Configure in QuotaBar"
    case .`kimi`: "Configure in QuotaBar"
    case .`litellm`: "Configure in QuotaBar"
    }
  }

  var brandIconAssetName: String {
    switch self {
    case .`codex`: "openai"
    case .`claude`: "claude"
    case .`grok`: "grok"
    case .`openrouter`: "openrouter"
    case .`deepseek`: "deepseek"
    case .`kimi`: "kimi"
    case .`litellm`: "litellm"
    }
  }

  var sortOrder: Int {
    switch self {
    case .`codex`: 0
    case .`claude`: 1
    case .`grok`: 2
    case .`openrouter`: 3
    case .`deepseek`: 4
    case .`kimi`: 5
    case .`litellm`: 6
    }
  }

  /// Providers that store secrets via service configuration.
  static var configurableCases: [ProviderID] {
    [.`openrouter`, .`deepseek`, .`kimi`, .`litellm`]
  }

  var isConfigurable: Bool {
    Self.configurableCases.contains(self)
  }

  var requiresBaseURL: Bool {
    switch self {
    case .`codex`: false
    case .`claude`: false
    case .`grok`: false
    case .`openrouter`: false
    case .`deepseek`: false
    case .`kimi`: false
    case .`litellm`: true
    }
  }

  var supportsBaseURL: Bool {
    switch self {
    case .`codex`: false
    case .`claude`: false
    case .`grok`: false
    case .`openrouter`: false
    case .`deepseek`: false
    case .`kimi`: false
    case .`litellm`: true
    }
  }

  var allowsPrivateHttpBaseURL: Bool {
    switch self {
    case .`codex`: false
    case .`claude`: false
    case .`grok`: false
    case .`openrouter`: false
    case .`deepseek`: false
    case .`kimi`: false
    case .`litellm`: true
    }
  }
}
