// Generated by scripts/generate-provider-catalog.mjs — do not edit.
// Source: packages/provider/catalog.json

import Foundation

struct BrowserSessionSpec: Equatable, Sendable {
  let loginURL: String
  let cookieHosts: [String]
  let cookieNames: [String]
  let browserPriority: [String]
}

enum ProviderID: String, Codable, CaseIterable, Identifiable, Sendable {
  // Every provider available to the local macOS app, including local-only collectors.
  case `codex`
  case `claude`
  case `grok`
  case `openrouter`
  case `deepseek`
  case `kimi`
  case `litellm`
  case `cursor`

  var id: String { rawValue }

  var displayName: String {
    switch self {
    case .`codex`: "Codex"
    case .`claude`: "Claude Code"
    case .`grok`: "Grok"
    case .`openrouter`: "OpenRouter"
    case .`deepseek`: "DeepSeek"
    case .`kimi`: "Kimi Code"
    case .`litellm`: "LiteLLM"
    case .`cursor`: "Cursor"
    }
  }

  /// Menubar Agents toggle default (catalog.default_visible).
  var defaultVisible: Bool {
    switch self {
    case .`codex`: true
    case .`claude`: true
    case .`grok`: true
    case .`openrouter`: false
    case .`deepseek`: false
    case .`kimi`: false
    case .`litellm`: false
    case .`cursor`: false
    }
  }

  /// Auth/setup action for Settings/Overview.
  var setupAction: String {
    switch self {
    case .`codex`: "codex login"
    case .`claude`: "claude auth login"
    case .`grok`: "grok login"
    case .`openrouter`: "Configure in QuotaBar"
    case .`deepseek`: "Configure in QuotaBar"
    case .`kimi`: "Configure in QuotaBar"
    case .`litellm`: "Configure in QuotaBar"
    case .`cursor`: "Sign in with browser"
    }
  }

  var brandIconAssetName: String {
    switch self {
    case .`codex`: "openai"
    case .`claude`: "claude"
    case .`grok`: "grok"
    case .`openrouter`: "openrouter"
    case .`deepseek`: "deepseek"
    case .`kimi`: "kimi"
    case .`litellm`: "litellm"
    case .`cursor`: "cursor"
    }
  }

  var sortOrder: Int {
    switch self {
    case .`codex`: 0
    case .`claude`: 1
    case .`grok`: 2
    case .`openrouter`: 3
    case .`deepseek`: 4
    case .`kimi`: 5
    case .`litellm`: 6
    case .`cursor`: 7
    }
  }

  /// Providers that store secrets via service configuration.
  static var configurableCases: [ProviderID] {
    [.`openrouter`, .`deepseek`, .`kimi`, .`litellm`]
  }

  var isConfigurable: Bool {
    Self.configurableCases.contains(self)
  }

  var requiresBaseURL: Bool {
    switch self {
    case .`codex`: false
    case .`claude`: false
    case .`grok`: false
    case .`openrouter`: false
    case .`deepseek`: false
    case .`kimi`: false
    case .`litellm`: true
    case .`cursor`: false
    }
  }

  var supportsBaseURL: Bool {
    switch self {
    case .`codex`: false
    case .`claude`: false
    case .`grok`: false
    case .`openrouter`: false
    case .`deepseek`: false
    case .`kimi`: false
    case .`litellm`: true
    case .`cursor`: false
    }
  }

  var allowsPrivateHttpBaseURL: Bool {
    switch self {
    case .`codex`: false
    case .`claude`: false
    case .`grok`: false
    case .`openrouter`: false
    case .`deepseek`: false
    case .`kimi`: false
    case .`litellm`: true
    case .`cursor`: false
    }
  }

  var browserSession: BrowserSessionSpec? {
    switch self {
    case .`codex`: nil
    case .`claude`: nil
    case .`grok`: nil
    case .`openrouter`: nil
    case .`deepseek`: nil
    case .`kimi`: nil
    case .`litellm`: nil
    case .`cursor`: BrowserSessionSpec(
      loginURL: "https://authenticator.cursor.sh/",
      cookieHosts: ["cursor.com", "www.cursor.com", "cursor.sh", "authenticator.cursor.sh"],
      cookieNames: ["WorkosCursorSessionToken", "__Secure-next-auth.session-token", "next-auth.session-token", "wos-session", "__Secure-wos-session", "authjs.session-token", "__Secure-authjs.session-token"],
      browserPriority: ["safari", "chrome", "edge", "brave", "arc", "dia", "chromium", "firefox"])
    }
  }

  /// Whether this provider is valid in the released managed Account/Relay v2 protocol.
  var syncsToAccount: Bool {
    switch self {
    case .`codex`: true
    case .`claude`: true
    case .`grok`: true
    case .`openrouter`: true
    case .`deepseek`: true
    case .`kimi`: true
    case .`litellm`: true
    case .`cursor`: false
    }
  }
}
