import { z } from "zod";
// Generated by `pnpm generate:provider-catalog` from packages/provider/catalog.json.
import { PROVIDER_IDS, type ProviderId, ProviderIdSchema } from "./provider-ids.generated.ts";

export { PROVIDER_IDS, type ProviderId, ProviderIdSchema };

export const PROTOCOL_VERSION = 2 as const;
export const MAXIMUM_SNAPSHOTS_PER_ENVELOPE = 32;
export const MAXIMUM_WINDOWS_PER_SNAPSHOT = 16;
export const MAXIMUM_USAGE_ROWS_PER_SUBMISSION = 2_048;
export const MAXIMUM_USAGE_COVERAGE_HOURS = 24 * 31;
export const MAXIMUM_USAGE_BREAKDOWNS = 1_000;
export const MAXIMUM_USAGE_READ_ROWS = 1_000;
export const MAXIMUM_USAGE_COVERAGE_ITEMS = 2_048;
export const MAXIMUM_UNPRICED_ITEMS = 100;
export const MAXIMUM_PRICING_ENTRIES = 4_096;
export const MAXIMUM_USAGE_SUBMISSION_BYTES = 1_048_576;
export const MAXIMUM_USAGE_MULTIPART_PARTS = 64;

const MAXIMUM_SAFE_INTEGER = Number.MAX_SAFE_INTEGER;
const OPAQUE_ID_PATTERN = /^[A-Za-z0-9][A-Za-z0-9._:-]*$/;
const BILLING_DIMENSION_PATTERN = /^[A-Za-z0-9][A-Za-z0-9._:+-]*$/;
// Models are provider-owned opaque text. Keep only the trust-boundary guard;
// punctuation, casing, whitespace, and Unicode are all valid model names.
const MODEL_PATTERN = /^(?=[\s\S]{1,128}$)(?![\s\S]*\p{Cc})[\s\S]+$/u;
const UTC_HOUR_PATTERN = /^\d{4}-\d{2}-\d{2}T\d{2}:00:00Z$/;
const DATE_PATTERN = /^\d{4}-\d{2}-\d{2}$/;
const NONNEGATIVE_INTEGER_PATTERN = /^(?:0|[1-9]\d*)$/;
const DECIMAL_PATTERN = /^(?:0|[1-9]\d*)(?:\.\d{1,12})?$/;
const PKCE_VERIFIER_PATTERN = /^[A-Za-z0-9._~-]{43,128}$/;

const SafeNonnegativeIntegerSchema = z.number().int().min(0).max(MAXIMUM_SAFE_INTEGER);
const SafePositiveIntegerSchema = SafeNonnegativeIntegerSchema.min(1);
const OpaqueIdSchema = z.string().min(1).max(128).regex(OPAQUE_ID_PATTERN);
const SecretSchema = z.string().min(16).max(2_048);
const DisplayNameSchema = z.string().trim().min(1).max(128);
const BillingDimensionSchema = z.string().min(1).max(64).regex(BILLING_DIMENSION_PATTERN);
const ModelSchema = z.string().min(1).regex(MODEL_PATTERN);
const LoopbackRedirectUriSchema = z
  .string()
  .url()
  .max(2_048)
  .refine(isLoopbackRedirectUri, "Expected a loopback HTTP redirect URI.");

export const Rfc3339InstantSchema = z.string().max(64).datetime({ offset: true });
export type Rfc3339Instant = z.infer<typeof Rfc3339InstantSchema>;

export const UtcHourSchema = z
  .string()
  .regex(UTC_HOUR_PATTERN)
  .refine(isCanonicalUtcHour, "Expected a valid UTC hour boundary.");
export type UtcHour = z.infer<typeof UtcHourSchema>;

export const UsageDateSchema = z
  .string()
  .regex(DATE_PATTERN)
  .refine(isCalendarDate, "Expected a valid calendar date.");
export type UsageDate = z.infer<typeof UsageDateSchema>;

export const IanaTimezoneSchema = z
  .string()
  .min(1)
  .max(64)
  .regex(/^[A-Za-z0-9._+-]+(?:\/[A-Za-z0-9._+-]+)*$/)
  .refine(isIanaTimezone, "Expected an IANA timezone.");
export type IanaTimezone = z.infer<typeof IanaTimezoneSchema>;

export const QuotaStatusSchema = z.enum([
  "available",
  "stale",
  "auth_required",
  "unavailable",
  "unsupported",
  "error",
]);
export type QuotaStatus = z.infer<typeof QuotaStatusSchema>;

export const FingerprintScopeSchema = z.enum(["global", "source"]);
export type FingerprintScope = z.infer<typeof FingerprintScopeSchema>;

/** Absolute quantity unit for credit/budget windows (optional; percent remains primary). */
export const QuotaValueUnitSchema = z.enum(["usd", "credits", "count"]);
export type QuotaValueUnit = z.infer<typeof QuotaValueUnitSchema>;

export const QuotaWindowSchema = z
  .object({
    id: z.string().min(1).max(64).regex(BILLING_DIMENSION_PATTERN),
    title: z.string().trim().min(1).max(128),
    /** Primary meter input; remaining is always 100 - used_percent in consumers. */
    used_percent: z.number().finite().min(0).max(100),
    resets_at: Rfc3339InstantSchema.optional(),
    duration_seconds: SafeNonnegativeIntegerSchema.optional(),
    /** Absolute remaining when known (for example, a USD balance). */
    remaining_value: z.number().finite().optional(),
    limit_value: z.number().finite().nonnegative().optional(),
    value_unit: QuotaValueUnitSchema.optional(),
  })
  .strict();
export type QuotaWindow = z.infer<typeof QuotaWindowSchema>;

export const QuotaAccountSchema = z
  .object({
    fingerprint: z.string().min(1).max(128).regex(OPAQUE_ID_PATTERN),
    fingerprint_scope: FingerprintScopeSchema,
    label: z.string().trim().min(1).max(128).optional(),
    plan: z.string().trim().min(1).max(64).optional(),
  })
  .strict();
export type QuotaAccount = z.infer<typeof QuotaAccountSchema>;

export const QuotaSnapshotSchema = z
  .object({
    provider: ProviderIdSchema,
    account: QuotaAccountSchema,
    windows: z.array(QuotaWindowSchema).max(MAXIMUM_WINDOWS_PER_SNAPSHOT),
    source: BillingDimensionSchema,
    status: QuotaStatusSchema,
    observed_at: Rfc3339InstantSchema,
    valid_until: Rfc3339InstantSchema.optional(),
  })
  .strict();
export type QuotaSnapshot = z.infer<typeof QuotaSnapshotSchema>;

/** The only supported remote quota upload envelope. */
export const QuotaSnapshotEnvelopeSchema = z
  .object({
    protocol_version: z.literal(PROTOCOL_VERSION),
    device_id: OpaqueIdSchema,
    generation: SafePositiveIntegerSchema,
    sequence: SafeNonnegativeIntegerSchema,
    captured_at: Rfc3339InstantSchema,
    snapshots: z.array(QuotaSnapshotSchema).max(MAXIMUM_SNAPSHOTS_PER_ENVELOPE),
  })
  .strict();
export type QuotaSnapshotEnvelope = z.infer<typeof QuotaSnapshotEnvelopeSchema>;

export const CollectionOutcomeSchema = z.enum([
  "success",
  "auth_required",
  "unavailable",
  "unsupported",
  "error",
]);
export type CollectionOutcome = z.infer<typeof CollectionOutcomeSchema>;

const QuotaCollectionSuccessResultSchema = z
  .object({
    provider: ProviderIdSchema,
    outcome: z.literal("success"),
    snapshots: z.array(QuotaSnapshotSchema).min(1).max(MAXIMUM_SNAPSHOTS_PER_ENVELOPE),
    source: BillingDimensionSchema.optional(),
    message: z.string().trim().min(1).max(512).optional(),
  })
  .strict();

const QuotaCollectionFailureResultSchema = z
  .object({
    provider: ProviderIdSchema,
    outcome: z.enum(["auth_required", "unavailable", "unsupported", "error"]),
    snapshots: z.array(QuotaSnapshotSchema).max(0),
    source: BillingDimensionSchema.optional(),
    message: z.string().trim().min(1).max(512).optional(),
  })
  .strict();

export const QuotaCollectionResultSchema = z
  .discriminatedUnion("outcome", [
    QuotaCollectionSuccessResultSchema,
    QuotaCollectionFailureResultSchema,
  ])
  .superRefine((result, context) => {
    for (const [index, snapshot] of result.snapshots.entries()) {
      if (snapshot.provider !== result.provider) {
        context.addIssue({
          code: "custom",
          path: ["snapshots", index, "provider"],
          message: "Snapshot provider must match collection result provider.",
        });
      }
    }
  });
export type QuotaCollectionResult = z.infer<typeof QuotaCollectionResultSchema>;

export const QuotaCollectionReportSchema = z
  .object({
    protocol_version: z.literal(PROTOCOL_VERSION),
    captured_at: Rfc3339InstantSchema,
    results: z.array(QuotaCollectionResultSchema).max(PROVIDER_IDS.length),
  })
  .strict();
export type QuotaCollectionReport = z.infer<typeof QuotaCollectionReportSchema>;

export const PlatformSchema = z.enum(["macos", "linux", "windows"]);
export type Platform = z.infer<typeof PlatformSchema>;

export const AccountSchema = z
  .object({
    account_id: OpaqueIdSchema,
    display_label: z.string().trim().min(1).max(128).nullable(),
    created_at: Rfc3339InstantSchema,
  })
  .strict();
export type Account = z.infer<typeof AccountSchema>;

export const DeviceStatusSchema = z.enum(["active", "offline", "signed_out"]);
export type DeviceStatus = z.infer<typeof DeviceStatusSchema>;

export const AccountDeviceSchema = z
  .object({
    device_id: OpaqueIdSchema,
    display_name: DisplayNameSchema,
    platform: PlatformSchema,
    device_generation: SafePositiveIntegerSchema,
    status: DeviceStatusSchema,
    created_at: Rfc3339InstantSchema,
    last_login_at: Rfc3339InstantSchema,
    last_seen_at: Rfc3339InstantSchema.nullable(),
    signed_out_at: Rfc3339InstantSchema.nullable(),
  })
  .strict()
  .superRefine((device, context) => {
    if ((device.status === "signed_out") !== (device.signed_out_at !== null)) {
      context.addIssue({
        code: "custom",
        path: ["signed_out_at"],
        message: "signed_out status and signed_out_at must agree.",
      });
    }
  });
export type AccountDevice = z.infer<typeof AccountDeviceSchema>;

export const AccountResponseSchema = z
  .object({
    protocol_version: z.literal(PROTOCOL_VERSION),
    account: AccountSchema,
  })
  .strict();
export type AccountResponse = z.infer<typeof AccountResponseSchema>;

export const AccountDevicesResponseSchema = z
  .object({
    protocol_version: z.literal(PROTOCOL_VERSION),
    devices: z.array(AccountDeviceSchema).max(256),
  })
  .strict();
export type AccountDevicesResponse = z.infer<typeof AccountDevicesResponseSchema>;

const NativeClientSchema = z.literal("quotacli");
const InstallationIdSchema = z.string().uuid();

export const BrowserLoginExchangeRequestSchema = z
  .object({
    protocol_version: z.literal(PROTOCOL_VERSION),
    grant_type: z.literal("authorization_code"),
    client_id: NativeClientSchema,
    code: SecretSchema,
    code_verifier: z.string().regex(PKCE_VERIFIER_PATTERN),
    redirect_uri: LoopbackRedirectUriSchema,
    installation_id: InstallationIdSchema,
    device_display_name: DisplayNameSchema,
    platform: PlatformSchema,
  })
  .strict();
export type BrowserLoginExchangeRequest = z.infer<typeof BrowserLoginExchangeRequestSchema>;

export const DeviceAuthorizationRequestSchema = z
  .object({
    protocol_version: z.literal(PROTOCOL_VERSION),
    client_id: NativeClientSchema,
    installation_id: InstallationIdSchema,
    device_display_name: DisplayNameSchema,
    platform: PlatformSchema,
  })
  .strict();
export type DeviceAuthorizationRequest = z.infer<typeof DeviceAuthorizationRequestSchema>;

export const DeviceAuthorizationResponseSchema = z
  .object({
    protocol_version: z.literal(PROTOCOL_VERSION),
    device_code: SecretSchema,
    user_code: z.string().trim().min(1).max(32),
    verification_uri: z.string().url().max(2_048).refine(isHttpsUrl, "Expected an HTTPS URL."),
    verification_uri_complete: z
      .string()
      .url()
      .max(2_048)
      .refine(isHttpsUrl, "Expected an HTTPS URL.")
      .nullable(),
    expires_in: SafePositiveIntegerSchema.max(600),
    interval: SafePositiveIntegerSchema.max(60),
  })
  .strict();
export type DeviceAuthorizationResponse = z.infer<typeof DeviceAuthorizationResponseSchema>;

export const DeviceAuthorizationDecisionRequestSchema = z
  .object({
    protocol_version: z.literal(PROTOCOL_VERSION),
    user_code: z.string().trim().min(1).max(32),
    decision: z.enum(["approve", "deny"]),
  })
  .strict();
export type DeviceAuthorizationDecisionRequest = z.infer<
  typeof DeviceAuthorizationDecisionRequestSchema
>;

const DeviceCodeTokenRequestSchema = z
  .object({
    protocol_version: z.literal(PROTOCOL_VERSION),
    grant_type: z.literal("urn:ietf:params:oauth:grant-type:device_code"),
    client_id: NativeClientSchema,
    device_code: SecretSchema,
  })
  .strict();

export const OAuthTokenRequestSchema = z.discriminatedUnion("grant_type", [
  BrowserLoginExchangeRequestSchema,
  DeviceCodeTokenRequestSchema,
]);
export type OAuthTokenRequest = z.infer<typeof OAuthTokenRequestSchema>;

export const SessionTokenSchema = z
  .object({
    access_token: SecretSchema,
    access_expires_at: Rfc3339InstantSchema,
    refresh_token: SecretSchema,
    refresh_expires_at: Rfc3339InstantSchema,
  })
  .strict();
export type SessionToken = z.infer<typeof SessionTokenSchema>;

export const OAuthTokenResponseSchema = z
  .object({
    protocol_version: z.literal(PROTOCOL_VERSION),
    token_type: z.literal("Bearer"),
    account_id: OpaqueIdSchema,
    device_id: OpaqueIdSchema,
    device_generation: SafePositiveIntegerSchema,
    next_snapshot_sequence: SafeNonnegativeIntegerSchema,
    next_usage_sequence: SafeNonnegativeIntegerSchema,
    usage_deleted_before: Rfc3339InstantSchema.nullable(),
    usage_sync_revision: SafeNonnegativeIntegerSchema,
    account_session: SessionTokenSchema,
    device_session: SessionTokenSchema,
  })
  .strict();
export type OAuthTokenResponse = z.infer<typeof OAuthTokenResponseSchema>;

export const SessionRefreshRequestSchema = z
  .object({
    protocol_version: z.literal(PROTOCOL_VERSION),
    grant_type: z.literal("refresh_token"),
    client_id: NativeClientSchema,
    token_audience: z.enum(["account", "device"]),
    refresh_token: SecretSchema,
  })
  .strict();
export type SessionRefreshRequest = z.infer<typeof SessionRefreshRequestSchema>;

const AccountSessionRefreshResponseSchema = z
  .object({
    protocol_version: z.literal(PROTOCOL_VERSION),
    token_type: z.literal("Bearer"),
    token_audience: z.literal("account"),
    account_id: OpaqueIdSchema,
    account_session: SessionTokenSchema,
  })
  .strict();

const DeviceSessionRefreshResponseSchema = z
  .object({
    protocol_version: z.literal(PROTOCOL_VERSION),
    token_type: z.literal("Bearer"),
    token_audience: z.literal("device"),
    account_id: OpaqueIdSchema,
    device_id: OpaqueIdSchema,
    device_generation: SafePositiveIntegerSchema,
    device_session: SessionTokenSchema,
  })
  .strict();

export const SessionRefreshResponseSchema = z.discriminatedUnion("token_audience", [
  AccountSessionRefreshResponseSchema,
  DeviceSessionRefreshResponseSchema,
]);
export type SessionRefreshResponse = z.infer<typeof SessionRefreshResponseSchema>;

export const DeviceSyncResponseSchema = z
  .object({
    protocol_version: z.literal(PROTOCOL_VERSION),
    account_id: OpaqueIdSchema,
    device_id: OpaqueIdSchema,
    device_generation: SafePositiveIntegerSchema,
    next_snapshot_sequence: SafeNonnegativeIntegerSchema,
    next_usage_sequence: SafeNonnegativeIntegerSchema,
    usage_deleted_before: Rfc3339InstantSchema.nullable(),
    usage_sync_revision: SafeNonnegativeIntegerSchema,
  })
  .strict();
export type DeviceSyncResponse = z.infer<typeof DeviceSyncResponseSchema>;

export const LogoutResponseSchema = z
  .object({
    protocol_version: z.literal(PROTOCOL_VERSION),
    status: z.literal("signed_out"),
  })
  .strict();
export type LogoutResponse = z.infer<typeof LogoutResponseSchema>;

export const DeleteDeviceResponseSchema = z
  .object({
    protocol_version: z.literal(PROTOCOL_VERSION),
    status: z.literal("deleted"),
    device_id: OpaqueIdSchema,
    device_generation: SafePositiveIntegerSchema,
    deleted_before: Rfc3339InstantSchema,
  })
  .strict();
export type DeleteDeviceResponse = z.infer<typeof DeleteDeviceResponseSchema>;

export const BILLING_AGENTS = ["codex", "claude_code", "grok", "opencode", "pi"] as const;
export const BillingAgentSchema = z.enum(BILLING_AGENTS);
export type BillingAgent = z.infer<typeof BillingAgentSchema>;

export const BillingChannelSchema = z.enum([
  "openai_direct",
  "azure_openai",
  "anthropic_direct",
  "aws_bedrock",
  "google_vertex",
  "openrouter",
  "xai_direct",
  "unknown",
]);
export type BillingChannel = z.infer<typeof BillingChannelSchema>;

export const PricedBillingChannelSchema = z.enum([
  "openai_direct",
  "azure_openai",
  "anthropic_direct",
  "aws_bedrock",
  "google_vertex",
  "openrouter",
  "xai_direct",
]);
export type PricedBillingChannel = z.infer<typeof PricedBillingChannelSchema>;

export const ChannelSourceSchema = z.enum(["explicit", "agent_default", "unknown"]);
export type ChannelSource = z.infer<typeof ChannelSourceSchema>;

export const ContextBucketSchema = z.enum([
  "le_128k",
  "gt_128k_le_200k",
  "gt_200k_le_256k",
  "gt_256k_le_272k",
  "gt_272k",
]);
export type ContextBucket = z.infer<typeof ContextBucketSchema>;

export const CoverageStatusSchema = z.enum(["complete", "partial"]);
export type CoverageStatus = z.infer<typeof CoverageStatusSchema>;

export const UsageCoverageSchema = z
  .object({
    agent: BillingAgentSchema,
    start_at: UtcHourSchema,
    end_at: UtcHourSchema,
    status: CoverageStatusSchema,
  })
  .strict()
  .superRefine(validateCoverageRange);
export type UsageCoverage = z.infer<typeof UsageCoverageSchema>;

const LocalUsageCoverageSchema = z
  .object({
    agent: BillingAgentSchema,
    start_at: UtcHourSchema,
    end_at: UtcHourSchema,
    status: CoverageStatusSchema,
  })
  .strict()
  .superRefine(validateCoverageOrder);

const UsageHourlyFactWireSchema = z
  .object({
    bucket_start_utc: UtcHourSchema,
    usage_date: UsageDateSchema,
    usage_hour: z.number().int().min(0).max(23),
    agent: BillingAgentSchema,
    billing_channel: BillingChannelSchema,
    channel_source: ChannelSourceSchema,
    model: ModelSchema,
    context_bucket: ContextBucketSchema,
    service_tier: BillingDimensionSchema,
    speed: BillingDimensionSchema,
    inference_geo: BillingDimensionSchema,
    input_tokens: SafeNonnegativeIntegerSchema,
    cache_read_tokens: SafeNonnegativeIntegerSchema,
    cache_write_5m_tokens: SafeNonnegativeIntegerSchema,
    cache_write_1h_tokens: SafeNonnegativeIntegerSchema,
    cache_write_inferred_tokens: SafeNonnegativeIntegerSchema,
    output_tokens: SafeNonnegativeIntegerSchema,
    reasoning_tokens: SafeNonnegativeIntegerSchema,
    requests: SafePositiveIntegerSchema,
    web_search_requests: SafeNonnegativeIntegerSchema,
    web_fetch_requests: SafeNonnegativeIntegerSchema,
    source_cost_microusd: z.string().max(32).regex(NONNEGATIVE_INTEGER_PATTERN).optional(),
    source_cost_covered_requests: SafeNonnegativeIntegerSchema,
  })
  .strict()
  .superRefine((fact, context) => {
    validateUsageCounts(fact, context);
    if ((fact.billing_channel === "unknown") !== (fact.channel_source === "unknown")) {
      context.addIssue({
        code: "custom",
        path: ["channel_source"],
        message: "Unknown billing channel and channel source must be used together.",
      });
    }
  });
// `model` is provider-owned opaque text. The literal "unknown" is a valid explicit model.
export const UsageHourlyFactSchema = UsageHourlyFactWireSchema;
export type UsageHourlyFact = z.infer<typeof UsageHourlyFactSchema>;

export const UsageSubmissionWriteModeSchema = z.literal("merge_partial");
export type UsageSubmissionWriteMode = z.infer<typeof UsageSubmissionWriteModeSchema>;

export const UsageSubmissionMultipartSchema = z
  .object({
    batch_id: OpaqueIdSchema,
    part_index: SafeNonnegativeIntegerSchema,
    part_count: SafePositiveIntegerSchema.max(MAXIMUM_USAGE_MULTIPART_PARTS),
  })
  .strict()
  .superRefine((part, context) => {
    if (part.part_count < 2) {
      context.addIssue({
        code: "custom",
        path: ["part_count"],
        message: "Multipart submissions must contain at least two parts.",
      });
    }
    if (part.part_index >= part.part_count) {
      context.addIssue({
        code: "custom",
        path: ["part_index"],
        message: "Multipart part index must be less than part count.",
      });
    }
  });
export type UsageSubmissionMultipart = z.infer<typeof UsageSubmissionMultipartSchema>;

export const UsageSubmissionSchema = z
  .object({
    protocol_version: z.literal(PROTOCOL_VERSION),
    submission_id: OpaqueIdSchema,
    device_id: OpaqueIdSchema,
    generation: SafePositiveIntegerSchema,
    sequence: SafeNonnegativeIntegerSchema,
    parser_revision: OpaqueIdSchema,
    aggregation_timezone: IanaTimezoneSchema,
    coverage: UsageCoverageSchema,
    rows: z.array(UsageHourlyFactWireSchema).max(MAXIMUM_USAGE_ROWS_PER_SUBMISSION),
    write_mode: UsageSubmissionWriteModeSchema.optional(),
    multipart: UsageSubmissionMultipartSchema.optional(),
  })
  .strict()
  .superRefine((submission, context) => {
    const start = Date.parse(submission.coverage.start_at);
    const end = Date.parse(submission.coverage.end_at);
    let localFormatter: Intl.DateTimeFormat | null = null;
    try {
      localFormatter = new Intl.DateTimeFormat("en", {
        timeZone: submission.aggregation_timezone,
        year: "numeric",
        month: "2-digit",
        day: "2-digit",
        hour: "2-digit",
        hourCycle: "h23",
      });
    } catch {
      // IanaTimezoneSchema reports the boundary error.
    }
    const identities = new Set<string>();
    if (submission.write_mode && submission.coverage.status !== "partial") {
      context.addIssue({
        code: "custom",
        path: ["coverage", "status"],
        message: "merge_partial submissions require partial coverage.",
      });
    }
    for (const [index, row] of submission.rows.entries()) {
      if (row.agent !== submission.coverage.agent) {
        context.addIssue({
          code: "custom",
          path: ["rows", index, "agent"],
          message: "Row agent must match coverage agent.",
        });
      }
      const bucket = Date.parse(row.bucket_start_utc);
      if (bucket < start || bucket >= end) {
        context.addIssue({
          code: "custom",
          path: ["rows", index, "bucket_start_utc"],
          message: "Row bucket must fall inside coverage.",
        });
      }
      if (
        localFormatter &&
        !localProjectionMatches(localFormatter, bucket, row.usage_date, row.usage_hour)
      ) {
        context.addIssue({
          code: "custom",
          path: ["rows", index, "usage_date"],
          message: "Row local date/hour must be possible in the aggregation timezone.",
        });
      }
      const identity = usageHourlyFactIdentity(row);
      if (identities.has(identity)) {
        context.addIssue({
          code: "custom",
          path: ["rows", index],
          message: "Hourly fact identities must be unique within a submission.",
        });
      }
      identities.add(identity);
    }
  });
export type UsageSubmissionV2 = z.infer<typeof UsageSubmissionSchema>;

export const UsageCostModeSchema = z.enum(["calculate", "auto", "reported"]);
export type UsageCostMode = z.infer<typeof UsageCostModeSchema>;

export const UsageCostBasisSchema = z.enum(["calculated", "reported", "mixed", "none"]);
export type UsageCostBasis = z.infer<typeof UsageCostBasisSchema>;

export const UsageCostStatusSchema = z.enum(["complete", "partial", "unavailable"]);
export type UsageCostStatus = z.infer<typeof UsageCostStatusSchema>;

export const UsageCostAssumptionSchema = z.enum([
  "agent_default_channel",
  "model_alias",
  "wildcard_service_tier",
  "wildcard_speed",
  "wildcard_inference_geo",
  "wildcard_context_bucket",
  "cache_write_inferred_rate",
  "source_reported",
]);
export type UsageCostAssumption = z.infer<typeof UsageCostAssumptionSchema>;

export const UsageUnpricedReasonSchema = z.enum([
  "unknown_channel",
  "unknown_model",
  "outside_effective_range",
  "unsupported_dimensions",
  "ambiguous_price",
  "missing_rate",
  "incomplete_source_cost",
  "invalid_catalog",
]);
export type UsageUnpricedReason = z.infer<typeof UsageUnpricedReasonSchema>;

export const UsageUnpricedItemSchema = z
  .object({
    billing_channel: BillingChannelSchema,
    model: ModelSchema,
    reason: UsageUnpricedReasonSchema,
    rows: SafePositiveIntegerSchema,
  })
  .strict();
export type UsageUnpricedItem = z.infer<typeof UsageUnpricedItemSchema>;

export const UsageCostOutcomeSchema = z
  .object({
    mode: UsageCostModeSchema,
    basis: UsageCostBasisSchema,
    status: UsageCostStatusSchema,
    amount_microusd: z.string().max(32).regex(NONNEGATIVE_INTEGER_PATTERN).nullable(),
    catalog_revision: OpaqueIdSchema.nullable(),
    calculated_rows: SafeNonnegativeIntegerSchema,
    reported_rows: SafeNonnegativeIntegerSchema,
    unpriced_rows: SafeNonnegativeIntegerSchema,
    assumptions: z.array(UsageCostAssumptionSchema).max(16),
    unpriced: z.array(UsageUnpricedItemSchema).max(MAXIMUM_UNPRICED_ITEMS),
    unpriced_truncated: z.literal(true).optional(),
  })
  .strict()
  .superRefine(validateCostOutcome);
export type UsageCostOutcome = z.infer<typeof UsageCostOutcomeSchema>;

export const UsageTokenTotalsSchema = z
  .object({
    input_tokens: SafeNonnegativeIntegerSchema,
    cache_read_tokens: SafeNonnegativeIntegerSchema,
    cache_write_5m_tokens: SafeNonnegativeIntegerSchema,
    cache_write_1h_tokens: SafeNonnegativeIntegerSchema,
    cache_write_inferred_tokens: SafeNonnegativeIntegerSchema,
    output_tokens: SafeNonnegativeIntegerSchema,
    reasoning_tokens: SafeNonnegativeIntegerSchema,
    requests: SafeNonnegativeIntegerSchema,
    web_search_requests: SafeNonnegativeIntegerSchema,
    web_fetch_requests: SafeNonnegativeIntegerSchema,
    source_cost_microusd: z.string().max(32).regex(NONNEGATIVE_INTEGER_PATTERN).nullable(),
    source_cost_covered_requests: SafeNonnegativeIntegerSchema,
  })
  .strict()
  .superRefine(validateUsageCounts);
export type UsageTokenTotals = z.infer<typeof UsageTokenTotalsSchema>;

export const UsageBreakdownDimensionSchema = z.enum([
  "device",
  "agent",
  "model",
  "billing_channel",
  "usage_date",
  "bucket_start_utc",
]);
export type UsageBreakdownDimension = z.infer<typeof UsageBreakdownDimensionSchema>;

const UsageBreakdownOtherDimensionSchema = z.enum([
  "device",
  "agent",
  "billing_channel",
  "usage_date",
  "bucket_start_utc",
]);
const UsageBreakdownFields = {
  totals: UsageTokenTotalsSchema,
  cost: UsageCostOutcomeSchema,
};

export const UsageBreakdownSchema = z.discriminatedUnion("dimension", [
  z
    .object({
      dimension: z.literal("model"),
      key: ModelSchema,
      ...UsageBreakdownFields,
    })
    .strict(),
  z
    .object({
      dimension: UsageBreakdownOtherDimensionSchema,
      key: z.string().min(1).max(128),
      ...UsageBreakdownFields,
    })
    .strict(),
]);
export type UsageBreakdown = z.infer<typeof UsageBreakdownSchema>;

export const UsageCoverageSummaryItemSchema = z
  .object({
    device_id: OpaqueIdSchema,
    agent: BillingAgentSchema,
    start_at: UtcHourSchema,
    end_at: UtcHourSchema,
    status: CoverageStatusSchema,
  })
  .strict()
  .superRefine(validateCoverageRange);
export type UsageCoverageSummaryItem = z.infer<typeof UsageCoverageSummaryItemSchema>;

export const UsageDateRangeSchema = z
  .object({
    from: UsageDateSchema,
    to: UsageDateSchema,
  })
  .strict()
  .superRefine((range, context) => {
    const from = Date.parse(`${range.from}T00:00:00Z`);
    const to = Date.parse(`${range.to}T00:00:00Z`);
    if (from > to) {
      context.addIssue({ code: "custom", path: ["to"], message: "to must not precede from." });
    }
  });
export type UsageDateRange = z.infer<typeof UsageDateRangeSchema>;

export const AccountUsageSummarySchema = z
  .object({
    range: UsageDateRangeSchema,
    totals: UsageTokenTotalsSchema,
    cost: UsageCostOutcomeSchema,
    coverage: z.array(UsageCoverageSummaryItemSchema).max(MAXIMUM_USAGE_COVERAGE_ITEMS),
    breakdowns: z.array(UsageBreakdownSchema).max(MAXIMUM_USAGE_BREAKDOWNS),
    coverage_truncated: z.literal(true).optional(),
    breakdowns_truncated: z.literal(true).optional(),
  })
  .strict();
export type AccountUsageSummary = z.infer<typeof AccountUsageSummarySchema>;

export const LocalUsageReportStatusSchema = z.enum(["complete", "partial", "unavailable"]);
export type LocalUsageReportStatus = z.infer<typeof LocalUsageReportStatusSchema>;

export const LocalUsageReportSchema = z
  .object({
    protocol_version: z.literal(PROTOCOL_VERSION),
    generated_at: Rfc3339InstantSchema,
    aggregation_timezone: IanaTimezoneSchema.nullable(),
    range: UsageDateRangeSchema,
    status: LocalUsageReportStatusSchema,
    totals: UsageTokenTotalsSchema.nullable(),
    cost: UsageCostOutcomeSchema.nullable(),
    coverage: z.array(LocalUsageCoverageSchema).max(MAXIMUM_USAGE_COVERAGE_ITEMS),
    breakdowns: z.array(UsageBreakdownSchema).max(MAXIMUM_USAGE_BREAKDOWNS),
    coverage_truncated: z.literal(true).optional(),
    breakdowns_truncated: z.literal(true).optional(),
  })
  .strict()
  .superRefine((report, context) => {
    const unavailable = report.status === "unavailable";
    if (
      unavailable !==
      (report.aggregation_timezone === null && report.totals === null && report.cost === null)
    ) {
      context.addIssue({
        code: "custom",
        path: ["status"],
        message: "Unavailable local Usage must omit timezone, totals, and cost.",
      });
    }
    if (unavailable && (report.coverage.length > 0 || report.breakdowns.length > 0)) {
      context.addIssue({
        code: "custom",
        path: ["coverage"],
        message: "Unavailable local Usage cannot contain coverage or breakdowns.",
      });
    }
    if (!unavailable) {
      const expected = report.coverage.every((item) => item.status === "complete")
        ? "complete"
        : "partial";
      if (report.status !== expected) {
        context.addIssue({
          code: "custom",
          path: ["status"],
          message: "Local Usage status must reflect its coverage.",
        });
      }
    }
  });
export type LocalUsageReport = z.infer<typeof LocalUsageReportSchema>;

export const AccountUsageResponseSchema = z
  .object({
    protocol_version: z.literal(PROTOCOL_VERSION),
    usage: AccountUsageSummarySchema,
  })
  .strict();
export type AccountUsageResponse = z.infer<typeof AccountUsageResponseSchema>;

export const AccountQuotaObservationSchema = z
  .object({
    device_id: OpaqueIdSchema,
    sequence: SafeNonnegativeIntegerSchema,
    captured_at: Rfc3339InstantSchema,
    snapshot: QuotaSnapshotSchema,
    updated_at: Rfc3339InstantSchema,
  })
  .strict();
export type AccountQuotaObservation = z.infer<typeof AccountQuotaObservationSchema>;

export const AccountQuotaResponseSchema = z
  .object({
    protocol_version: z.literal(PROTOCOL_VERSION),
    quota: z.array(AccountQuotaObservationSchema).max(8_192),
  })
  .strict();
export type AccountQuotaResponse = z.infer<typeof AccountQuotaResponseSchema>;

export const AccountUsageHourlyFactSchema = UsageHourlyFactSchema.safeExtend({
  device_id: OpaqueIdSchema,
  aggregation_timezone: IanaTimezoneSchema,
}).superRefine((fact, context) => {
  const bucket = Date.parse(fact.bucket_start_utc);
  const formatter = new Intl.DateTimeFormat("en", {
    timeZone: fact.aggregation_timezone,
    year: "numeric",
    month: "2-digit",
    day: "2-digit",
    hour: "2-digit",
    hourCycle: "h23",
  });
  if (!localProjectionMatches(formatter, bucket, fact.usage_date, fact.usage_hour)) {
    context.addIssue({
      code: "custom",
      path: ["usage_date"],
      message: "Row local date/hour must match aggregation_timezone.",
    });
  }
});
export type AccountUsageHourlyFact = z.infer<typeof AccountUsageHourlyFactSchema>;

export const AccountUsageHourlyResponseSchema = z
  .object({
    protocol_version: z.literal(PROTOCOL_VERSION),
    start_at: UtcHourSchema,
    end_at: UtcHourSchema,
    facts: z.array(AccountUsageHourlyFactSchema).max(MAXIMUM_USAGE_READ_ROWS),
    coverage: z.array(UsageCoverageSummaryItemSchema).max(MAXIMUM_USAGE_COVERAGE_ITEMS),
    cost: UsageCostOutcomeSchema,
    coverage_truncated: z.literal(true).optional(),
  })
  .strict()
  .superRefine((response, context) => {
    validateCoverageRange(response, context);
    const start = Date.parse(response.start_at);
    const end = Date.parse(response.end_at);
    for (const [index, fact] of response.facts.entries()) {
      const bucket = Date.parse(fact.bucket_start_utc);
      if (bucket < start || bucket >= end) {
        context.addIssue({
          code: "custom",
          path: ["facts", index, "bucket_start_utc"],
          message: "Hourly fact must fall inside the response range.",
        });
      }
    }
    const costRows =
      response.cost.calculated_rows + response.cost.reported_rows + response.cost.unpriced_rows;
    if (!Number.isSafeInteger(costRows) || costRows !== response.facts.length) {
      context.addIssue({
        code: "custom",
        path: ["cost"],
        message: "Cost row counts must match the hourly facts.",
      });
    }
  });
export type AccountUsageHourlyResponse = z.infer<typeof AccountUsageHourlyResponseSchema>;

export const AccountSummarySchema = z
  .object({
    protocol_version: z.literal(PROTOCOL_VERSION),
    generated_at: Rfc3339InstantSchema,
    account: AccountSchema,
    devices: z.array(AccountDeviceSchema).max(256),
    quota: z.array(AccountQuotaObservationSchema).max(8_192),
    usage: AccountUsageSummarySchema,
  })
  .strict();
export type AccountSummary = z.infer<typeof AccountSummarySchema>;

export const QuotaSnapshotUploadResponseSchema = z
  .object({
    protocol_version: z.literal(PROTOCOL_VERSION),
    outcome: z.enum(["accepted", "duplicate"]),
    device_id: OpaqueIdSchema,
    device_generation: SafePositiveIntegerSchema,
    accepted_sequence: SafeNonnegativeIntegerSchema,
    next_snapshot_sequence: SafeNonnegativeIntegerSchema,
  })
  .strict();
export type QuotaSnapshotUploadResponse = z.infer<typeof QuotaSnapshotUploadResponseSchema>;

export const UsageUploadOutcomeSchema = z.enum([
  "accepted",
  "duplicate",
  "partial",
  "sequence_conflict",
  "stale_generation",
  "deleted",
]);
export type UsageUploadOutcome = z.infer<typeof UsageUploadOutcomeSchema>;

export const UsageUploadResponseSchema = z
  .object({
    protocol_version: z.literal(PROTOCOL_VERSION),
    outcome: UsageUploadOutcomeSchema,
    device_id: OpaqueIdSchema,
    device_generation: SafePositiveIntegerSchema,
    accepted_sequence: SafeNonnegativeIntegerSchema.nullable(),
    next_sequence: SafeNonnegativeIntegerSchema,
    usage_sync_revision: SafeNonnegativeIntegerSchema,
    deleted_before: Rfc3339InstantSchema.nullable(),
  })
  .strict()
  .superRefine((response, context) => {
    const accepted = response.outcome === "accepted" || response.outcome === "duplicate";
    if (accepted !== (response.accepted_sequence !== null)) {
      context.addIssue({
        code: "custom",
        path: ["accepted_sequence"],
        message: "accepted_sequence is present only for accepted or duplicate uploads.",
      });
    }
    if ((response.outcome === "deleted") !== (response.deleted_before !== null)) {
      context.addIssue({
        code: "custom",
        path: ["deleted_before"],
        message: "deleted_before is present only for a deleted device.",
      });
    }
  });
export type UsageUploadResponse = z.infer<typeof UsageUploadResponseSchema>;

export const DecimalAmountSchema = z.string().min(1).max(32).regex(DECIMAL_PATTERN);
export type DecimalAmount = z.infer<typeof DecimalAmountSchema>;

export const PricingRatesSchema = z
  .object({
    uncached_input_per_million: DecimalAmountSchema.nullable(),
    cache_read_per_million: DecimalAmountSchema.nullable(),
    cache_write_5m_per_million: DecimalAmountSchema.nullable(),
    cache_write_1h_per_million: DecimalAmountSchema.nullable(),
    cache_write_inferred_per_million: DecimalAmountSchema.nullable(),
    output_per_million: DecimalAmountSchema.nullable(),
    web_search_per_request: DecimalAmountSchema.nullable(),
    web_fetch_per_request: DecimalAmountSchema.nullable(),
  })
  .strict()
  .refine((rates) => Object.values(rates).some((rate) => rate !== null), {
    message: "A pricing entry must define at least one rate.",
  });
export type PricingRates = z.infer<typeof PricingRatesSchema>;

export const PricingDimensionSchema = z.union([BillingDimensionSchema, z.literal("*")]);
export type PricingDimension = z.infer<typeof PricingDimensionSchema>;

export const PricingContextBucketSchema = z.union([ContextBucketSchema, z.literal("*")]);
export type PricingContextBucket = z.infer<typeof PricingContextBucketSchema>;

export const PricingCatalogEntrySchema = z
  .object({
    entry_id: OpaqueIdSchema,
    billing_channel: PricedBillingChannelSchema,
    model: ModelSchema,
    aliases: z.array(ModelSchema).max(16),
    effective_from: UsageDateSchema,
    effective_to: UsageDateSchema.nullable(),
    service_tier: PricingDimensionSchema,
    speed: PricingDimensionSchema,
    inference_geo: PricingDimensionSchema,
    context_bucket: PricingContextBucketSchema,
    currency: z.literal("USD"),
    rates: PricingRatesSchema,
    source_url: z.string().url().max(2_048).refine(isHttpsUrl, "Expected an HTTPS URL."),
    verified_at: Rfc3339InstantSchema,
  })
  .strict()
  .superRefine((entry, context) => {
    if (entry.effective_to !== null && entry.effective_to <= entry.effective_from) {
      context.addIssue({
        code: "custom",
        path: ["effective_to"],
        message: "effective_to must be later than effective_from.",
      });
    }
    const names = [entry.model, ...entry.aliases];
    if (new Set(names).size !== names.length) {
      context.addIssue({
        code: "custom",
        path: ["aliases"],
        message: "Model and aliases must be unique within an entry.",
      });
    }
  });
export type PricingCatalogEntry = z.infer<typeof PricingCatalogEntrySchema>;

/** Structure only; quota-model performs catalog-wide ambiguity validation. */
export const PricingCatalogSchema = z
  .object({
    protocol_version: z.literal(PROTOCOL_VERSION),
    revision: OpaqueIdSchema,
    published_at: Rfc3339InstantSchema,
    entries: z.array(PricingCatalogEntrySchema).max(MAXIMUM_PRICING_ENTRIES),
  })
  .strict();
export type PricingCatalog = z.infer<typeof PricingCatalogSchema>;

export const RelayErrorCodeSchema = z.enum([
  "invalid_request",
  "unauthorized",
  "forbidden",
  "not_found",
  "authorization_pending",
  "slow_down",
  "access_denied",
  "expired_token",
  "invalid_grant",
  "rate_limited",
  "sequence_conflict",
  "stale_generation",
  "device_deleted",
  "client_upgrade_required",
  "conflict",
  "internal_error",
]);
export type RelayErrorCode = z.infer<typeof RelayErrorCodeSchema>;

export const RelayErrorEnvelopeSchema = z
  .object({
    error: z
      .object({
        code: RelayErrorCodeSchema,
        message: z.string().trim().min(1).max(512),
      })
      .strict(),
  })
  .strict();
export type RelayErrorEnvelope = z.infer<typeof RelayErrorEnvelopeSchema>;

function isCalendarDate(value: string): boolean {
  const instant = new Date(`${value}T00:00:00Z`);
  return !Number.isNaN(instant.getTime()) && instant.toISOString().slice(0, 10) === value;
}

function isCanonicalUtcHour(value: string): boolean {
  const instant = Date.parse(value);
  return (
    Number.isFinite(instant) && new Date(instant).toISOString().replace(".000Z", "Z") === value
  );
}

function isIanaTimezone(value: string): boolean {
  try {
    new Intl.DateTimeFormat("en", { timeZone: value }).format(0);
    return true;
  } catch {
    return false;
  }
}

function isHttpsUrl(value: string): boolean {
  try {
    return new URL(value).protocol === "https:";
  } catch {
    return false;
  }
}

function isLoopbackRedirectUri(value: string): boolean {
  try {
    const url = new URL(value);
    return (
      url.protocol === "http:" &&
      (url.hostname === "127.0.0.1" || url.hostname === "[::1]" || url.hostname === "::1") &&
      url.port !== "" &&
      url.username === "" &&
      url.password === "" &&
      url.search === "" &&
      url.hash === ""
    );
  } catch {
    return false;
  }
}

function localProjectionMatches(
  formatter: Intl.DateTimeFormat,
  bucketStart: number,
  usageDate: string,
  usageHour: number,
): boolean {
  return [bucketStart, bucketStart + 3_600_000 - 1].some((instant) => {
    const parts = Object.fromEntries(
      formatter
        .formatToParts(instant)
        .filter((part) => part.type !== "literal")
        .map((part) => [part.type, part.value]),
    );
    return (
      `${parts.year}-${parts.month}-${parts.day}` === usageDate && Number(parts.hour) === usageHour
    );
  });
}

function usageHourlyFactIdentity(fact: z.infer<typeof UsageHourlyFactSchema>): string {
  return JSON.stringify([
    fact.bucket_start_utc,
    fact.usage_date,
    fact.usage_hour,
    fact.agent,
    fact.billing_channel,
    fact.channel_source,
    fact.model,
    fact.context_bucket,
    fact.service_tier,
    fact.speed,
    fact.inference_geo,
  ]);
}

function validateCoverageRange(
  coverage: { start_at: string; end_at: string },
  context: z.RefinementCtx,
): void {
  validateCoverageOrder(coverage, context);
  const start = Date.parse(coverage.start_at);
  const end = Date.parse(coverage.end_at);
  if (end <= start) return;
  if ((end - start) / 3_600_000 > MAXIMUM_USAGE_COVERAGE_HOURS) {
    context.addIssue({
      code: "custom",
      path: ["end_at"],
      message: `Coverage may span at most ${MAXIMUM_USAGE_COVERAGE_HOURS} hours.`,
    });
  }
}

function validateCoverageOrder(
  coverage: { start_at: string; end_at: string },
  context: z.RefinementCtx,
): void {
  if (Date.parse(coverage.end_at) <= Date.parse(coverage.start_at)) {
    context.addIssue({
      code: "custom",
      path: ["end_at"],
      message: "Coverage end_at must be later than start_at.",
    });
  }
}

function validateUsageCounts(
  value: {
    input_tokens: number;
    cache_read_tokens: number;
    cache_write_5m_tokens: number;
    cache_write_1h_tokens: number;
    cache_write_inferred_tokens: number;
    output_tokens: number;
    reasoning_tokens: number;
    requests: number;
    web_search_requests: number;
    web_fetch_requests: number;
    source_cost_microusd?: string | null | undefined;
    source_cost_covered_requests: number;
  },
  context: z.RefinementCtx,
): void {
  const classifiedInput =
    value.cache_read_tokens +
    value.cache_write_5m_tokens +
    value.cache_write_1h_tokens +
    value.cache_write_inferred_tokens;
  if (!Number.isSafeInteger(classifiedInput) || classifiedInput > value.input_tokens) {
    context.addIssue({
      code: "custom",
      path: ["input_tokens"],
      message: "Cache token subsets must not exceed input_tokens.",
    });
  }
  if (value.reasoning_tokens > value.output_tokens) {
    context.addIssue({
      code: "custom",
      path: ["reasoning_tokens"],
      message: "reasoning_tokens must not exceed output_tokens.",
    });
  }
  if (value.source_cost_covered_requests > value.requests) {
    context.addIssue({
      code: "custom",
      path: ["source_cost_covered_requests"],
      message: "Source cost coverage must not exceed requests.",
    });
  }
  if (value.requests === 0 && (value.web_search_requests > 0 || value.web_fetch_requests > 0)) {
    context.addIssue({
      code: "custom",
      path: ["requests"],
      message: "Billable tool requests require at least one request.",
    });
  }
  const hasSourceCost =
    value.source_cost_microusd !== undefined && value.source_cost_microusd !== null;
  if (hasSourceCost !== value.source_cost_covered_requests > 0) {
    context.addIssue({
      code: "custom",
      path: ["source_cost_microusd"],
      message: "Source cost is present exactly when it covers at least one request.",
    });
  }
}

function validateCostOutcome(
  outcome: z.infer<typeof UsageCostOutcomeSchema>,
  context: z.RefinementCtx,
) {
  const pricedRows = outcome.calculated_rows + outcome.reported_rows;
  if (!Number.isSafeInteger(pricedRows)) {
    context.addIssue({ code: "custom", path: ["calculated_rows"], message: "Row count overflow." });
  }
  const expectedBasis =
    outcome.calculated_rows > 0 && outcome.reported_rows > 0
      ? "mixed"
      : outcome.calculated_rows > 0
        ? "calculated"
        : outcome.reported_rows > 0
          ? "reported"
          : "none";
  if (outcome.basis !== expectedBasis) {
    context.addIssue({
      code: "custom",
      path: ["basis"],
      message: "Cost basis must match calculated and reported row counts.",
    });
  }
  const expectedStatus =
    outcome.unpriced_rows === 0 ? "complete" : pricedRows > 0 ? "partial" : "unavailable";
  if (outcome.status !== expectedStatus) {
    context.addIssue({
      code: "custom",
      path: ["status"],
      message: "Cost status must match priced and unpriced row counts.",
    });
  }
  if (pricedRows > 0 !== (outcome.amount_microusd !== null)) {
    context.addIssue({
      code: "custom",
      path: ["amount_microusd"],
      message: "Cost amount is present exactly when at least one row is priced.",
    });
  }
  const detailedUnpricedRows = outcome.unpriced.reduce((sum, item) => sum + item.rows, 0);
  if (
    outcome.unpriced_truncated
      ? detailedUnpricedRows > outcome.unpriced_rows
      : detailedUnpricedRows !== outcome.unpriced_rows
  ) {
    context.addIssue({
      code: "custom",
      path: ["unpriced"],
      message: "Unpriced item counts must sum to unpriced_rows.",
    });
  }
  if (new Set(outcome.assumptions).size !== outcome.assumptions.length) {
    context.addIssue({
      code: "custom",
      path: ["assumptions"],
      message: "Cost assumptions must be unique.",
    });
  }
}
