import { z } from "zod";
import modelCatalogDocument from "../catalog/model-catalog.json" with { type: "json" };
// Generated by `pnpm generate:provider-catalog` from packages/provider/catalog.json.
import {
  LOCAL_PROVIDER_IDS,
  type LocalProviderId,
  LocalProviderIdSchema,
  PROVIDER_IDS,
  type ProviderId,
  ProviderIdSchema,
} from "./provider-ids.generated.ts";

export {
  LOCAL_PROVIDER_IDS,
  type LocalProviderId,
  LocalProviderIdSchema,
  PROVIDER_IDS,
  type ProviderId,
  ProviderIdSchema,
};

/**
 * Each contract carries its own version, because each evolves on its own terms. Sharing a
 * number couples two contracts that have nothing to say to each other: bumping one would
 * force the other to move with it.
 */
/** OAuth, Device authorization and control, Account metadata, and the catalogs. */
export const PROTOCOL_VERSION = 2 as const;
/** Quota, Usage, and Account summary between a Device and Relay. */
export const MANAGED_DATA_PROTOCOL_VERSION = 5 as const;
/** The private local Usage report the service hands its own app. */
export const LOCAL_USAGE_PROTOCOL_VERSION = 3 as const;
/** The private local quota collection report the service hands its own app. */
export const LOCAL_COLLECTION_PROTOCOL_VERSION = 4 as const;
export const MAXIMUM_SNAPSHOTS_PER_ENVELOPE = 32;
export const MAXIMUM_WINDOWS_PER_SNAPSHOT = 16;
export const MAXIMUM_USAGE_ROWS_PER_SUBMISSION = 2_048;
export const MAXIMUM_USAGE_COVERAGE_HOURS = 24 * 31;
/**
 * No agent this Account accepts existed before this instant, so a window reaching back past it
 * was computed from a missing lower bound rather than scanned.  Six such windows, each a
 * 31-hour-limit chunk marching forward from the Unix epoch, reached production this way.
 */
export const EARLIEST_USAGE_INSTANT = "2020-01-01T00:00:00Z";
export const MAXIMUM_USAGE_BREAKDOWNS = 1_000;
export const MAXIMUM_USAGE_READ_ROWS = 1_000;
export const MAXIMUM_USAGE_COVERAGE_ITEMS = 2_048;
export const MAXIMUM_UNPRICED_ITEMS = 100;
export const MAXIMUM_PRICING_ENTRIES = 4_096;
export const MAXIMUM_USAGE_SUBMISSION_BYTES = 1_048_576;
export const MAXIMUM_USAGE_MULTIPART_PARTS = 64;

const MAXIMUM_SAFE_INTEGER = Number.MAX_SAFE_INTEGER;
const OPAQUE_ID_PATTERN = /^[A-Za-z0-9][A-Za-z0-9._:-]*$/;
const BILLING_DIMENSION_PATTERN = /^[A-Za-z0-9][A-Za-z0-9._:+-]*$/;
// Models are provider-owned opaque text. Keep only the trust-boundary guard;
// punctuation, casing, whitespace, and Unicode are all valid model names.
const MODEL_PATTERN = /^(?=[\s\S]{1,128}$)(?![\s\S]*\p{Cc})[\s\S]+$/u;
const UTC_HOUR_PATTERN = /^\d{4}-\d{2}-\d{2}T\d{2}:00:00Z$/;
const DATE_PATTERN = /^\d{4}-\d{2}-\d{2}$/;
const NONNEGATIVE_INTEGER_PATTERN = /^(?:0|[1-9]\d*)$/;
const DECIMAL_PATTERN = /^(?:0|[1-9]\d*)(?:\.\d{1,12})?$/;
const PKCE_VERIFIER_PATTERN = /^[A-Za-z0-9._~-]{43,128}$/;

const SafeNonnegativeIntegerSchema = z.number().int().min(0).max(MAXIMUM_SAFE_INTEGER);
const SafePositiveIntegerSchema = SafeNonnegativeIntegerSchema.min(1);
const OpaqueIdSchema = z.string().min(1).max(128).regex(OPAQUE_ID_PATTERN);
const SecretSchema = z.string().min(16).max(2_048);
const DisplayNameSchema = z.string().trim().min(1).max(128);
const BillingDimensionSchema = z.string().min(1).max(64).regex(BILLING_DIMENSION_PATTERN);
const ModelSchema = z.string().min(1).regex(MODEL_PATTERN);
const LoopbackRedirectUriSchema = z
  .string()
  .url()
  .max(2_048)
  .refine(isLoopbackRedirectUri, "Expected a loopback HTTP redirect URI.");

export const Rfc3339InstantSchema = z.string().max(64).datetime({ offset: true });
export type Rfc3339Instant = z.infer<typeof Rfc3339InstantSchema>;

export const UtcHourSchema = z
  .string()
  .regex(UTC_HOUR_PATTERN)
  .refine(isCanonicalUtcHour, "Expected a valid UTC hour boundary.");
export type UtcHour = z.infer<typeof UtcHourSchema>;

export const UsageDateSchema = z
  .string()
  .regex(DATE_PATTERN)
  .refine(isCalendarDate, "Expected a valid calendar date.");
export type UsageDate = z.infer<typeof UsageDateSchema>;

export const IanaTimezoneSchema = z
  .string()
  .min(1)
  .max(64)
  .regex(/^[A-Za-z0-9._+-]+(?:\/[A-Za-z0-9._+-]+)*$/)
  .refine(isIanaTimezone, "Expected an IANA timezone.");
export type IanaTimezone = z.infer<typeof IanaTimezoneSchema>;

export const QuotaStatusSchema = z.enum([
  "available",
  "stale",
  "auth_required",
  "unavailable",
  "unsupported",
  "error",
]);
export type QuotaStatus = z.infer<typeof QuotaStatusSchema>;

export const FingerprintScopeSchema = z.enum(["global", "source"]);
export type FingerprintScope = z.infer<typeof FingerprintScopeSchema>;

/** Absolute quantity unit for credit/budget windows (optional; percent remains primary). */
export const QuotaValueUnitSchema = z.enum(["usd", "credits", "count"]);
export type QuotaValueUnit = z.infer<typeof QuotaValueUnitSchema>;

export const QuotaWindowSchema = z
  .object({
    id: z.string().min(1).max(64).regex(BILLING_DIMENSION_PATTERN),
    title: z.string().trim().min(1).max(128),
    /** Primary meter input; remaining is always 100 - used_percent in consumers. */
    used_percent: z.number().finite().min(0).max(100),
    resets_at: Rfc3339InstantSchema.optional(),
    duration_seconds: SafeNonnegativeIntegerSchema.optional(),
    /** Absolute remaining when known (for example, a USD balance). */
    remaining_value: z.number().finite().optional(),
    limit_value: z.number().finite().nonnegative().optional(),
    value_unit: QuotaValueUnitSchema.optional(),
  })
  .strict();
export type QuotaWindow = z.infer<typeof QuotaWindowSchema>;

export const QuotaAccountSchema = z
  .object({
    fingerprint: z.string().min(1).max(128).regex(OPAQUE_ID_PATTERN),
    fingerprint_scope: FingerprintScopeSchema,
    label: z.string().trim().min(1).max(128).optional(),
    plan: z.string().trim().min(1).max(64).optional(),
  })
  .strict();
export type QuotaAccount = z.infer<typeof QuotaAccountSchema>;

export const QuotaSnapshotSchema = z
  .object({
    provider: ProviderIdSchema,
    account: QuotaAccountSchema,
    windows: z.array(QuotaWindowSchema).max(MAXIMUM_WINDOWS_PER_SNAPSHOT),
    status: QuotaStatusSchema,
    observed_at: Rfc3339InstantSchema,
  })
  .strict();
export type QuotaSnapshot = z.infer<typeof QuotaSnapshotSchema>;

const LocalQuotaSnapshotSchema = QuotaSnapshotSchema.extend({
  provider: LocalProviderIdSchema,
});

/** The only supported remote quota upload envelope. */
export const QuotaSnapshotEnvelopeSchema = z
  .object({
    protocol_version: z.literal(MANAGED_DATA_PROTOCOL_VERSION),
    device_id: OpaqueIdSchema,
    generation: SafePositiveIntegerSchema,
    sequence: SafeNonnegativeIntegerSchema,
    captured_at: Rfc3339InstantSchema,
    snapshots: z.array(QuotaSnapshotSchema).max(MAXIMUM_SNAPSHOTS_PER_ENVELOPE),
  })
  .strict();
export type QuotaSnapshotEnvelope = z.infer<typeof QuotaSnapshotEnvelopeSchema>;

export const CollectionOutcomeSchema = z.enum([
  "success",
  "auth_required",
  "unavailable",
  "unsupported",
  "error",
]);
export type CollectionOutcome = z.infer<typeof CollectionOutcomeSchema>;

/**
 * One discovered credential source and what reading it produced.
 *
 * `outcome` is the wire spelling, which folds a refusal into `unavailable` because no other
 * device can see or change this one's access. `category` keeps them apart for the reader who
 * can act on the difference.
 */
export const QuotaCollectionSourceSchema = z
  .object({
    source_id: BillingDimensionSchema,
    outcome: CollectionOutcomeSchema,
    category: z.enum([
      "success",
      "auth_required",
      "access_denied",
      "unavailable",
      "unsupported",
      "error",
    ]),
  })
  .strict();
export type QuotaCollectionSource = z.infer<typeof QuotaCollectionSourceSchema>;

/** What every collection result carries; the outcome decides what `snapshots` may hold. */
const QuotaCollectionResultFieldsSchema = z.object({
  provider: LocalProviderIdSchema,
  source: BillingDimensionSchema.optional(),
  message: z.string().trim().min(1).max(512).optional(),
  /**
   * The credential sources discovered for this provider, each named by the rung that
   * answered for it. Empty means the provider was never set up on this device, which is a
   * different thing from collection failing here.
   */
  sources: z.array(QuotaCollectionSourceSchema).max(MAXIMUM_SNAPSHOTS_PER_ENVELOPE),
  /**
   * Set when the failure was this device being refused what it holds — a Keychain entry whose
   * secret is withheld, say.  Signing in again rewrites a secret this device still cannot
   * read, so the reader is sent to check access instead.
   */
  access_denied: z.literal(true).optional(),
});

const QuotaCollectionSuccessResultSchema = QuotaCollectionResultFieldsSchema.extend({
  outcome: z.literal("success"),
  snapshots: z.array(LocalQuotaSnapshotSchema).min(1).max(MAXIMUM_SNAPSHOTS_PER_ENVELOPE),
}).strict();

const QuotaCollectionFailureResultSchema = QuotaCollectionResultFieldsSchema.extend({
  outcome: z.enum(["auth_required", "unavailable", "unsupported", "error"]),
  snapshots: z.array(LocalQuotaSnapshotSchema).max(0),
}).strict();

export const QuotaCollectionResultSchema = z
  .discriminatedUnion("outcome", [
    QuotaCollectionSuccessResultSchema,
    QuotaCollectionFailureResultSchema,
  ])
  .superRefine((result, context) => {
    for (const [index, snapshot] of result.snapshots.entries()) {
      if (snapshot.provider !== result.provider) {
        context.addIssue({
          code: "custom",
          path: ["snapshots", index, "provider"],
          message: "Snapshot provider must match collection result provider.",
        });
      }
    }
  });
export type QuotaCollectionResult = z.infer<typeof QuotaCollectionResultSchema>;

export const QuotaCollectionReportSchema = z
  .object({
    protocol_version: z.literal(LOCAL_COLLECTION_PROTOCOL_VERSION),
    captured_at: Rfc3339InstantSchema,
    results: z.array(QuotaCollectionResultSchema).max(LOCAL_PROVIDER_IDS.length),
  })
  .strict();
export type QuotaCollectionReport = z.infer<typeof QuotaCollectionReportSchema>;

export const PlatformSchema = z.enum(["macos", "linux", "windows"]);
export type Platform = z.infer<typeof PlatformSchema>;

export const AccountSchema = z
  .object({
    account_id: OpaqueIdSchema,
    display_label: z.string().trim().min(1).max(128).nullable(),
    created_at: Rfc3339InstantSchema,
  })
  .strict();
export type Account = z.infer<typeof AccountSchema>;

export const DeviceStatusSchema = z.enum(["active", "offline", "signed_out"]);
export type DeviceStatus = z.infer<typeof DeviceStatusSchema>;

export const DeviceHealthClientProductSchema = z.enum(["quotabar", "quotacli"]);
export type DeviceHealthClientProduct = z.infer<typeof DeviceHealthClientProductSchema>;

export const DeviceHealthOperationSchema = z.enum(["healthy", "degraded", "blocked"]);
export type DeviceHealthOperation = z.infer<typeof DeviceHealthOperationSchema>;

export const DeviceHealthDataStateSchema = z.enum([
  "current",
  "stale",
  "partial",
  "empty",
  "unknown",
]);
export type DeviceHealthDataState = z.infer<typeof DeviceHealthDataStateSchema>;

export const DeviceHealthAttentionSchema = z.enum(["none", "automatic", "optional", "required"]);
export type DeviceHealthAttention = z.infer<typeof DeviceHealthAttentionSchema>;

export const DeviceHealthCodeSchema = z.enum([
  "refresh_failed",
  "quota_collection_failed",
  "usage_scan_partial",
  "usage_upload_failed",
  "account_sync_failed",
  "pricing_refresh_failed",
  "process_interrupted",
  "local_state_invalid",
]);
export type DeviceHealthCode = z.infer<typeof DeviceHealthCodeSchema>;

export const DeviceHealthSummarySchema = z
  .object({
    operation: DeviceHealthOperationSchema,
    data: DeviceHealthDataStateSchema,
    attention: DeviceHealthAttentionSchema,
  })
  .strict();
export type DeviceHealthSummary = z.infer<typeof DeviceHealthSummarySchema>;

const ClientVersionSchema = z
  .string()
  .min(1)
  .max(32)
  .regex(/^[A-Za-z0-9][A-Za-z0-9.+_-]*$/);

export const DeviceHealthUploadRequestSchema = z
  .object({
    protocol_version: z.literal(MANAGED_DATA_PROTOCOL_VERSION),
    schema_version: z.literal(1),
    client_product: DeviceHealthClientProductSchema,
    client_version: ClientVersionSchema,
    platform: PlatformSchema,
    observed_at: Rfc3339InstantSchema,
    refresh_revision: SafeNonnegativeIntegerSchema,
    last_completed_refresh_at: Rfc3339InstantSchema.nullable(),
    last_successful_account_sync_at: Rfc3339InstantSchema.nullable(),
    summary: DeviceHealthSummarySchema,
    top_code: DeviceHealthCodeSchema.nullable(),
    consecutive_failures: SafeNonnegativeIntegerSchema.max(1_000),
    usage_upload_enabled: z.boolean(),
  })
  .strict();
export type DeviceHealthUploadRequest = z.infer<typeof DeviceHealthUploadRequestSchema>;

export const DeviceHealthUploadResponseSchema = z
  .object({
    protocol_version: z.literal(MANAGED_DATA_PROTOCOL_VERSION),
    status: z.enum(["updated", "ignored_stale"]),
    received_at: Rfc3339InstantSchema,
    fresh_until: Rfc3339InstantSchema,
  })
  .strict();
export type DeviceHealthUploadResponse = z.infer<typeof DeviceHealthUploadResponseSchema>;

export const AccountDeviceHealthSchema = DeviceHealthUploadRequestSchema.omit({
  protocol_version: true,
})
  .extend({
    received_at: Rfc3339InstantSchema,
    fresh_until: Rfc3339InstantSchema,
  })
  .superRefine((health, context) => {
    if (Date.parse(health.fresh_until) < Date.parse(health.received_at)) {
      context.addIssue({
        code: "custom",
        path: ["fresh_until"],
        message: "Device Health freshness must not precede server receipt.",
      });
    }
  });
export type AccountDeviceHealth = z.infer<typeof AccountDeviceHealthSchema>;

export const AccountDeviceSchema = z
  .object({
    device_id: OpaqueIdSchema,
    display_name: DisplayNameSchema,
    platform: PlatformSchema,
    device_generation: SafePositiveIntegerSchema,
    status: DeviceStatusSchema,
    created_at: Rfc3339InstantSchema,
    last_login_at: Rfc3339InstantSchema,
    last_seen_at: Rfc3339InstantSchema.nullable(),
    signed_out_at: Rfc3339InstantSchema.nullable(),
  })
  .strict()
  .superRefine((device, context) => {
    if ((device.status === "signed_out") !== (device.signed_out_at !== null)) {
      context.addIssue({
        code: "custom",
        path: ["signed_out_at"],
        message: "signed_out status and signed_out_at must agree.",
      });
    }
  });
export type AccountDevice = z.infer<typeof AccountDeviceSchema>;

export const AccountDeviceWithHealthSchema = AccountDeviceSchema.extend({
  health: AccountDeviceHealthSchema.nullable(),
}).superRefine((device, context) => {
  if (device.health !== null && device.health.platform !== device.platform) {
    context.addIssue({
      code: "custom",
      path: ["health", "platform"],
      message: "Device Health platform must match the Account Device.",
    });
  }
});
export type AccountDeviceWithHealth = z.infer<typeof AccountDeviceWithHealthSchema>;

export const AccountResponseSchema = z
  .object({
    protocol_version: z.literal(PROTOCOL_VERSION),
    account: AccountSchema,
  })
  .strict();
export type AccountResponse = z.infer<typeof AccountResponseSchema>;

export const AccountDevicesResponseSchema = z
  .object({
    protocol_version: z.literal(PROTOCOL_VERSION),
    devices: z.array(AccountDeviceSchema).max(256),
  })
  .strict();
export type AccountDevicesResponse = z.infer<typeof AccountDevicesResponseSchema>;

const NativeClientSchema = z.literal("quotacli");
const InstallationIdSchema = z.string().uuid();

export const IOS_OAUTH_CLIENT_ID = "quota-ios" as const;
export const IOS_OAUTH_REDIRECT_URI = "io.gotry.quota:/oauth/callback" as const;
const IosClientSchema = z.literal(IOS_OAUTH_CLIENT_ID);
const IosRedirectUriSchema = z.literal(IOS_OAUTH_REDIRECT_URI);

export const BrowserLoginExchangeRequestSchema = z
  .object({
    protocol_version: z.literal(PROTOCOL_VERSION),
    grant_type: z.literal("authorization_code"),
    client_id: NativeClientSchema,
    code: SecretSchema,
    code_verifier: z.string().regex(PKCE_VERIFIER_PATTERN),
    redirect_uri: LoopbackRedirectUriSchema,
    installation_id: InstallationIdSchema,
    device_display_name: DisplayNameSchema,
    platform: PlatformSchema,
  })
  .strict();
export type BrowserLoginExchangeRequest = z.infer<typeof BrowserLoginExchangeRequestSchema>;

export const IosLoginExchangeRequestSchema = z
  .object({
    protocol_version: z.literal(PROTOCOL_VERSION),
    grant_type: z.literal("authorization_code"),
    client_id: IosClientSchema,
    code: SecretSchema,
    code_verifier: z.string().regex(PKCE_VERIFIER_PATTERN),
    redirect_uri: IosRedirectUriSchema,
  })
  .strict();
export type IosLoginExchangeRequest = z.infer<typeof IosLoginExchangeRequestSchema>;

export const DeviceAuthorizationRequestSchema = z
  .object({
    protocol_version: z.literal(PROTOCOL_VERSION),
    client_id: NativeClientSchema,
    installation_id: InstallationIdSchema,
    device_display_name: DisplayNameSchema,
    platform: PlatformSchema,
  })
  .strict();
export type DeviceAuthorizationRequest = z.infer<typeof DeviceAuthorizationRequestSchema>;

export const DeviceAuthorizationResponseSchema = z
  .object({
    protocol_version: z.literal(PROTOCOL_VERSION),
    device_code: SecretSchema,
    user_code: z.string().trim().min(1).max(32),
    verification_uri: z.string().url().max(2_048).refine(isHttpsUrl, "Expected an HTTPS URL."),
    verification_uri_complete: z
      .string()
      .url()
      .max(2_048)
      .refine(isHttpsUrl, "Expected an HTTPS URL.")
      .nullable(),
    expires_in: SafePositiveIntegerSchema.max(600),
    interval: SafePositiveIntegerSchema.max(60),
  })
  .strict();
export type DeviceAuthorizationResponse = z.infer<typeof DeviceAuthorizationResponseSchema>;

export const DeviceAuthorizationDecisionRequestSchema = z
  .object({
    protocol_version: z.literal(PROTOCOL_VERSION),
    user_code: z.string().trim().min(1).max(32),
    decision: z.enum(["approve", "deny"]),
  })
  .strict();
export type DeviceAuthorizationDecisionRequest = z.infer<
  typeof DeviceAuthorizationDecisionRequestSchema
>;

const DeviceCodeTokenRequestSchema = z
  .object({
    protocol_version: z.literal(PROTOCOL_VERSION),
    grant_type: z.literal("urn:ietf:params:oauth:grant-type:device_code"),
    client_id: NativeClientSchema,
    device_code: SecretSchema,
  })
  .strict();

export const OAuthTokenRequestSchema = z.discriminatedUnion("grant_type", [
  BrowserLoginExchangeRequestSchema,
  DeviceCodeTokenRequestSchema,
]);
export type OAuthTokenRequest = z.infer<typeof OAuthTokenRequestSchema>;

export const SessionTokenSchema = z
  .object({
    access_token: SecretSchema,
    access_expires_at: Rfc3339InstantSchema,
    refresh_token: SecretSchema,
    refresh_expires_at: Rfc3339InstantSchema,
  })
  .strict();
export type SessionToken = z.infer<typeof SessionTokenSchema>;

export const OAuthTokenResponseSchema = z
  .object({
    protocol_version: z.literal(PROTOCOL_VERSION),
    token_type: z.literal("Bearer"),
    account_id: OpaqueIdSchema,
    device_id: OpaqueIdSchema,
    device_generation: SafePositiveIntegerSchema,
    next_snapshot_sequence: SafeNonnegativeIntegerSchema,
    next_usage_sequence: SafeNonnegativeIntegerSchema,
    usage_deleted_before: Rfc3339InstantSchema.nullable(),
    usage_sync_revision: SafeNonnegativeIntegerSchema,
    account_session: SessionTokenSchema,
    device_session: SessionTokenSchema,
  })
  .strict();
export type OAuthTokenResponse = z.infer<typeof OAuthTokenResponseSchema>;

export const IosOAuthTokenResponseSchema = z
  .object({
    protocol_version: z.literal(PROTOCOL_VERSION),
    token_type: z.literal("Bearer"),
    account_id: OpaqueIdSchema,
    account_session: SessionTokenSchema,
  })
  .strict();
export type IosOAuthTokenResponse = z.infer<typeof IosOAuthTokenResponseSchema>;

export const SessionRefreshRequestSchema = z
  .object({
    protocol_version: z.literal(PROTOCOL_VERSION),
    grant_type: z.literal("refresh_token"),
    client_id: NativeClientSchema,
    token_audience: z.enum(["account", "device"]),
    refresh_token: SecretSchema,
  })
  .strict();
export type SessionRefreshRequest = z.infer<typeof SessionRefreshRequestSchema>;

export const IosSessionRefreshRequestSchema = z
  .object({
    protocol_version: z.literal(PROTOCOL_VERSION),
    grant_type: z.literal("refresh_token"),
    client_id: IosClientSchema,
    token_audience: z.literal("account"),
    refresh_token: SecretSchema,
  })
  .strict();
export type IosSessionRefreshRequest = z.infer<typeof IosSessionRefreshRequestSchema>;

const AccountSessionRefreshResponseSchema = z
  .object({
    protocol_version: z.literal(PROTOCOL_VERSION),
    token_type: z.literal("Bearer"),
    token_audience: z.literal("account"),
    account_id: OpaqueIdSchema,
    account_session: SessionTokenSchema,
  })
  .strict();

const DeviceSessionRefreshResponseSchema = z
  .object({
    protocol_version: z.literal(PROTOCOL_VERSION),
    token_type: z.literal("Bearer"),
    token_audience: z.literal("device"),
    account_id: OpaqueIdSchema,
    device_id: OpaqueIdSchema,
    device_generation: SafePositiveIntegerSchema,
    device_session: SessionTokenSchema,
  })
  .strict();

export const SessionRefreshResponseSchema = z.discriminatedUnion("token_audience", [
  AccountSessionRefreshResponseSchema,
  DeviceSessionRefreshResponseSchema,
]);
export type SessionRefreshResponse = z.infer<typeof SessionRefreshResponseSchema>;

export const DeviceSyncResponseSchema = z
  .object({
    protocol_version: z.literal(PROTOCOL_VERSION),
    account_id: OpaqueIdSchema,
    device_id: OpaqueIdSchema,
    device_generation: SafePositiveIntegerSchema,
    next_snapshot_sequence: SafeNonnegativeIntegerSchema,
    next_usage_sequence: SafeNonnegativeIntegerSchema,
    usage_deleted_before: Rfc3339InstantSchema.nullable(),
    usage_sync_revision: SafeNonnegativeIntegerSchema,
  })
  .strict();
export type DeviceSyncResponse = z.infer<typeof DeviceSyncResponseSchema>;

export const DeviceProfileUpdateRequestSchema = z
  .object({
    protocol_version: z.literal(PROTOCOL_VERSION),
    display_name: DisplayNameSchema,
    platform: PlatformSchema,
  })
  .strict();
export type DeviceProfileUpdateRequest = z.infer<typeof DeviceProfileUpdateRequestSchema>;

export const DeviceProfileUpdateResponseSchema = z
  .object({
    protocol_version: z.literal(PROTOCOL_VERSION),
    status: z.literal("updated"),
    device_id: OpaqueIdSchema,
  })
  .strict();
export type DeviceProfileUpdateResponse = z.infer<typeof DeviceProfileUpdateResponseSchema>;

export const LogoutResponseSchema = z
  .object({
    protocol_version: z.literal(PROTOCOL_VERSION),
    status: z.literal("signed_out"),
  })
  .strict();
export type LogoutResponse = z.infer<typeof LogoutResponseSchema>;

export const DeleteDeviceResponseSchema = z
  .object({
    protocol_version: z.literal(PROTOCOL_VERSION),
    status: z.literal("deleted"),
    device_id: OpaqueIdSchema,
    device_generation: SafePositiveIntegerSchema,
    deleted_before: Rfc3339InstantSchema,
  })
  .strict();
export type DeleteDeviceResponse = z.infer<typeof DeleteDeviceResponseSchema>;

export const BILLING_AGENTS = ["codex", "claude_code", "grok", "opencode", "pi", "cursor"] as const;
export const BillingAgentSchema = z.enum(BILLING_AGENTS);
export type BillingAgent = z.infer<typeof BillingAgentSchema>;

export const InferenceProviderSchema = z.enum([
  "openai",
  "azure_openai",
  "anthropic",
  "aws_bedrock",
  "google_vertex",
  "openrouter",
  "xai",
  "moonshot",
  "deepseek",
  "unknown",
]);
export type InferenceProvider = z.infer<typeof InferenceProviderSchema>;

export const MAXIMUM_MODEL_CATALOG_MODELS = 512;
export const MAXIMUM_MODEL_CATALOG_ALIASES_PER_MODEL = 32;
export const MAXIMUM_MODEL_CATALOG_ALIASES = 4_096;

export const BillingChannelSchema = z.enum([
  "openai_direct",
  "azure_openai",
  "anthropic_direct",
  "aws_bedrock",
  "google_vertex",
  "openrouter",
  "xai_direct",
  "moonshot_direct",
  "deepseek_direct",
  "unknown",
]);

export type BillingChannel = z.infer<typeof BillingChannelSchema>;

const ModelCatalogCanonicalIDSchema = z.string().min(1).max(128).regex(OPAQUE_ID_PATTERN);

export const ModelCatalogAliasSchema = z
  .object({
    reported_model: ModelSchema,
    provider: InferenceProviderSchema,
    agent: BillingAgentSchema.optional(),
    effective_from: UsageDateSchema.optional(),
    effective_to: UsageDateSchema.optional(),
  })
  .strict()
  .superRefine((alias, context) => {
    if (alias.effective_from && alias.effective_to && alias.effective_to <= alias.effective_from) {
      context.addIssue({
        code: "custom",
        path: ["effective_to"],
        message: "effective_to must be later than effective_from.",
      });
    }
  });
export type ModelCatalogAlias = z.infer<typeof ModelCatalogAliasSchema>;

export const ModelCatalogModelSchema = z
  .object({
    canonical_id: ModelCatalogCanonicalIDSchema,
    aliases: z.array(ModelCatalogAliasSchema).min(1).max(MAXIMUM_MODEL_CATALOG_ALIASES_PER_MODEL),
  })
  .strict();
export type ModelCatalogModel = z.infer<typeof ModelCatalogModelSchema>;

export const ModelCatalogSchema = z
  .object({
    schema_version: z.literal(2),
    revision: OpaqueIdSchema,
    models: z.array(ModelCatalogModelSchema).min(1).max(MAXIMUM_MODEL_CATALOG_MODELS),
  })
  .strict();
export type ModelCatalog = z.infer<typeof ModelCatalogSchema>;

/** The checked-in, language-neutral model catalog source used by the Relay default. */
export const MODEL_CATALOG: ModelCatalog = ModelCatalogSchema.parse(modelCatalogDocument);

/** Every channel except the sentinel: an unknown channel has no price to resolve. */
export const PricedBillingChannelSchema = z.enum(
  BillingChannelSchema.options.filter((channel) => channel !== "unknown") as [
    Exclude<BillingChannel, "unknown">,
    ...Exclude<BillingChannel, "unknown">[],
  ],
);
export type PricedBillingChannel = z.infer<typeof PricedBillingChannelSchema>;

export const ChannelSourceSchema = z.enum(["explicit", "agent_default", "unknown"]);
export type ChannelSource = z.infer<typeof ChannelSourceSchema>;

export const ContextBucketSchema = z.enum([
  "le_128k",
  "gt_128k_le_200k",
  "gt_200k_le_256k",
  "gt_256k_le_272k",
  "gt_272k",
]);
export type ContextBucket = z.infer<typeof ContextBucketSchema>;

export const CoverageStatusSchema = z.enum(["complete", "partial"]);
export type CoverageStatus = z.infer<typeof CoverageStatusSchema>;

/**
 * One agent's contiguous UTC-hour window and how completely it was scanned.
 *
 * A submission is bounded so one upload cannot claim an unbounded span; the private local
 * report covers whatever range the app asked for, so it carries the order rule alone.
 */
const coverageFields = {
  agent: BillingAgentSchema,
  start_at: UtcHourSchema,
  end_at: UtcHourSchema,
  status: CoverageStatusSchema,
};

/** A submission is bounded so one upload cannot claim an unbounded span. */
export const UsageCoverageSchema = z
  .object(coverageFields)
  .strict()
  .superRefine(validateCoverageRange);

/** The private local report covers whatever range the app asked for. */
const LocalUsageCoverageSchema = z
  .object(coverageFields)
  .strict()
  .superRefine(validateCoverageOrder);
export type UsageCoverage = z.infer<typeof UsageCoverageSchema>;

const UsageHourlyFactWireSchema = z
  .object({
    bucket_start_utc: UtcHourSchema,
    usage_date: UsageDateSchema,
    usage_hour: z.number().int().min(0).max(23),
    agent: BillingAgentSchema,
    billing_channel: BillingChannelSchema,
    channel_source: ChannelSourceSchema,
    model: ModelSchema,
    context_bucket: ContextBucketSchema,
    service_tier: BillingDimensionSchema,
    speed: BillingDimensionSchema,
    inference_geo: BillingDimensionSchema,
    input_tokens: SafeNonnegativeIntegerSchema,
    cache_read_tokens: SafeNonnegativeIntegerSchema,
    cache_write_5m_tokens: SafeNonnegativeIntegerSchema,
    cache_write_1h_tokens: SafeNonnegativeIntegerSchema,
    cache_write_inferred_tokens: SafeNonnegativeIntegerSchema,
    output_tokens: SafeNonnegativeIntegerSchema,
    reasoning_tokens: SafeNonnegativeIntegerSchema,
    requests: SafePositiveIntegerSchema,
    web_search_requests: SafeNonnegativeIntegerSchema,
    web_fetch_requests: SafeNonnegativeIntegerSchema,
    source_cost_microusd: z.string().max(32).regex(NONNEGATIVE_INTEGER_PATTERN).optional(),
    source_cost_covered_requests: SafeNonnegativeIntegerSchema,
  })
  .strict()
  .superRefine((fact, context) => {
    validateUsageCounts(fact, context);
    if ((fact.billing_channel === "unknown") !== (fact.channel_source === "unknown")) {
      context.addIssue({
        code: "custom",
        path: ["channel_source"],
        message: "Unknown billing channel and channel source must be used together.",
      });
    }
  });
// `model` is provider-owned opaque text. The literal "unknown" is a valid explicit model.
export const UsageHourlyFactSchema = UsageHourlyFactWireSchema;
export type UsageHourlyFact = z.infer<typeof UsageHourlyFactSchema>;

export const UsageSubmissionWriteModeSchema = z.literal("merge_partial");
export type UsageSubmissionWriteMode = z.infer<typeof UsageSubmissionWriteModeSchema>;

export const UsageSubmissionMultipartSchema = z
  .object({
    batch_id: OpaqueIdSchema,
    part_index: SafeNonnegativeIntegerSchema,
    part_count: SafePositiveIntegerSchema.max(MAXIMUM_USAGE_MULTIPART_PARTS),
  })
  .strict()
  .superRefine((part, context) => {
    if (part.part_count < 2) {
      context.addIssue({
        code: "custom",
        path: ["part_count"],
        message: "Multipart submissions must contain at least two parts.",
      });
    }
    if (part.part_index >= part.part_count) {
      context.addIssue({
        code: "custom",
        path: ["part_index"],
        message: "Multipart part index must be less than part count.",
      });
    }
  });
export type UsageSubmissionMultipart = z.infer<typeof UsageSubmissionMultipartSchema>;

export const UsageSubmissionSchema = z
  .object({
    protocol_version: z.literal(MANAGED_DATA_PROTOCOL_VERSION),
    submission_id: OpaqueIdSchema,
    device_id: OpaqueIdSchema,
    generation: SafePositiveIntegerSchema,
    sequence: SafeNonnegativeIntegerSchema,
    parser_revision: OpaqueIdSchema,
    aggregation_timezone: IanaTimezoneSchema,
    coverage: UsageCoverageSchema,
    rows: z.array(UsageHourlyFactWireSchema).max(MAXIMUM_USAGE_ROWS_PER_SUBMISSION),
    write_mode: UsageSubmissionWriteModeSchema.optional(),
    multipart: UsageSubmissionMultipartSchema.optional(),
  })
  .strict()
  .superRefine((submission, context) => {
    const start = Date.parse(submission.coverage.start_at);
    const end = Date.parse(submission.coverage.end_at);
    let localFormatter: Intl.DateTimeFormat | null = null;
    try {
      localFormatter = new Intl.DateTimeFormat("en", {
        timeZone: submission.aggregation_timezone,
        year: "numeric",
        month: "2-digit",
        day: "2-digit",
        hour: "2-digit",
        hourCycle: "h23",
      });
    } catch {
      // IanaTimezoneSchema reports the boundary error.
    }
    const identities = new Set<string>();
    if (submission.write_mode && submission.coverage.status !== "partial") {
      context.addIssue({
        code: "custom",
        path: ["coverage", "status"],
        message: "merge_partial submissions require partial coverage.",
      });
    }
    for (const [index, row] of submission.rows.entries()) {
      if (row.agent !== submission.coverage.agent) {
        context.addIssue({
          code: "custom",
          path: ["rows", index, "agent"],
          message: "Row agent must match coverage agent.",
        });
      }
      const bucket = Date.parse(row.bucket_start_utc);
      if (bucket < start || bucket >= end) {
        context.addIssue({
          code: "custom",
          path: ["rows", index, "bucket_start_utc"],
          message: "Row bucket must fall inside coverage.",
        });
      }
      if (
        localFormatter &&
        !localProjectionMatches(localFormatter, bucket, row.usage_date, row.usage_hour)
      ) {
        context.addIssue({
          code: "custom",
          path: ["rows", index, "usage_date"],
          message: "Row local date/hour must be possible in the aggregation timezone.",
        });
      }
      const identity = usageHourlyFactIdentity(row);
      if (identities.has(identity)) {
        context.addIssue({
          code: "custom",
          path: ["rows", index],
          message: "Hourly fact identities must be unique within a submission.",
        });
      }
      identities.add(identity);
    }
  });
export type UsageSubmission = z.infer<typeof UsageSubmissionSchema>;

export const UsageCostModeSchema = z.enum(["calculate", "auto", "reported"]);
export type UsageCostMode = z.infer<typeof UsageCostModeSchema>;

export const UsageCostBasisSchema = z.enum(["calculated", "reported", "mixed", "none"]);
export type UsageCostBasis = z.infer<typeof UsageCostBasisSchema>;

export const UsageCostStatusSchema = z.enum(["complete", "partial", "unavailable"]);
export type UsageCostStatus = z.infer<typeof UsageCostStatusSchema>;

export const UsageCostAssumptionSchema = z.enum([
  "agent_default_channel",
  "model_alias",
  "wildcard_service_tier",
  "wildcard_speed",
  "wildcard_inference_geo",
  "wildcard_context_bucket",
  "cache_write_inferred_rate",
  "source_reported",
]);
export type UsageCostAssumption = z.infer<typeof UsageCostAssumptionSchema>;

export const UsageUnpricedReasonSchema = z.enum([
  "unknown_channel",
  "unknown_model",
  "outside_effective_range",
  "unsupported_dimensions",
  "ambiguous_price",
  "missing_rate",
  "incomplete_source_cost",
  "invalid_catalog",
]);
export type UsageUnpricedReason = z.infer<typeof UsageUnpricedReasonSchema>;

export const UsageUnpricedItemSchema = z
  .object({
    billing_channel: BillingChannelSchema,
    model: ModelSchema,
    reason: UsageUnpricedReasonSchema,
    rows: SafePositiveIntegerSchema,
  })
  .strict();
export type UsageUnpricedItem = z.infer<typeof UsageUnpricedItemSchema>;

export const UsageCostOutcomeSchema = z
  .object({
    mode: UsageCostModeSchema,
    basis: UsageCostBasisSchema,
    status: UsageCostStatusSchema,
    amount_microusd: z.string().max(32).regex(NONNEGATIVE_INTEGER_PATTERN).nullable(),
    catalog_revision: OpaqueIdSchema.nullable(),
    calculated_rows: SafeNonnegativeIntegerSchema,
    reported_rows: SafeNonnegativeIntegerSchema,
    unpriced_rows: SafeNonnegativeIntegerSchema,
    assumptions: z.array(UsageCostAssumptionSchema).max(16),
    unpriced: z.array(UsageUnpricedItemSchema).max(MAXIMUM_UNPRICED_ITEMS),
    unpriced_truncated: z.literal(true).optional(),
  })
  .strict()
  .superRefine(validateCostOutcome);
export type UsageCostOutcome = z.infer<typeof UsageCostOutcomeSchema>;

export const UsageTokenTotalsSchema = z
  .object({
    input_tokens: SafeNonnegativeIntegerSchema,
    cache_read_tokens: SafeNonnegativeIntegerSchema,
    cache_write_5m_tokens: SafeNonnegativeIntegerSchema,
    cache_write_1h_tokens: SafeNonnegativeIntegerSchema,
    cache_write_inferred_tokens: SafeNonnegativeIntegerSchema,
    output_tokens: SafeNonnegativeIntegerSchema,
    reasoning_tokens: SafeNonnegativeIntegerSchema,
    requests: SafeNonnegativeIntegerSchema,
    web_search_requests: SafeNonnegativeIntegerSchema,
    web_fetch_requests: SafeNonnegativeIntegerSchema,
    source_cost_microusd: z.string().max(32).regex(NONNEGATIVE_INTEGER_PATTERN).nullable(),
    source_cost_covered_requests: SafeNonnegativeIntegerSchema,
  })
  .strict()
  .superRefine(validateUsageCounts);
export type UsageTokenTotals = z.infer<typeof UsageTokenTotalsSchema>;

export const UsageSummaryTotalsSchema = z
  .object({
    total_tokens: SafeNonnegativeIntegerSchema,
    input_tokens: SafeNonnegativeIntegerSchema,
    output_tokens: SafeNonnegativeIntegerSchema,
    cache_read_input_tokens: SafeNonnegativeIntegerSchema,
    cache_write_input_tokens: SafeNonnegativeIntegerSchema,
    reasoning_tokens: SafeNonnegativeIntegerSchema,
    messages: SafeNonnegativeIntegerSchema,
  })
  .strict()
  .superRefine((totals, context) => {
    const totalTokens = totals.input_tokens + totals.output_tokens;
    if (!Number.isSafeInteger(totalTokens) || totals.total_tokens !== totalTokens) {
      context.addIssue({
        code: "custom",
        path: ["total_tokens"],
        message: "total_tokens must equal input_tokens plus output_tokens.",
      });
    }
    const cachedInput = totals.cache_read_input_tokens + totals.cache_write_input_tokens;
    if (!Number.isSafeInteger(cachedInput) || cachedInput > totals.input_tokens) {
      context.addIssue({
        code: "custom",
        path: ["input_tokens"],
        message: "Cache token subsets must not exceed input_tokens.",
      });
    }
    if (totals.reasoning_tokens > totals.output_tokens) {
      context.addIssue({
        code: "custom",
        path: ["reasoning_tokens"],
        message: "reasoning_tokens must not exceed output_tokens.",
      });
    }
  });
export type UsageSummaryTotals = z.infer<typeof UsageSummaryTotalsSchema>;

export const LocalUsageModelSummarySchema = z
  .object({
    model: ModelSchema,
    totals: UsageSummaryTotalsSchema,
    cost: UsageCostOutcomeSchema,
  })
  .strict();
export type LocalUsageModelSummary = z.infer<typeof LocalUsageModelSummarySchema>;

export const LocalUsageProviderSummarySchema = z
  .object({
    provider: InferenceProviderSchema,
    totals: UsageSummaryTotalsSchema,
    cost: UsageCostOutcomeSchema,
    models: z.array(LocalUsageModelSummarySchema).max(MAXIMUM_USAGE_BREAKDOWNS),
  })
  .strict();
export type LocalUsageProviderSummary = z.infer<typeof LocalUsageProviderSummarySchema>;

export const LocalUsageAgentSummarySchema = z
  .object({
    agent: BillingAgentSchema,
    totals: UsageSummaryTotalsSchema,
    cost: UsageCostOutcomeSchema,
    providers: z.array(LocalUsageProviderSummarySchema).max(InferenceProviderSchema.options.length),
  })
  .strict();
export type LocalUsageAgentSummary = z.infer<typeof LocalUsageAgentSummarySchema>;

export const LocalUsagePeriodSummarySchema = z
  .object({
    totals: UsageSummaryTotalsSchema,
    cost: UsageCostOutcomeSchema,
    agents: z.array(LocalUsageAgentSummarySchema).max(BillingAgentSchema.options.length),
    models_truncated: z.literal(true).optional(),
  })
  .strict();
export type LocalUsagePeriodSummary = z.infer<typeof LocalUsagePeriodSummarySchema>;

export const UsageBreakdownDimensionSchema = z.enum([
  "device",
  "agent",
  "model",
  "billing_channel",
  "usage_date",
  "bucket_start_utc",
]);
export type UsageBreakdownDimension = z.infer<typeof UsageBreakdownDimensionSchema>;

const UsageBreakdownOtherDimensionSchema = z.enum([
  "device",
  "agent",
  "billing_channel",
  "usage_date",
  "bucket_start_utc",
]);
const UsageBreakdownFields = {
  totals: UsageTokenTotalsSchema,
  cost: UsageCostOutcomeSchema,
};

export const UsageBreakdownSchema = z.discriminatedUnion("dimension", [
  z
    .object({
      dimension: z.literal("model"),
      key: ModelSchema,
      ...UsageBreakdownFields,
    })
    .strict(),
  z
    .object({
      dimension: UsageBreakdownOtherDimensionSchema,
      key: z.string().min(1).max(128),
      ...UsageBreakdownFields,
    })
    .strict(),
]);
export type UsageBreakdown = z.infer<typeof UsageBreakdownSchema>;

/**
 * How completely a read's range was scanned.
 *
 * Every reader of a managed read has only ever asked whether anything was missed, so the
 * answer travels instead of the windows it was derived from: `none` when no window covers
 * the range at all, `partial` when any window that does was scanned incompletely, `complete`
 * otherwise.
 *
 * The verdict describes the scanning, not the calendar. A stretch of the range no window
 * touches leaves the verdict alone, because a device that was not running has no usage to
 * miss; a scan that was attempted and came up short records a `partial` window, and that is
 * what `partial` reports.
 */
export const UsageCoverageVerdictSchema = z.enum(["none", "complete", "partial"]);
export type UsageCoverageVerdict = z.infer<typeof UsageCoverageVerdictSchema>;

export const UsageDateRangeSchema = z
  .object({
    from: UsageDateSchema,
    to: UsageDateSchema,
  })
  .strict()
  .superRefine((range, context) => {
    const from = Date.parse(`${range.from}T00:00:00Z`);
    const to = Date.parse(`${range.to}T00:00:00Z`);
    if (from > to) {
      context.addIssue({ code: "custom", path: ["to"], message: "to must not precede from." });
    }
  });
export type UsageDateRange = z.infer<typeof UsageDateRangeSchema>;

export const AccountUsageSummarySchema = z
  .object({
    range: UsageDateRangeSchema,
    totals: UsageTokenTotalsSchema,
    cost: UsageCostOutcomeSchema,
    model_catalog_revision: OpaqueIdSchema.optional(),
    coverage: UsageCoverageVerdictSchema,
    breakdowns: z.array(UsageBreakdownSchema).max(MAXIMUM_USAGE_BREAKDOWNS),
    agents: z.array(LocalUsageAgentSummarySchema).max(BillingAgentSchema.options.length).optional(),
    breakdowns_truncated: z.literal(true).optional(),
  })
  .strict();
export type AccountUsageSummary = z.infer<typeof AccountUsageSummarySchema>;

export const LocalUsageReportStatusSchema = z.enum(["complete", "partial", "unavailable"]);
export type LocalUsageReportStatus = z.infer<typeof LocalUsageReportStatusSchema>;

export const LocalUsageReportSchema = z
  .object({
    protocol_version: z.literal(LOCAL_USAGE_PROTOCOL_VERSION),
    generated_at: Rfc3339InstantSchema,
    aggregation_timezone: IanaTimezoneSchema.nullable(),
    range: UsageDateRangeSchema,
    status: LocalUsageReportStatusSchema,
    model_catalog_revision: OpaqueIdSchema.nullable(),
    coverage: z.array(LocalUsageCoverageSchema).max(MAXIMUM_USAGE_COVERAGE_ITEMS),
  })
  .strict()
  .superRefine((report, context) => {
    const unavailable = report.status === "unavailable";
    const validMetadata = unavailable
      ? report.aggregation_timezone === null && report.model_catalog_revision === null
      : report.aggregation_timezone !== null;
    if (!validMetadata) {
      context.addIssue({
        code: "custom",
        path: ["status"],
        message: "Unavailable local Usage must omit timezone and model metadata.",
      });
    }
    if (unavailable && report.coverage.length > 0) {
      context.addIssue({
        code: "custom",
        path: ["coverage"],
        message: "Unavailable local Usage cannot contain coverage.",
      });
    }
    if (!unavailable) {
      const expected = report.coverage.every((item) => item.status === "complete")
        ? "complete"
        : "partial";
      if (report.status !== expected) {
        context.addIssue({
          code: "custom",
          path: ["status"],
          message: "Local Usage status must reflect its coverage.",
        });
      }
    }
  });
export type LocalUsageReport = z.infer<typeof LocalUsageReportSchema>;

export const AccountUsageResponseSchema = z
  .object({
    protocol_version: z.literal(MANAGED_DATA_PROTOCOL_VERSION),
    usage: AccountUsageSummarySchema,
  })
  .strict();
export type AccountUsageResponse = z.infer<typeof AccountUsageResponseSchema>;

export const AccountQuotaObservationSchema = z
  .object({
    device_id: OpaqueIdSchema,
    snapshot: QuotaSnapshotSchema,
  })
  .strict();
export type AccountQuotaObservation = z.infer<typeof AccountQuotaObservationSchema>;

export const AccountQuotaResponseSchema = z
  .object({
    protocol_version: z.literal(MANAGED_DATA_PROTOCOL_VERSION),
    quota: z.array(AccountQuotaObservationSchema).max(8_192),
  })
  .strict();
export type AccountQuotaResponse = z.infer<typeof AccountQuotaResponseSchema>;

export const AccountSummarySchema = z
  .object({
    protocol_version: z.literal(MANAGED_DATA_PROTOCOL_VERSION),
    account: AccountSchema,
    devices: z.array(AccountDeviceWithHealthSchema).max(256),
    quota: z.array(AccountQuotaObservationSchema).max(8_192),
    usage: AccountUsageSummarySchema,
  })
  .strict();
export type AccountSummary = z.infer<typeof AccountSummarySchema>;

export const QuotaSnapshotUploadResponseSchema = z
  .object({
    protocol_version: z.literal(MANAGED_DATA_PROTOCOL_VERSION),
    outcome: z.enum(["accepted", "duplicate"]),
    device_id: OpaqueIdSchema,
    device_generation: SafePositiveIntegerSchema,
    accepted_sequence: SafeNonnegativeIntegerSchema,
    next_snapshot_sequence: SafeNonnegativeIntegerSchema,
  })
  .strict();
export type QuotaSnapshotUploadResponse = z.infer<typeof QuotaSnapshotUploadResponseSchema>;

export const UsageUploadOutcomeSchema = z.enum([
  "accepted",
  "duplicate",
  "rejected",
  "partial",
  "sequence_conflict",
  "stale_generation",
  "deleted",
]);
export type UsageUploadOutcome = z.infer<typeof UsageUploadOutcomeSchema>;

export const UsageUploadRejectionReasonSchema = z.literal("duplicate_fact_identity");
export type UsageUploadRejectionReason = z.infer<typeof UsageUploadRejectionReasonSchema>;

export const UsageUploadResponseSchema = z
  .object({
    protocol_version: z.literal(MANAGED_DATA_PROTOCOL_VERSION),
    outcome: UsageUploadOutcomeSchema,
    device_id: OpaqueIdSchema,
    device_generation: SafePositiveIntegerSchema,
    accepted_sequence: SafeNonnegativeIntegerSchema.nullable(),
    next_sequence: SafeNonnegativeIntegerSchema,
    usage_sync_revision: SafeNonnegativeIntegerSchema,
    deleted_before: Rfc3339InstantSchema.nullable(),
    rejection_reason: UsageUploadRejectionReasonSchema.optional(),
  })
  .strict()
  .superRefine((response, context) => {
    const accepted = response.outcome === "accepted" || response.outcome === "duplicate";
    if (accepted !== (response.accepted_sequence !== null)) {
      context.addIssue({
        code: "custom",
        path: ["accepted_sequence"],
        message: "accepted_sequence is present only for accepted or duplicate uploads.",
      });
    }
    if ((response.outcome === "deleted") !== (response.deleted_before !== null)) {
      context.addIssue({
        code: "custom",
        path: ["deleted_before"],
        message: "deleted_before is present only for a deleted device.",
      });
    }
    if ((response.outcome === "rejected") !== (response.rejection_reason !== undefined)) {
      context.addIssue({
        code: "custom",
        path: ["rejection_reason"],
        message: "rejection_reason is present only for rejected uploads.",
      });
    }
  });
export type UsageUploadResponse = z.infer<typeof UsageUploadResponseSchema>;

export const DecimalAmountSchema = z.string().min(1).max(32).regex(DECIMAL_PATTERN);
export type DecimalAmount = z.infer<typeof DecimalAmountSchema>;

export const PricingRatesSchema = z
  .object({
    uncached_input_per_million: DecimalAmountSchema.nullable(),
    cache_read_per_million: DecimalAmountSchema.nullable(),
    cache_write_5m_per_million: DecimalAmountSchema.nullable(),
    cache_write_1h_per_million: DecimalAmountSchema.nullable(),
    cache_write_inferred_per_million: DecimalAmountSchema.nullable(),
    output_per_million: DecimalAmountSchema.nullable(),
    web_search_per_request: DecimalAmountSchema.nullable(),
    web_fetch_per_request: DecimalAmountSchema.nullable(),
  })
  .strict()
  .refine((rates) => Object.values(rates).some((rate) => rate !== null), {
    message: "A pricing entry must define at least one rate.",
  });
export type PricingRates = z.infer<typeof PricingRatesSchema>;

export const PricingDimensionSchema = z.union([BillingDimensionSchema, z.literal("*")]);
export type PricingDimension = z.infer<typeof PricingDimensionSchema>;

export const PricingContextBucketSchema = z.union([ContextBucketSchema, z.literal("*")]);
export type PricingContextBucket = z.infer<typeof PricingContextBucketSchema>;

export const PricingCatalogEntrySchema = z
  .object({
    entry_id: OpaqueIdSchema,
    billing_channel: PricedBillingChannelSchema,
    model: ModelSchema,
    aliases: z.array(ModelSchema).max(16),
    effective_from: UsageDateSchema,
    effective_to: UsageDateSchema.nullable(),
    service_tier: PricingDimensionSchema,
    speed: PricingDimensionSchema,
    inference_geo: PricingDimensionSchema,
    context_bucket: PricingContextBucketSchema,
    currency: z.literal("USD"),
    rates: PricingRatesSchema,
    source_url: z.string().url().max(2_048).refine(isHttpsUrl, "Expected an HTTPS URL."),
    verified_at: Rfc3339InstantSchema,
  })
  .strict()
  .superRefine((entry, context) => {
    if (entry.effective_to !== null && entry.effective_to <= entry.effective_from) {
      context.addIssue({
        code: "custom",
        path: ["effective_to"],
        message: "effective_to must be later than effective_from.",
      });
    }
    const names = [entry.model, ...entry.aliases];
    if (new Set(names).size !== names.length) {
      context.addIssue({
        code: "custom",
        path: ["aliases"],
        message: "Model and aliases must be unique within an entry.",
      });
    }
  });
export type PricingCatalogEntry = z.infer<typeof PricingCatalogEntrySchema>;

/** Structure only; quota-model performs catalog-wide ambiguity validation. */
export const PricingCatalogSchema = z
  .object({
    protocol_version: z.literal(PROTOCOL_VERSION),
    revision: OpaqueIdSchema,
    published_at: Rfc3339InstantSchema,
    entries: z.array(PricingCatalogEntrySchema).max(MAXIMUM_PRICING_ENTRIES),
  })
  .strict();
export type PricingCatalog = z.infer<typeof PricingCatalogSchema>;

export const RelayErrorCodeSchema = z.enum([
  "invalid_request",
  "unauthorized",
  "forbidden",
  "not_found",
  "authorization_pending",
  "slow_down",
  "access_denied",
  "expired_token",
  "invalid_grant",
  "rate_limited",
  "sequence_conflict",
  "stale_generation",
  "device_deleted",
  "client_upgrade_required",
  "conflict",
  "internal_error",
]);
export type RelayErrorCode = z.infer<typeof RelayErrorCodeSchema>;

export const RelayErrorEnvelopeSchema = z
  .object({
    error: z
      .object({
        code: RelayErrorCodeSchema,
        message: z.string().trim().min(1).max(512),
      })
      .strict(),
  })
  .strict();
export type RelayErrorEnvelope = z.infer<typeof RelayErrorEnvelopeSchema>;

function isCalendarDate(value: string): boolean {
  const instant = new Date(`${value}T00:00:00Z`);
  return !Number.isNaN(instant.getTime()) && instant.toISOString().slice(0, 10) === value;
}

function isCanonicalUtcHour(value: string): boolean {
  const instant = Date.parse(value);
  return (
    Number.isFinite(instant) && new Date(instant).toISOString().replace(".000Z", "Z") === value
  );
}

function isIanaTimezone(value: string): boolean {
  try {
    new Intl.DateTimeFormat("en", { timeZone: value }).format(0);
    return true;
  } catch {
    return false;
  }
}

function isHttpsUrl(value: string): boolean {
  try {
    return new URL(value).protocol === "https:";
  } catch {
    return false;
  }
}

function isLoopbackRedirectUri(value: string): boolean {
  try {
    const url = new URL(value);
    return (
      url.protocol === "http:" &&
      (url.hostname === "127.0.0.1" || url.hostname === "[::1]" || url.hostname === "::1") &&
      url.port !== "" &&
      url.username === "" &&
      url.password === "" &&
      url.search === "" &&
      url.hash === ""
    );
  } catch {
    return false;
  }
}

function localProjectionMatches(
  formatter: Intl.DateTimeFormat,
  bucketStart: number,
  usageDate: string,
  usageHour: number,
): boolean {
  return [bucketStart, bucketStart + 3_600_000 - 1].some((instant) => {
    const parts = Object.fromEntries(
      formatter
        .formatToParts(instant)
        .filter((part) => part.type !== "literal")
        .map((part) => [part.type, part.value]),
    );
    return (
      `${parts.year}-${parts.month}-${parts.day}` === usageDate && Number(parts.hour) === usageHour
    );
  });
}

function usageHourlyFactIdentity(fact: z.infer<typeof UsageHourlyFactSchema>): string {
  return JSON.stringify([
    fact.bucket_start_utc,
    fact.usage_date,
    fact.usage_hour,
    fact.agent,
    fact.billing_channel,
    fact.channel_source,
    fact.model,
    fact.context_bucket,
    fact.service_tier,
    fact.speed,
    fact.inference_geo,
  ]);
}

function validateCoverageRange(
  coverage: { start_at: string; end_at: string },
  context: z.RefinementCtx,
): void {
  validateCoverageOrder(coverage, context);
  const start = Date.parse(coverage.start_at);
  const end = Date.parse(coverage.end_at);
  if (start < Date.parse(EARLIEST_USAGE_INSTANT)) {
    context.addIssue({
      code: "custom",
      path: ["start_at"],
      message: `Coverage may not begin before ${EARLIEST_USAGE_INSTANT}.`,
    });
  }
  if (end <= start) return;
  if ((end - start) / 3_600_000 > MAXIMUM_USAGE_COVERAGE_HOURS) {
    context.addIssue({
      code: "custom",
      path: ["end_at"],
      message: `Coverage may span at most ${MAXIMUM_USAGE_COVERAGE_HOURS} hours.`,
    });
  }
}

function validateCoverageOrder(
  coverage: { start_at: string; end_at: string },
  context: z.RefinementCtx,
): void {
  if (Date.parse(coverage.end_at) <= Date.parse(coverage.start_at)) {
    context.addIssue({
      code: "custom",
      path: ["end_at"],
      message: "Coverage end_at must be later than start_at.",
    });
  }
}

function validateUsageCounts(
  value: {
    input_tokens: number;
    cache_read_tokens: number;
    cache_write_5m_tokens: number;
    cache_write_1h_tokens: number;
    cache_write_inferred_tokens: number;
    output_tokens: number;
    reasoning_tokens: number;
    requests: number;
    web_search_requests: number;
    web_fetch_requests: number;
    source_cost_microusd?: string | null | undefined;
    source_cost_covered_requests: number;
  },
  context: z.RefinementCtx,
): void {
  const classifiedInput =
    value.cache_read_tokens +
    value.cache_write_5m_tokens +
    value.cache_write_1h_tokens +
    value.cache_write_inferred_tokens;
  if (!Number.isSafeInteger(classifiedInput) || classifiedInput > value.input_tokens) {
    context.addIssue({
      code: "custom",
      path: ["input_tokens"],
      message: "Cache token subsets must not exceed input_tokens.",
    });
  }
  if (value.reasoning_tokens > value.output_tokens) {
    context.addIssue({
      code: "custom",
      path: ["reasoning_tokens"],
      message: "reasoning_tokens must not exceed output_tokens.",
    });
  }
  if (value.source_cost_covered_requests > value.requests) {
    context.addIssue({
      code: "custom",
      path: ["source_cost_covered_requests"],
      message: "Source cost coverage must not exceed requests.",
    });
  }
  if (value.requests === 0 && (value.web_search_requests > 0 || value.web_fetch_requests > 0)) {
    context.addIssue({
      code: "custom",
      path: ["requests"],
      message: "Billable tool requests require at least one request.",
    });
  }
  const hasSourceCost =
    value.source_cost_microusd !== undefined && value.source_cost_microusd !== null;
  if (hasSourceCost !== value.source_cost_covered_requests > 0) {
    context.addIssue({
      code: "custom",
      path: ["source_cost_microusd"],
      message: "Source cost is present exactly when it covers at least one request.",
    });
  }
}

function validateCostOutcome(
  outcome: z.infer<typeof UsageCostOutcomeSchema>,
  context: z.RefinementCtx,
) {
  const pricedRows = outcome.calculated_rows + outcome.reported_rows;
  if (!Number.isSafeInteger(pricedRows)) {
    context.addIssue({ code: "custom", path: ["calculated_rows"], message: "Row count overflow." });
  }
  const expectedBasis =
    outcome.calculated_rows > 0 && outcome.reported_rows > 0
      ? "mixed"
      : outcome.calculated_rows > 0
        ? "calculated"
        : outcome.reported_rows > 0
          ? "reported"
          : "none";
  if (outcome.basis !== expectedBasis) {
    context.addIssue({
      code: "custom",
      path: ["basis"],
      message: "Cost basis must match calculated and reported row counts.",
    });
  }
  const expectedStatus =
    outcome.unpriced_rows === 0 ? "complete" : pricedRows > 0 ? "partial" : "unavailable";
  if (outcome.status !== expectedStatus) {
    context.addIssue({
      code: "custom",
      path: ["status"],
      message: "Cost status must match priced and unpriced row counts.",
    });
  }
  if (pricedRows > 0 !== (outcome.amount_microusd !== null)) {
    context.addIssue({
      code: "custom",
      path: ["amount_microusd"],
      message: "Cost amount is present exactly when at least one row is priced.",
    });
  }
  const detailedUnpricedRows = outcome.unpriced.reduce((sum, item) => sum + item.rows, 0);
  if (
    outcome.unpriced_truncated
      ? detailedUnpricedRows > outcome.unpriced_rows
      : detailedUnpricedRows !== outcome.unpriced_rows
  ) {
    context.addIssue({
      code: "custom",
      path: ["unpriced"],
      message: "Unpriced item counts must sum to unpriced_rows.",
    });
  }
  if (new Set(outcome.assumptions).size !== outcome.assumptions.length) {
    context.addIssue({
      code: "custom",
      path: ["assumptions"],
      message: "Cost assumptions must be unique.",
    });
  }
}
