import { z } from "zod";
import modelCatalogDocument from "../catalog/model-catalog.json" with { type: "json" };
// Generated by `pnpm generate:provider-catalog` from packages/provider/catalog.json.
import {
  LOCAL_PROVIDER_IDS,
  type LocalProviderId,
  LocalProviderIdSchema,
  PROVIDER_DISPLAY_NAMES,
  PROVIDER_IDS,
  type ProviderId,
  ProviderIdSchema,
  providerDisplayName,
} from "./provider-ids.generated.ts";

export {
  LOCAL_PROVIDER_IDS,
  type LocalProviderId,
  LocalProviderIdSchema,
  PROVIDER_DISPLAY_NAMES,
  PROVIDER_IDS,
  type ProviderId,
  ProviderIdSchema,
  providerDisplayName,
};

/**
 * Each contract carries its own version, because each evolves on its own terms. Sharing a
 * number couples two contracts that have nothing to say to each other: bumping one would
 * force the other to move with it.
 *
 * The private local reports name no version of their own. They only ever travel nested inside an
 * IPC state that carries `ipc_version`, and both ends of that pipe ship in the same build.
 */
/** OAuth, Device authorization and control, Account metadata, and the catalogs. */
export const PROTOCOL_VERSION = 2 as const;
/** Quota, Usage, and Account summary between a Device and Relay. */
export const MANAGED_DATA_PROTOCOL_VERSION = 6 as const;
export const MAXIMUM_SNAPSHOTS_PER_ENVELOPE = 32;
export const MAXIMUM_WINDOWS_PER_SNAPSHOT = 16;
/**
 * A Usage upload replaces whole hours, so what bounds it is hours and rows inside an hour
 * rather than a span and a row total. A scan that finds more distinct rows in one hour than
 * this folds the overflow into the `other` model before uploading; Relay refuses more.
 */
export const MAXIMUM_USAGE_HOURS_PER_UPLOAD = 256;
export const MAXIMUM_USAGE_ROWS_PER_HOUR = 512;
export const MAXIMUM_USAGE_SUBMISSION_BYTES = 1_048_576;
/**
 * No agent this Account accepts existed before this instant, so an hour reaching back past it
 * was computed from a missing lower bound rather than scanned.
 */
export const EARLIEST_USAGE_INSTANT = "2020-01-01T00:00:00Z";
/** One activity read answers at most this many days. */
export const MAXIMUM_USAGE_ACTIVITY_DAYS = 400;
/** One period's agent tree carries at most this many model leaves. */
export const MAXIMUM_USAGE_PERIOD_LEAVES = 200;
/** The model that every leaf past {@link MAXIMUM_USAGE_PERIOD_LEAVES} folds into. */
export const USAGE_OTHER_MODEL = "other";
export const MAXIMUM_USAGE_BREAKDOWNS = 1_000;
export const MAXIMUM_USAGE_COVERAGE_ITEMS = 2_048;
export const MAXIMUM_UNPRICED_ITEMS = 100;
export const MAXIMUM_PRICING_ENTRIES = 4_096;

const MAXIMUM_SAFE_INTEGER = Number.MAX_SAFE_INTEGER;
const OPAQUE_ID_PATTERN = /^[A-Za-z0-9][A-Za-z0-9._:-]*$/;
const BILLING_DIMENSION_PATTERN = /^[A-Za-z0-9][A-Za-z0-9._:+-]*$/;
// Models are provider-owned opaque text. Keep only the trust-boundary guard;
// punctuation, casing, whitespace, and Unicode are all valid model names.
const MODEL_PATTERN = /^(?=[\s\S]{1,128}$)(?![\s\S]*\p{Cc})[\s\S]+$/u;
const UTC_HOUR_PATTERN = /^\d{4}-\d{2}-\d{2}T\d{2}:00:00Z$/;
const DATE_PATTERN = /^\d{4}-\d{2}-\d{2}$/;
const NONNEGATIVE_INTEGER_PATTERN = /^(?:0|[1-9]\d*)$/;
const DECIMAL_PATTERN = /^(?:0|[1-9]\d*)(?:\.\d{1,12})?$/;
const PKCE_VERIFIER_PATTERN = /^[A-Za-z0-9._~-]{43,128}$/;
// A wire enum member, as a reader takes it: lowercase snake_case, bounded, membership unchecked.
const WIRE_ENUM_PATTERN = /^[a-z][a-z0-9_]*$/;

const SafeNonnegativeIntegerSchema = z.number().int().min(0).max(MAXIMUM_SAFE_INTEGER);
const SafePositiveIntegerSchema = SafeNonnegativeIntegerSchema.min(1);
const OpaqueIdSchema = z.string().min(1).max(128).regex(OPAQUE_ID_PATTERN);
const SecretSchema = z.string().min(16).max(2_048);
const DisplayNameSchema = z.string().trim().min(1).max(128);
const BillingDimensionSchema = z.string().min(1).max(64).regex(BILLING_DIMENSION_PATTERN);
const ModelSchema = z.string().min(1).regex(MODEL_PATTERN);
const LoopbackRedirectUriSchema = z
  .string()
  .url()
  .max(2_048)
  .refine(isLoopbackRedirectUri, "Expected a loopback HTTP redirect URI.");

export const Rfc3339InstantSchema = z.string().max(64).datetime({ offset: true });
export type Rfc3339Instant = z.infer<typeof Rfc3339InstantSchema>;

export const UtcHourSchema = z
  .string()
  .regex(UTC_HOUR_PATTERN)
  .refine(isCanonicalUtcHour, "Expected a valid UTC hour boundary.");
export type UtcHour = z.infer<typeof UtcHourSchema>;

export const UsageDateSchema = z
  .string()
  .regex(DATE_PATTERN)
  .refine(isCalendarDate, "Expected a valid calendar date.");
export type UsageDate = z.infer<typeof UsageDateSchema>;

export const IanaTimezoneSchema = z
  .string()
  .min(1)
  .max(64)
  .regex(/^[A-Za-z0-9._+-]+(?:\/[A-Za-z0-9._+-]+)*$/)
  .refine(isIanaTimezone, "Expected an IANA timezone.");
export type IanaTimezone = z.infer<typeof IanaTimezoneSchema>;

export const QuotaStatusSchema = z.enum([
  "available",
  "stale",
  "auth_required",
  "unavailable",
  "unsupported",
  "error",
]);
export type QuotaStatus = z.infer<typeof QuotaStatusSchema>;

export const FingerprintScopeSchema = z.enum(["global", "source"]);
export type FingerprintScope = z.infer<typeof FingerprintScopeSchema>;

/** Absolute quantity unit for credit/budget windows (optional; percent remains primary). */
export const QuotaValueUnitSchema = z.enum(["usd", "credits", "count"]);
export type QuotaValueUnit = z.infer<typeof QuotaValueUnitSchema>;

export const QuotaWindowSchema = z
  .object({
    id: z.string().min(1).max(64).regex(BILLING_DIMENSION_PATTERN),
    title: z.string().trim().min(1).max(128),
    /** Primary meter input; remaining is always 100 - used_percent in consumers. */
    used_percent: z.number().finite().min(0).max(100),
    resets_at: Rfc3339InstantSchema.optional(),
    duration_seconds: SafeNonnegativeIntegerSchema.optional(),
    /** Absolute remaining when known (for example, a USD balance). */
    remaining_value: z.number().finite().optional(),
    limit_value: z.number().finite().nonnegative().optional(),
    value_unit: QuotaValueUnitSchema.optional(),
  })
  .strict();
export type QuotaWindow = z.infer<typeof QuotaWindowSchema>;

export const QuotaAccountSchema = z
  .object({
    fingerprint: z.string().min(1).max(128).regex(OPAQUE_ID_PATTERN),
    fingerprint_scope: FingerprintScopeSchema,
    label: z.string().trim().min(1).max(128).optional(),
    plan: z.string().trim().min(1).max(64).optional(),
  })
  .strict();
export type QuotaAccount = z.infer<typeof QuotaAccountSchema>;

export const QuotaSnapshotSchema = z
  .object({
    provider: ProviderIdSchema,
    account: QuotaAccountSchema,
    windows: z.array(QuotaWindowSchema).max(MAXIMUM_WINDOWS_PER_SNAPSHOT),
    status: QuotaStatusSchema,
    observed_at: Rfc3339InstantSchema,
  })
  .strict();
export type QuotaSnapshot = z.infer<typeof QuotaSnapshotSchema>;

const LocalQuotaSnapshotSchema = QuotaSnapshotSchema.extend({
  provider: LocalProviderIdSchema,
});

/**
 * The only supported remote quota upload envelope.
 *
 * The device token names the device and its generation, so the body restates neither an id a
 * caller could get wrong nor a sequence Relay would have to keep for it: a reading is placed
 * by `(provider, fingerprint)` and ordered by the instant it was observed.
 */
export const QuotaSnapshotEnvelopeSchema = z
  .object({
    protocol_version: z.literal(MANAGED_DATA_PROTOCOL_VERSION),
    generation: SafePositiveIntegerSchema,
    snapshots: z.array(QuotaSnapshotSchema).max(MAXIMUM_SNAPSHOTS_PER_ENVELOPE),
  })
  .strict();
export type QuotaSnapshotEnvelope = z.infer<typeof QuotaSnapshotEnvelopeSchema>;

export const CollectionOutcomeSchema = z.enum([
  "success",
  "auth_required",
  "unavailable",
  "unsupported",
  "error",
]);
export type CollectionOutcome = z.infer<typeof CollectionOutcomeSchema>;

/**
 * One discovered credential source and what reading it produced.
 *
 * `outcome` is the wire spelling, which folds a refusal into `unavailable` because no other
 * device can see or change this one's access. `category` keeps them apart for the reader who
 * can act on the difference.
 */
export const QuotaCollectionSourceSchema = z
  .object({
    source_id: BillingDimensionSchema,
    outcome: CollectionOutcomeSchema,
    category: z.enum([
      "success",
      "auth_required",
      "access_denied",
      "unavailable",
      "unsupported",
      "error",
    ]),
  })
  .strict();
export type QuotaCollectionSource = z.infer<typeof QuotaCollectionSourceSchema>;

/** What every collection result carries; the outcome decides what `snapshots` may hold. */
const QuotaCollectionResultFieldsSchema = z.object({
  provider: LocalProviderIdSchema,
  source: BillingDimensionSchema.optional(),
  message: z.string().trim().min(1).max(512).optional(),
  /**
   * The credential sources discovered for this provider, each named by the rung that
   * answered for it. Empty means the provider was never set up on this device, which is a
   * different thing from collection failing here.
   */
  sources: z.array(QuotaCollectionSourceSchema).max(MAXIMUM_SNAPSHOTS_PER_ENVELOPE),
  /**
   * Set when the failure was this device being refused what it holds — a Keychain entry whose
   * secret is withheld, say.  Signing in again rewrites a secret this device still cannot
   * read, so the reader is sent to check access instead.
   */
  access_denied: z.literal(true).optional(),
});

const QuotaCollectionSuccessResultSchema = QuotaCollectionResultFieldsSchema.extend({
  outcome: z.literal("success"),
  snapshots: z.array(LocalQuotaSnapshotSchema).min(1).max(MAXIMUM_SNAPSHOTS_PER_ENVELOPE),
}).strict();

const QuotaCollectionFailureResultSchema = QuotaCollectionResultFieldsSchema.extend({
  outcome: z.enum(["auth_required", "unavailable", "unsupported", "error"]),
  snapshots: z.array(LocalQuotaSnapshotSchema).max(0),
}).strict();

export const QuotaCollectionResultSchema = z
  .discriminatedUnion("outcome", [
    QuotaCollectionSuccessResultSchema,
    QuotaCollectionFailureResultSchema,
  ])
  .superRefine((result, context) => {
    for (const [index, snapshot] of result.snapshots.entries()) {
      if (snapshot.provider !== result.provider) {
        context.addIssue({
          code: "custom",
          path: ["snapshots", index, "provider"],
          message: "Snapshot provider must match collection result provider.",
        });
      }
    }
  });
export type QuotaCollectionResult = z.infer<typeof QuotaCollectionResultSchema>;

export const QuotaCollectionReportSchema = z
  .object({
    captured_at: Rfc3339InstantSchema,
    results: z.array(QuotaCollectionResultSchema).max(LOCAL_PROVIDER_IDS.length),
  })
  .strict();
export type QuotaCollectionReport = z.infer<typeof QuotaCollectionReportSchema>;

/**
 * What a Device runs.
 *
 * QuotaBar is the only client that registers a Device, so macOS is the only platform one can
 * report. The registered `quota-ios` client is a viewer and owns no Device
 * ([ADR 0013](../../docs/decisions/0013-readonly-ios-account-client.md)).
 */
export const PlatformSchema = z.enum(["macos"]);
export type Platform = z.infer<typeof PlatformSchema>;

/** A platform this build has never heard of is named as what it is, not as a raw enum member. */
export function platformDisplayName(platform: string): string {
  return platform === "macos" ? "macOS" : "Unknown";
}

export const AccountSchema = z
  .object({
    account_id: OpaqueIdSchema,
    display_label: z.string().trim().min(1).max(128).nullable(),
    created_at: Rfc3339InstantSchema,
  })
  .strict();
export type Account = z.infer<typeof AccountSchema>;

/**
 * A device as an Account reads it: the two instants Relay witnessed.
 *
 * `last_seen_at` is when the device last called; `last_observed_at` is when the newest reading
 * it sent was taken. How recently a device spoke is derived from those by whoever reads them,
 * so nothing here is a status one device asserted about another.
 */
export const AccountDeviceSchema = z
  .object({
    id: OpaqueIdSchema,
    display_name: DisplayNameSchema,
    platform: PlatformSchema,
    last_seen_at: Rfc3339InstantSchema.nullable(),
    last_observed_at: Rfc3339InstantSchema.nullable(),
  })
  .strict();
export type AccountDevice = z.infer<typeof AccountDeviceSchema>;

export const AccountResponseSchema = z
  .object({
    protocol_version: z.literal(PROTOCOL_VERSION),
    account: AccountSchema,
  })
  .strict();
export type AccountResponse = z.infer<typeof AccountResponseSchema>;

const NativeClientSchema = z.literal("quotabar");
const InstallationIdSchema = z.string().uuid();

export const IOS_OAUTH_CLIENT_ID = "quota-ios" as const;
export const IOS_OAUTH_REDIRECT_URI = "io.gotry.quota:/oauth/callback" as const;
const IosClientSchema = z.literal(IOS_OAUTH_CLIENT_ID);
const IosRedirectUriSchema = z.literal(IOS_OAUTH_REDIRECT_URI);

export const BrowserLoginExchangeRequestSchema = z
  .object({
    protocol_version: z.literal(PROTOCOL_VERSION),
    grant_type: z.literal("authorization_code"),
    client_id: NativeClientSchema,
    code: SecretSchema,
    code_verifier: z.string().regex(PKCE_VERIFIER_PATTERN),
    redirect_uri: LoopbackRedirectUriSchema,
    installation_id: InstallationIdSchema,
    device_display_name: DisplayNameSchema,
    platform: PlatformSchema,
  })
  .strict();
export type BrowserLoginExchangeRequest = z.infer<typeof BrowserLoginExchangeRequestSchema>;

export const IosLoginExchangeRequestSchema = z
  .object({
    protocol_version: z.literal(PROTOCOL_VERSION),
    grant_type: z.literal("authorization_code"),
    client_id: IosClientSchema,
    code: SecretSchema,
    code_verifier: z.string().regex(PKCE_VERIFIER_PATTERN),
    redirect_uri: IosRedirectUriSchema,
  })
  .strict();
export type IosLoginExchangeRequest = z.infer<typeof IosLoginExchangeRequestSchema>;

export const SessionTokenSchema = z
  .object({
    access_token: SecretSchema,
    access_expires_at: Rfc3339InstantSchema,
    refresh_token: SecretSchema,
    refresh_expires_at: Rfc3339InstantSchema,
  })
  .strict();
export type SessionToken = z.infer<typeof SessionTokenSchema>;

/**
 * What QuotaBar holds after signing in: one session, and the Device it may write.
 *
 * A login used to issue two token families — one to read the Account, one to write the Device —
 * and every rule about a session was then written twice. One family carries both scopes, so a
 * client holds one access token, rotates one refresh token, and revoking it revokes everything
 * that login granted ([ADR 0027](../../docs/decisions/0027-one-token-per-client.md)).
 */
export const OAuthTokenResponseSchema = z
  .object({
    protocol_version: z.literal(PROTOCOL_VERSION),
    token_type: z.literal("Bearer"),
    account_id: OpaqueIdSchema,
    device_id: OpaqueIdSchema,
    device_generation: SafePositiveIntegerSchema,
    usage_deleted_before: Rfc3339InstantSchema.nullable(),
    usage_sync_revision: SafeNonnegativeIntegerSchema,
    session: SessionTokenSchema,
  })
  .strict();
export type OAuthTokenResponse = z.infer<typeof OAuthTokenResponseSchema>;

/** The read-only viewer's session. It names no Device, because it registers none. */
export const IosOAuthTokenResponseSchema = z
  .object({
    protocol_version: z.literal(PROTOCOL_VERSION),
    token_type: z.literal("Bearer"),
    account_id: OpaqueIdSchema,
    session: SessionTokenSchema,
  })
  .strict();
export type IosOAuthTokenResponse = z.infer<typeof IosOAuthTokenResponseSchema>;

export const SessionRefreshRequestSchema = z
  .object({
    protocol_version: z.literal(PROTOCOL_VERSION),
    grant_type: z.literal("refresh_token"),
    client_id: NativeClientSchema,
    refresh_token: SecretSchema,
  })
  .strict();
export type SessionRefreshRequest = z.infer<typeof SessionRefreshRequestSchema>;

export const IosSessionRefreshRequestSchema = z
  .object({
    protocol_version: z.literal(PROTOCOL_VERSION),
    grant_type: z.literal("refresh_token"),
    client_id: IosClientSchema,
    refresh_token: SecretSchema,
  })
  .strict();
export type IosSessionRefreshRequest = z.infer<typeof IosSessionRefreshRequestSchema>;

export const SessionRefreshResponseSchema = z
  .object({
    protocol_version: z.literal(PROTOCOL_VERSION),
    token_type: z.literal("Bearer"),
    account_id: OpaqueIdSchema,
    device_id: OpaqueIdSchema,
    device_generation: SafePositiveIntegerSchema,
    session: SessionTokenSchema,
  })
  .strict();
export type SessionRefreshResponse = z.infer<typeof SessionRefreshResponseSchema>;

export const IosSessionRefreshResponseSchema = z
  .object({
    protocol_version: z.literal(PROTOCOL_VERSION),
    token_type: z.literal("Bearer"),
    account_id: OpaqueIdSchema,
    session: SessionTokenSchema,
  })
  .strict();
export type IosSessionRefreshResponse = z.infer<typeof IosSessionRefreshResponseSchema>;

export const DeviceSyncResponseSchema = z
  .object({
    protocol_version: z.literal(PROTOCOL_VERSION),
    account_id: OpaqueIdSchema,
    device_id: OpaqueIdSchema,
    device_generation: SafePositiveIntegerSchema,
    usage_deleted_before: Rfc3339InstantSchema.nullable(),
    usage_sync_revision: SafeNonnegativeIntegerSchema,
  })
  .strict();
export type DeviceSyncResponse = z.infer<typeof DeviceSyncResponseSchema>;

export const DeviceProfileUpdateRequestSchema = z
  .object({
    protocol_version: z.literal(PROTOCOL_VERSION),
    display_name: DisplayNameSchema,
    platform: PlatformSchema,
  })
  .strict();
export type DeviceProfileUpdateRequest = z.infer<typeof DeviceProfileUpdateRequestSchema>;

export const DeviceProfileUpdateResponseSchema = z
  .object({
    protocol_version: z.literal(PROTOCOL_VERSION),
    status: z.literal("updated"),
    device_id: OpaqueIdSchema,
  })
  .strict();
export type DeviceProfileUpdateResponse = z.infer<typeof DeviceProfileUpdateResponseSchema>;

export const LogoutResponseSchema = z
  .object({
    protocol_version: z.literal(PROTOCOL_VERSION),
    status: z.literal("signed_out"),
  })
  .strict();
export type LogoutResponse = z.infer<typeof LogoutResponseSchema>;

export const DeleteDeviceResponseSchema = z
  .object({
    protocol_version: z.literal(PROTOCOL_VERSION),
    status: z.literal("deleted"),
    device_id: OpaqueIdSchema,
    device_generation: SafePositiveIntegerSchema,
    deleted_before: Rfc3339InstantSchema,
  })
  .strict();
export type DeleteDeviceResponse = z.infer<typeof DeleteDeviceResponseSchema>;

export const BILLING_AGENTS = ["codex", "claude_code", "grok", "opencode", "pi", "cursor"] as const;
export const BillingAgentSchema = z.enum(BILLING_AGENTS);
export type BillingAgent = z.infer<typeof BillingAgentSchema>;

const AGENT_DISPLAY_NAMES: Readonly<Record<BillingAgent, string>> = {
  codex: "Codex",
  claude_code: "Claude Code",
  grok: "Grok",
  opencode: "OpenCode",
  pi: "Pi",
  cursor: "Cursor",
};

/** An agent this build has never heard of is named as what it is. */
export function agentDisplayName(agent: string): string {
  return AGENT_DISPLAY_NAMES[agent as BillingAgent] ?? "Unknown";
}

export const InferenceProviderSchema = z.enum([
  "openai",
  "azure_openai",
  "anthropic",
  "aws_bedrock",
  "google_vertex",
  "openrouter",
  "xai",
  "moonshot",
  "deepseek",
  "unknown",
]);
export type InferenceProvider = z.infer<typeof InferenceProviderSchema>;

const INFERENCE_PROVIDER_DISPLAY_NAMES: Readonly<Record<InferenceProvider, string>> = {
  openai: "OpenAI",
  azure_openai: "Azure OpenAI",
  anthropic: "Anthropic",
  aws_bedrock: "AWS Bedrock",
  google_vertex: "Google Vertex AI",
  openrouter: "OpenRouter",
  xai: "xAI",
  moonshot: "Moonshot AI",
  deepseek: "DeepSeek",
  unknown: "Unknown Provider",
};

/** The words the Apple clients already say for the company that ran the inference. */
export function inferenceProviderDisplayName(provider: string): string {
  return INFERENCE_PROVIDER_DISPLAY_NAMES[provider as InferenceProvider] ?? "Unknown Provider";
}

export const MAXIMUM_MODEL_CATALOG_MODELS = 512;
export const MAXIMUM_MODEL_CATALOG_ALIASES_PER_MODEL = 32;
export const MAXIMUM_MODEL_CATALOG_ALIASES = 4_096;

export const BillingChannelSchema = z.enum([
  "openai_direct",
  "azure_openai",
  "anthropic_direct",
  "aws_bedrock",
  "google_vertex",
  "openrouter",
  "xai_direct",
  "moonshot_direct",
  "deepseek_direct",
  "unknown",
]);

export type BillingChannel = z.infer<typeof BillingChannelSchema>;

const ModelCatalogCanonicalIDSchema = z.string().min(1).max(128).regex(OPAQUE_ID_PATTERN);

export const ModelCatalogAliasSchema = z
  .object({
    reported_model: ModelSchema,
    provider: InferenceProviderSchema,
    agent: BillingAgentSchema.optional(),
    effective_from: UsageDateSchema.optional(),
    effective_to: UsageDateSchema.optional(),
  })
  .strict()
  .superRefine((alias, context) => {
    if (alias.effective_from && alias.effective_to && alias.effective_to <= alias.effective_from) {
      context.addIssue({
        code: "custom",
        path: ["effective_to"],
        message: "effective_to must be later than effective_from.",
      });
    }
  });
export type ModelCatalogAlias = z.infer<typeof ModelCatalogAliasSchema>;

export const ModelCatalogModelSchema = z
  .object({
    canonical_id: ModelCatalogCanonicalIDSchema,
    aliases: z.array(ModelCatalogAliasSchema).min(1).max(MAXIMUM_MODEL_CATALOG_ALIASES_PER_MODEL),
  })
  .strict();
export type ModelCatalogModel = z.infer<typeof ModelCatalogModelSchema>;

export const ModelCatalogSchema = z
  .object({
    schema_version: z.literal(2),
    revision: OpaqueIdSchema,
    models: z.array(ModelCatalogModelSchema).min(1).max(MAXIMUM_MODEL_CATALOG_MODELS),
  })
  .strict();
export type ModelCatalog = z.infer<typeof ModelCatalogSchema>;

/** The checked-in, language-neutral model catalog source used by the Relay default. */
export const MODEL_CATALOG: ModelCatalog = ModelCatalogSchema.parse(modelCatalogDocument);

/** Every channel except the sentinel: an unknown channel has no price to resolve. */
export const PricedBillingChannelSchema = z.enum(
  BillingChannelSchema.options.filter((channel) => channel !== "unknown") as [
    Exclude<BillingChannel, "unknown">,
    ...Exclude<BillingChannel, "unknown">[],
  ],
);
export type PricedBillingChannel = z.infer<typeof PricedBillingChannelSchema>;

export const ChannelSourceSchema = z.enum(["explicit", "agent_default", "unknown"]);
export type ChannelSource = z.infer<typeof ChannelSourceSchema>;

export const ContextBucketSchema = z.enum([
  "le_128k",
  "gt_128k_le_200k",
  "gt_200k_le_256k",
  "gt_256k_le_272k",
  "gt_272k",
]);
export type ContextBucket = z.infer<typeof ContextBucketSchema>;

export const CoverageStatusSchema = z.enum(["complete", "partial"]);
export type CoverageStatus = z.infer<typeof CoverageStatusSchema>;

/**
 * One agent's contiguous UTC-hour window and how completely it was scanned.
 *
 * Only the private local report still states coverage. A managed upload replaces whole hours
 * and says of each one whether the scan behind it was complete, so a window has nothing left
 * to say there.
 */
const LocalUsageCoverageSchema = z
  .object({
    agent: BillingAgentSchema,
    start_at: UtcHourSchema,
    end_at: UtcHourSchema,
    status: CoverageStatusSchema,
  })
  .strict()
  .superRefine(validateCoverageOrder);

/**
 * One row of Usage, identified by what it measures rather than by when.
 *
 * The hour is carried by the upload that replaces it, so a row names no instant, no local
 * date, and no aggregation timezone: those made the same measurement look like two rows
 * whenever a device moved.
 */
const usageRowFields = {
  agent: BillingAgentSchema,
  billing_channel: BillingChannelSchema,
  channel_source: ChannelSourceSchema,
  model: ModelSchema,
  context_bucket: ContextBucketSchema,
  service_tier: BillingDimensionSchema,
  speed: BillingDimensionSchema,
  inference_geo: BillingDimensionSchema,
  input_tokens: SafeNonnegativeIntegerSchema,
  cache_read_tokens: SafeNonnegativeIntegerSchema,
  cache_write_5m_tokens: SafeNonnegativeIntegerSchema,
  cache_write_1h_tokens: SafeNonnegativeIntegerSchema,
  cache_write_inferred_tokens: SafeNonnegativeIntegerSchema,
  output_tokens: SafeNonnegativeIntegerSchema,
  reasoning_tokens: SafeNonnegativeIntegerSchema,
  requests: SafePositiveIntegerSchema,
  web_search_requests: SafeNonnegativeIntegerSchema,
  web_fetch_requests: SafeNonnegativeIntegerSchema,
  source_cost_microusd: z.string().max(32).regex(NONNEGATIVE_INTEGER_PATTERN).optional(),
  source_cost_covered_requests: SafeNonnegativeIntegerSchema,
} as const;

function validateUsageRow(
  row: { billing_channel: string; channel_source: string } & Parameters<
    typeof validateUsageCounts
  >[0],
  context: z.RefinementCtx,
): void {
  validateUsageCounts(row, context);
  if ((row.billing_channel === "unknown") !== (row.channel_source === "unknown")) {
    context.addIssue({
      code: "custom",
      path: ["channel_source"],
      message: "Unknown billing channel and channel source must be used together.",
    });
  }
}

// `model` is provider-owned opaque text. The literal "unknown" is a valid explicit model.
export const UsageRowSchema = z.object(usageRowFields).strict().superRefine(validateUsageRow);
export type UsageRow = z.infer<typeof UsageRowSchema>;

/**
 * A stored row projected for costing: the same measurement plus the UTC date it was rolled
 * into. Pricing entries and model aliases carry effective dates, so a price cannot be
 * resolved without one, and the daily rollup is where a stored row keeps its date.
 */
export const DatedUsageRowSchema = z
  .object({ ...usageRowFields, date: UsageDateSchema })
  .strict()
  .superRefine(validateUsageRow);
export type DatedUsageRow = z.infer<typeof DatedUsageRowSchema>;

/**
 * One scanned UTC hour and every row the scan found in it.
 *
 * `scan_version` orders the scans of one hour, so an upload replaces an hour only when it
 * carries a strictly newer reading of it; a re-sent or overtaken hour is ignored rather than
 * merged, which is what makes a retry safe without a submission id, a sequence, or a receipt.
 * `partial` says the scan behind this hour came up short, which the reads report and which
 * costs nothing to carry.
 */
export const UsageHourSchema = z
  .object({
    bucket_start_utc: UtcHourSchema,
    scan_version: SafeNonnegativeIntegerSchema,
    partial: z.boolean(),
    rows: z.array(UsageRowSchema).max(MAXIMUM_USAGE_ROWS_PER_HOUR),
  })
  .strict()
  .superRefine((hour, context) => {
    if (Date.parse(hour.bucket_start_utc) < Date.parse(EARLIEST_USAGE_INSTANT)) {
      context.addIssue({
        code: "custom",
        path: ["bucket_start_utc"],
        message: `An hour may not begin before ${EARLIEST_USAGE_INSTANT}.`,
      });
    }
    const identities = new Set<string>();
    for (const [index, row] of hour.rows.entries()) {
      const identity = usageRowIdentity(row);
      if (identities.has(identity)) {
        context.addIssue({
          code: "custom",
          path: ["rows", index],
          message: "Row identities must be unique within an hour.",
        });
      }
      identities.add(identity);
    }
  });
export type UsageHour = z.infer<typeof UsageHourSchema>;

/** One agent's rescanned hours. The device token names the device and its generation. */
export const UsageUploadSchema = z
  .object({
    protocol_version: z.literal(MANAGED_DATA_PROTOCOL_VERSION),
    generation: SafePositiveIntegerSchema,
    agent: BillingAgentSchema,
    hours: z.array(UsageHourSchema).max(MAXIMUM_USAGE_HOURS_PER_UPLOAD),
  })
  .strict()
  .superRefine((upload, context) => {
    const buckets = new Set<string>();
    for (const [index, hour] of upload.hours.entries()) {
      if (buckets.has(hour.bucket_start_utc)) {
        context.addIssue({
          code: "custom",
          path: ["hours", index, "bucket_start_utc"],
          message: "An upload may name each hour once.",
        });
      }
      buckets.add(hour.bucket_start_utc);
      for (const [rowIndex, row] of hour.rows.entries()) {
        if (row.agent !== upload.agent) {
          context.addIssue({
            code: "custom",
            path: ["hours", index, "rows", rowIndex, "agent"],
            message: "Row agent must match the upload agent.",
          });
        }
      }
    }
  });
export type UsageUpload = z.infer<typeof UsageUploadSchema>;

export const UsageCostModeSchema = z.enum(["calculate", "auto", "reported"]);
export type UsageCostMode = z.infer<typeof UsageCostModeSchema>;

export const UsageCostBasisSchema = z.enum(["calculated", "reported", "mixed", "none"]);
export type UsageCostBasis = z.infer<typeof UsageCostBasisSchema>;

export const UsageCostStatusSchema = z.enum(["complete", "partial", "unavailable"]);
export type UsageCostStatus = z.infer<typeof UsageCostStatusSchema>;

export const UsageCostAssumptionSchema = z.enum([
  "agent_default_channel",
  "model_alias",
  "wildcard_service_tier",
  "wildcard_speed",
  "wildcard_inference_geo",
  "wildcard_context_bucket",
  "cache_write_inferred_rate",
  "source_reported",
]);
export type UsageCostAssumption = z.infer<typeof UsageCostAssumptionSchema>;

export const UsageUnpricedReasonSchema = z.enum([
  "unknown_channel",
  "unknown_model",
  "outside_effective_range",
  "unsupported_dimensions",
  "ambiguous_price",
  "missing_rate",
  "incomplete_source_cost",
  "invalid_catalog",
]);
export type UsageUnpricedReason = z.infer<typeof UsageUnpricedReasonSchema>;

export const UsageUnpricedItemSchema = z
  .object({
    billing_channel: BillingChannelSchema,
    model: ModelSchema,
    reason: UsageUnpricedReasonSchema,
    rows: SafePositiveIntegerSchema,
  })
  .strict();
export type UsageUnpricedItem = z.infer<typeof UsageUnpricedItemSchema>;

export const UsageCostOutcomeSchema = z
  .object({
    mode: UsageCostModeSchema,
    basis: UsageCostBasisSchema,
    status: UsageCostStatusSchema,
    amount_microusd: z.string().max(32).regex(NONNEGATIVE_INTEGER_PATTERN).nullable(),
    catalog_revision: OpaqueIdSchema.nullable(),
    calculated_rows: SafeNonnegativeIntegerSchema,
    reported_rows: SafeNonnegativeIntegerSchema,
    unpriced_rows: SafeNonnegativeIntegerSchema,
    assumptions: z.array(UsageCostAssumptionSchema).max(16),
    unpriced: z.array(UsageUnpricedItemSchema).max(MAXIMUM_UNPRICED_ITEMS),
    unpriced_truncated: z.literal(true).optional(),
  })
  .strict()
  .superRefine(validateCostOutcome);
export type UsageCostOutcome = z.infer<typeof UsageCostOutcomeSchema>;

export const UsageSummaryTotalsSchema = z
  .object({
    total_tokens: SafeNonnegativeIntegerSchema,
    input_tokens: SafeNonnegativeIntegerSchema,
    output_tokens: SafeNonnegativeIntegerSchema,
    cache_read_input_tokens: SafeNonnegativeIntegerSchema,
    cache_write_input_tokens: SafeNonnegativeIntegerSchema,
    reasoning_tokens: SafeNonnegativeIntegerSchema,
    messages: SafeNonnegativeIntegerSchema,
  })
  .strict()
  .superRefine((totals, context) => {
    const totalTokens = totals.input_tokens + totals.output_tokens;
    if (!Number.isSafeInteger(totalTokens) || totals.total_tokens !== totalTokens) {
      context.addIssue({
        code: "custom",
        path: ["total_tokens"],
        message: "total_tokens must equal input_tokens plus output_tokens.",
      });
    }
    const cachedInput = totals.cache_read_input_tokens + totals.cache_write_input_tokens;
    if (!Number.isSafeInteger(cachedInput) || cachedInput > totals.input_tokens) {
      context.addIssue({
        code: "custom",
        path: ["input_tokens"],
        message: "Cache token subsets must not exceed input_tokens.",
      });
    }
    if (totals.reasoning_tokens > totals.output_tokens) {
      context.addIssue({
        code: "custom",
        path: ["reasoning_tokens"],
        message: "reasoning_tokens must not exceed output_tokens.",
      });
    }
  });
export type UsageSummaryTotals = z.infer<typeof UsageSummaryTotalsSchema>;

export const LocalUsageModelSummarySchema = z
  .object({
    model: ModelSchema,
    totals: UsageSummaryTotalsSchema,
    cost: UsageCostOutcomeSchema,
  })
  .strict();
export type LocalUsageModelSummary = z.infer<typeof LocalUsageModelSummarySchema>;

export const LocalUsageProviderSummarySchema = z
  .object({
    provider: InferenceProviderSchema,
    totals: UsageSummaryTotalsSchema,
    cost: UsageCostOutcomeSchema,
    models: z.array(LocalUsageModelSummarySchema).max(MAXIMUM_USAGE_BREAKDOWNS),
  })
  .strict();
export type LocalUsageProviderSummary = z.infer<typeof LocalUsageProviderSummarySchema>;

export const LocalUsageAgentSummarySchema = z
  .object({
    agent: BillingAgentSchema,
    totals: UsageSummaryTotalsSchema,
    cost: UsageCostOutcomeSchema,
    providers: z.array(LocalUsageProviderSummarySchema).max(InferenceProviderSchema.options.length),
  })
  .strict();
export type LocalUsageAgentSummary = z.infer<typeof LocalUsageAgentSummarySchema>;

export const LocalUsagePeriodSummarySchema = z
  .object({
    totals: UsageSummaryTotalsSchema,
    cost: UsageCostOutcomeSchema,
    agents: z.array(LocalUsageAgentSummarySchema).max(BillingAgentSchema.options.length),
    models_truncated: z.literal(true).optional(),
  })
  .strict();
export type LocalUsagePeriodSummary = z.infer<typeof LocalUsagePeriodSummarySchema>;

/** A range of calendar dates. `to` names the last day it covers, inclusive. */
export const UsageDateRangeSchema = z
  .object({
    from: UsageDateSchema,
    to: UsageDateSchema,
  })
  .strict()
  .superRefine((range, context) => {
    if (Date.parse(`${range.from}T00:00:00Z`) > Date.parse(`${range.to}T00:00:00Z`)) {
      context.addIssue({ code: "custom", path: ["to"], message: "to must not precede from." });
    }
  });
export type UsageDateRange = z.infer<typeof UsageDateRangeSchema>;

/**
 * The dates an activity read may ask for.
 *
 * The private local report states whatever range the app asked for, so the bound belongs to the
 * read that has to answer it rather than to every range.
 */
export const UsageActivityRangeSchema = UsageDateRangeSchema.superRefine((range, context) => {
  const days =
    (Date.parse(`${range.to}T00:00:00Z`) - Date.parse(`${range.from}T00:00:00Z`)) / 86_400_000 + 1;
  if (days > MAXIMUM_USAGE_ACTIVITY_DAYS) {
    context.addIssue({
      code: "custom",
      path: ["to"],
      message: `A range may span at most ${MAXIMUM_USAGE_ACTIVITY_DAYS} days.`,
    });
  }
});

export const LocalUsageReportStatusSchema = z.enum(["complete", "partial", "unavailable"]);
export type LocalUsageReportStatus = z.infer<typeof LocalUsageReportStatusSchema>;

export const LocalUsageReportSchema = z
  .object({
    generated_at: Rfc3339InstantSchema,
    aggregation_timezone: IanaTimezoneSchema.nullable(),
    range: UsageDateRangeSchema,
    status: LocalUsageReportStatusSchema,
    model_catalog_revision: OpaqueIdSchema.nullable(),
    coverage: z.array(LocalUsageCoverageSchema).max(MAXIMUM_USAGE_COVERAGE_ITEMS),
  })
  .strict()
  .superRefine((report, context) => {
    const unavailable = report.status === "unavailable";
    const validMetadata = unavailable
      ? report.aggregation_timezone === null && report.model_catalog_revision === null
      : report.aggregation_timezone !== null;
    if (!validMetadata) {
      context.addIssue({
        code: "custom",
        path: ["status"],
        message: "Unavailable local Usage must omit timezone and model metadata.",
      });
    }
    if (unavailable && report.coverage.length > 0) {
      context.addIssue({
        code: "custom",
        path: ["coverage"],
        message: "Unavailable local Usage cannot contain coverage.",
      });
    }
    if (!unavailable) {
      const expected = report.coverage.every((item) => item.status === "complete")
        ? "complete"
        : "partial";
      if (report.status !== expected) {
        context.addIssue({
          code: "custom",
          path: ["status"],
          message: "Local Usage status must reflect its coverage.",
        });
      }
    }
  });
export type LocalUsageReport = z.infer<typeof LocalUsageReportSchema>;

/** One model's share of a period. Totals and cost live at the leaf and at the period. */
export const UsageModelUsageSchema = z
  .object({
    model: ModelSchema,
    totals: UsageSummaryTotalsSchema,
    cost: UsageCostOutcomeSchema,
  })
  .strict();
export type UsageModelUsage = z.infer<typeof UsageModelUsageSchema>;

export const UsageProviderUsageSchema = z
  .object({
    provider: InferenceProviderSchema,
    models: z.array(UsageModelUsageSchema).max(MAXIMUM_USAGE_PERIOD_LEAVES),
  })
  .strict();
export type UsageProviderUsage = z.infer<typeof UsageProviderUsageSchema>;

export const UsageAgentUsageSchema = z
  .object({
    agent: BillingAgentSchema,
    providers: z.array(UsageProviderUsageSchema).max(InferenceProviderSchema.options.length),
  })
  .strict();
export type UsageAgentUsage = z.infer<typeof UsageAgentUsageSchema>;

/**
 * One period of Usage: its totals, its cost, whether any hour behind it was scanned
 * incompletely, and the agent tree that makes up the difference.
 */
export const UsagePeriodSchema = z
  .object({
    totals: UsageSummaryTotalsSchema,
    cost: UsageCostOutcomeSchema,
    partial: z.boolean(),
    agents: z.array(UsageAgentUsageSchema).max(BillingAgentSchema.options.length),
  })
  .strict();
export type UsagePeriod = z.infer<typeof UsagePeriodSchema>;

/**
 * The four periods an Account read answers.
 *
 * A day is a UTC day, because that is the grain the daily rollup keeps. The `tz` a caller
 * names decides which calendar days `today` and the trailing windows cover, not where a day
 * begins.
 */
export const AccountUsageSchema = z
  .object({
    today: UsagePeriodSchema,
    last_7_days: UsagePeriodSchema,
    last_30_days: UsagePeriodSchema,
    all: UsagePeriodSchema,
  })
  .strict();
export type AccountUsage = z.infer<typeof AccountUsageSchema>;

/** One device that reported a subscription, kept whether or not its reading is the one shown. */
export const QuotaSubscriptionSourceSchema = z
  .object({
    device_id: OpaqueIdSchema,
    observed_at: Rfc3339InstantSchema,
  })
  .strict();
export type QuotaSubscriptionSource = z.infer<typeof QuotaSubscriptionSourceSchema>;

/**
 * One subscription, already resolved.
 *
 * Relay keeps one observation per reporting device and resolves them once, so an account
 * collected on three Macs reaches every reader as one row with three sources rather than as
 * three cards each client had to collapse for itself. See
 * [ADR 0003](../../../docs/decisions/0003-observation-preserving-subscription-merge.md).
 */
export const QuotaSubscriptionSchema = z
  .object({
    key: z.string().min(1).max(512),
    provider: ProviderIdSchema,
    snapshot: QuotaSnapshotSchema,
    sources: z.array(QuotaSubscriptionSourceSchema).max(256),
  })
  .strict();
export type QuotaSubscription = z.infer<typeof QuotaSubscriptionSchema>;

export const AccountSummarySchema = z
  .object({
    protocol_version: z.literal(MANAGED_DATA_PROTOCOL_VERSION),
    account: AccountSchema,
    devices: z.array(AccountDeviceSchema).max(256),
    subscriptions: z.array(QuotaSubscriptionSchema).max(1_024),
    usage: AccountUsageSchema,
    pricing_revision: OpaqueIdSchema,
    model_catalog_revision: OpaqueIdSchema,
  })
  .strict();
export type AccountSummary = z.infer<typeof AccountSummarySchema>;

/** One UTC day of the activity chart. */
export const UsageActivityDaySchema = z
  .object({
    date: UsageDateSchema,
    totals: UsageSummaryTotalsSchema,
    cost: UsageCostOutcomeSchema,
    partial: z.boolean(),
  })
  .strict();
export type UsageActivityDay = z.infer<typeof UsageActivityDaySchema>;

export const AccountUsageActivityResponseSchema = z
  .object({
    protocol_version: z.literal(MANAGED_DATA_PROTOCOL_VERSION),
    days: z.array(UsageActivityDaySchema).max(MAXIMUM_USAGE_ACTIVITY_DAYS),
  })
  .strict();
export type AccountUsageActivityResponse = z.infer<typeof AccountUsageActivityResponseSchema>;

/**
 * What a client takes from a managed read.
 *
 * Every schema above states the contract exactly, which is how Relay — the producer — fails its
 * own tests for a key it never stated. A client reads across a version boundary: the Relay it
 * talks to can be newer than the build doing the reading. So a reader keeps the keys it knows,
 * carries the ones it does not, and never discards a payload over an enum member it has not
 * heard of. A verdict the payload derives from its own numbers — the cost basis and status —
 * stays closed, because a value outside that set contradicts the payload rather than extending
 * it. See [ADR 0023](../../../docs/decisions/0023-strict-writes-tolerant-reads.md).
 */
const ReadEnumSchema = z.string().min(1).max(64).regex(WIRE_ENUM_PATTERN);

const QuotaWindowReadSchema = QuotaWindowSchema.extend({
  value_unit: ReadEnumSchema.optional(),
}).loose();

const QuotaAccountReadSchema = QuotaAccountSchema.extend({
  fingerprint_scope: ReadEnumSchema,
}).loose();

const QuotaSnapshotReadSchema = QuotaSnapshotSchema.extend({
  provider: ReadEnumSchema,
  status: ReadEnumSchema,
  account: QuotaAccountReadSchema,
  windows: z.array(QuotaWindowReadSchema).max(MAXIMUM_WINDOWS_PER_SNAPSHOT),
}).loose();
export type QuotaSnapshotRead = z.infer<typeof QuotaSnapshotReadSchema>;

const AccountDeviceReadSchema = z.looseObject({
  ...AccountDeviceSchema.shape,
  platform: ReadEnumSchema,
});
export type AccountDeviceRead = z.infer<typeof AccountDeviceReadSchema>;

const UsageUnpricedItemReadSchema = UsageUnpricedItemSchema.extend({
  billing_channel: ReadEnumSchema,
  reason: ReadEnumSchema,
}).loose();

const UsageCostOutcomeReadSchema = z
  .looseObject({
    ...UsageCostOutcomeSchema.shape,
    assumptions: z.array(ReadEnumSchema).max(16),
    unpriced: z.array(UsageUnpricedItemReadSchema).max(MAXIMUM_UNPRICED_ITEMS),
  })
  .superRefine(validateCostOutcome);

const UsageSummaryTotalsReadSchema = UsageSummaryTotalsSchema.loose();

const LocalUsageModelSummaryReadSchema = LocalUsageModelSummarySchema.extend({
  totals: UsageSummaryTotalsReadSchema,
  cost: UsageCostOutcomeReadSchema,
}).loose();

const LocalUsageProviderSummaryReadSchema = LocalUsageProviderSummarySchema.extend({
  provider: ReadEnumSchema,
  totals: UsageSummaryTotalsReadSchema,
  cost: UsageCostOutcomeReadSchema,
  models: z.array(LocalUsageModelSummaryReadSchema).max(MAXIMUM_USAGE_BREAKDOWNS),
}).loose();

const LocalUsageAgentSummaryReadSchema = LocalUsageAgentSummarySchema.extend({
  agent: ReadEnumSchema,
  totals: UsageSummaryTotalsReadSchema,
  cost: UsageCostOutcomeReadSchema,
  providers: z.array(LocalUsageProviderSummaryReadSchema).max(MAXIMUM_USAGE_BREAKDOWNS),
}).loose();
export type LocalUsageAgentSummaryRead = z.infer<typeof LocalUsageAgentSummaryReadSchema>;

const UsageModelUsageReadSchema = UsageModelUsageSchema.extend({
  totals: UsageSummaryTotalsReadSchema,
  cost: UsageCostOutcomeReadSchema,
}).loose();
export type UsageModelUsageRead = z.infer<typeof UsageModelUsageReadSchema>;

const UsageProviderUsageReadSchema = UsageProviderUsageSchema.extend({
  provider: ReadEnumSchema,
  models: z.array(UsageModelUsageReadSchema).max(MAXIMUM_USAGE_PERIOD_LEAVES),
}).loose();
export type UsageProviderUsageRead = z.infer<typeof UsageProviderUsageReadSchema>;

const UsageAgentUsageReadSchema = UsageAgentUsageSchema.extend({
  agent: ReadEnumSchema,
  providers: z.array(UsageProviderUsageReadSchema).max(MAXIMUM_USAGE_PERIOD_LEAVES),
}).loose();
export type UsageAgentUsageRead = z.infer<typeof UsageAgentUsageReadSchema>;

const UsagePeriodReadSchema = UsagePeriodSchema.extend({
  totals: UsageSummaryTotalsReadSchema,
  cost: UsageCostOutcomeReadSchema,
  agents: z.array(UsageAgentUsageReadSchema).max(MAXIMUM_USAGE_PERIOD_LEAVES),
}).loose();
export type UsagePeriodRead = z.infer<typeof UsagePeriodReadSchema>;

const AccountUsageReadSchema = AccountUsageSchema.extend({
  today: UsagePeriodReadSchema,
  last_7_days: UsagePeriodReadSchema,
  last_30_days: UsagePeriodReadSchema,
  all: UsagePeriodReadSchema,
}).loose();
export type AccountUsageRead = z.infer<typeof AccountUsageReadSchema>;

const QuotaSubscriptionReadSchema = QuotaSubscriptionSchema.extend({
  provider: ReadEnumSchema,
  snapshot: QuotaSnapshotReadSchema,
  sources: z.array(QuotaSubscriptionSourceSchema.loose()).max(256),
}).loose();
export type QuotaSubscriptionRead = z.infer<typeof QuotaSubscriptionReadSchema>;

export const AccountSummaryReadSchema = AccountSummarySchema.extend({
  account: AccountSchema.loose(),
  devices: z.array(AccountDeviceReadSchema).max(256),
  subscriptions: z.array(QuotaSubscriptionReadSchema).max(1_024),
  usage: AccountUsageReadSchema,
}).loose();
export type AccountSummaryRead = z.infer<typeof AccountSummaryReadSchema>;

const UsageActivityDayReadSchema = UsageActivityDaySchema.extend({
  totals: UsageSummaryTotalsReadSchema,
  cost: UsageCostOutcomeReadSchema,
}).loose();
export type UsageActivityDayRead = z.infer<typeof UsageActivityDayReadSchema>;

export const AccountUsageActivityResponseReadSchema = AccountUsageActivityResponseSchema.extend({
  days: z.array(UsageActivityDayReadSchema).max(MAXIMUM_USAGE_ACTIVITY_DAYS),
}).loose();
export type AccountUsageActivityResponseRead = z.infer<
  typeof AccountUsageActivityResponseReadSchema
>;

/**
 * What Relay answers a snapshot upload with.
 *
 * A provider is `accepted` when at least one of its readings was newer than the one already
 * stored and `ignored` when none was, which is everything a device needs to know: there is no
 * sequence to advance and no receipt to reconcile.
 */
export const QuotaSnapshotUploadResponseSchema = z
  .object({
    protocol_version: z.literal(MANAGED_DATA_PROTOCOL_VERSION),
    device_id: OpaqueIdSchema,
    device_generation: SafePositiveIntegerSchema,
    accepted: z.array(ProviderIdSchema).max(MAXIMUM_SNAPSHOTS_PER_ENVELOPE),
    ignored: z.array(ProviderIdSchema).max(MAXIMUM_SNAPSHOTS_PER_ENVELOPE),
  })
  .strict();
export type QuotaSnapshotUploadResponse = z.infer<typeof QuotaSnapshotUploadResponseSchema>;

/**
 * What Relay answers a Usage upload with.
 *
 * Every named hour comes back in exactly one list. `accepted` means this scan replaced the
 * hour; `ignored` means it did not and never will, because a newer scan already stands or the
 * hour precedes this device's deletion watermark. Either way the device is done with it.
 */
export const UsageUploadResponseSchema = z
  .object({
    protocol_version: z.literal(MANAGED_DATA_PROTOCOL_VERSION),
    device_id: OpaqueIdSchema,
    device_generation: SafePositiveIntegerSchema,
    accepted: z.array(UtcHourSchema).max(MAXIMUM_USAGE_HOURS_PER_UPLOAD),
    ignored: z.array(UtcHourSchema).max(MAXIMUM_USAGE_HOURS_PER_UPLOAD),
  })
  .strict();
export type UsageUploadResponse = z.infer<typeof UsageUploadResponseSchema>;

export const DecimalAmountSchema = z.string().min(1).max(32).regex(DECIMAL_PATTERN);
export type DecimalAmount = z.infer<typeof DecimalAmountSchema>;

export const PricingRatesSchema = z
  .object({
    uncached_input_per_million: DecimalAmountSchema.nullable(),
    cache_read_per_million: DecimalAmountSchema.nullable(),
    cache_write_5m_per_million: DecimalAmountSchema.nullable(),
    cache_write_1h_per_million: DecimalAmountSchema.nullable(),
    cache_write_inferred_per_million: DecimalAmountSchema.nullable(),
    output_per_million: DecimalAmountSchema.nullable(),
    web_search_per_request: DecimalAmountSchema.nullable(),
    web_fetch_per_request: DecimalAmountSchema.nullable(),
  })
  .strict()
  .refine((rates) => Object.values(rates).some((rate) => rate !== null), {
    message: "A pricing entry must define at least one rate.",
  });
export type PricingRates = z.infer<typeof PricingRatesSchema>;

export const PricingDimensionSchema = z.union([BillingDimensionSchema, z.literal("*")]);
export type PricingDimension = z.infer<typeof PricingDimensionSchema>;

export const PricingContextBucketSchema = z.union([ContextBucketSchema, z.literal("*")]);
export type PricingContextBucket = z.infer<typeof PricingContextBucketSchema>;

export const PricingCatalogEntrySchema = z
  .object({
    entry_id: OpaqueIdSchema,
    billing_channel: PricedBillingChannelSchema,
    model: ModelSchema,
    aliases: z.array(ModelSchema).max(16),
    effective_from: UsageDateSchema,
    effective_to: UsageDateSchema.nullable(),
    service_tier: PricingDimensionSchema,
    speed: PricingDimensionSchema,
    inference_geo: PricingDimensionSchema,
    context_bucket: PricingContextBucketSchema,
    currency: z.literal("USD"),
    rates: PricingRatesSchema,
    source_url: z.string().url().max(2_048).refine(isHttpsUrl, "Expected an HTTPS URL."),
    verified_at: Rfc3339InstantSchema,
  })
  .strict()
  .superRefine((entry, context) => {
    if (entry.effective_to !== null && entry.effective_to <= entry.effective_from) {
      context.addIssue({
        code: "custom",
        path: ["effective_to"],
        message: "effective_to must be later than effective_from.",
      });
    }
    const names = [entry.model, ...entry.aliases];
    if (new Set(names).size !== names.length) {
      context.addIssue({
        code: "custom",
        path: ["aliases"],
        message: "Model and aliases must be unique within an entry.",
      });
    }
  });
export type PricingCatalogEntry = z.infer<typeof PricingCatalogEntrySchema>;

/** Structure only; quota-model performs catalog-wide ambiguity validation. */
export const PricingCatalogSchema = z
  .object({
    protocol_version: z.literal(PROTOCOL_VERSION),
    revision: OpaqueIdSchema,
    published_at: Rfc3339InstantSchema,
    entries: z.array(PricingCatalogEntrySchema).max(MAXIMUM_PRICING_ENTRIES),
  })
  .strict();
export type PricingCatalog = z.infer<typeof PricingCatalogSchema>;

export const RelayErrorCodeSchema = z.enum([
  "invalid_request",
  "unauthorized",
  "forbidden",
  "not_found",
  "authorization_pending",
  "slow_down",
  "access_denied",
  "expired_token",
  "invalid_grant",
  "rate_limited",
  "stale_generation",
  "device_deleted",
  "client_upgrade_required",
  "conflict",
  "internal_error",
]);
export type RelayErrorCode = z.infer<typeof RelayErrorCodeSchema>;

export const RelayErrorEnvelopeSchema = z
  .object({
    error: z
      .object({
        code: RelayErrorCodeSchema,
        message: z.string().trim().min(1).max(512),
      })
      .strict(),
  })
  .strict();
export type RelayErrorEnvelope = z.infer<typeof RelayErrorEnvelopeSchema>;

function isCalendarDate(value: string): boolean {
  const instant = new Date(`${value}T00:00:00Z`);
  return !Number.isNaN(instant.getTime()) && instant.toISOString().slice(0, 10) === value;
}

function isCanonicalUtcHour(value: string): boolean {
  const instant = Date.parse(value);
  return (
    Number.isFinite(instant) && new Date(instant).toISOString().replace(".000Z", "Z") === value
  );
}

function isIanaTimezone(value: string): boolean {
  try {
    new Intl.DateTimeFormat("en", { timeZone: value }).format(0);
    return true;
  } catch {
    return false;
  }
}

function isHttpsUrl(value: string): boolean {
  try {
    return new URL(value).protocol === "https:";
  } catch {
    return false;
  }
}

function isLoopbackRedirectUri(value: string): boolean {
  try {
    const url = new URL(value);
    return (
      url.protocol === "http:" &&
      (url.hostname === "127.0.0.1" || url.hostname === "[::1]" || url.hostname === "::1") &&
      url.port !== "" &&
      url.username === "" &&
      url.password === "" &&
      url.search === "" &&
      url.hash === ""
    );
  } catch {
    return false;
  }
}

/** What makes two rows in one hour the same measurement. */
export function usageRowIdentity(row: {
  agent: string;
  billing_channel: string;
  channel_source: string;
  model: string;
  context_bucket: string;
  service_tier: string;
  speed: string;
  inference_geo: string;
}): string {
  return JSON.stringify([
    row.agent,
    row.billing_channel,
    row.channel_source,
    row.model,
    row.context_bucket,
    row.service_tier,
    row.speed,
    row.inference_geo,
  ]);
}

function validateCoverageOrder(
  coverage: { start_at: string; end_at: string },
  context: z.RefinementCtx,
): void {
  if (Date.parse(coverage.end_at) <= Date.parse(coverage.start_at)) {
    context.addIssue({
      code: "custom",
      path: ["end_at"],
      message: "Coverage end_at must be later than start_at.",
    });
  }
}

function validateUsageCounts(
  value: {
    input_tokens: number;
    cache_read_tokens: number;
    cache_write_5m_tokens: number;
    cache_write_1h_tokens: number;
    cache_write_inferred_tokens: number;
    output_tokens: number;
    reasoning_tokens: number;
    requests: number;
    web_search_requests: number;
    web_fetch_requests: number;
    source_cost_microusd?: string | null | undefined;
    source_cost_covered_requests: number;
  },
  context: z.RefinementCtx,
): void {
  const classifiedInput =
    value.cache_read_tokens +
    value.cache_write_5m_tokens +
    value.cache_write_1h_tokens +
    value.cache_write_inferred_tokens;
  if (!Number.isSafeInteger(classifiedInput) || classifiedInput > value.input_tokens) {
    context.addIssue({
      code: "custom",
      path: ["input_tokens"],
      message: "Cache token subsets must not exceed input_tokens.",
    });
  }
  if (value.reasoning_tokens > value.output_tokens) {
    context.addIssue({
      code: "custom",
      path: ["reasoning_tokens"],
      message: "reasoning_tokens must not exceed output_tokens.",
    });
  }
  if (value.source_cost_covered_requests > value.requests) {
    context.addIssue({
      code: "custom",
      path: ["source_cost_covered_requests"],
      message: "Source cost coverage must not exceed requests.",
    });
  }
  if (value.requests === 0 && (value.web_search_requests > 0 || value.web_fetch_requests > 0)) {
    context.addIssue({
      code: "custom",
      path: ["requests"],
      message: "Billable tool requests require at least one request.",
    });
  }
  const hasSourceCost =
    value.source_cost_microusd !== undefined && value.source_cost_microusd !== null;
  if (hasSourceCost !== value.source_cost_covered_requests > 0) {
    context.addIssue({
      code: "custom",
      path: ["source_cost_microusd"],
      message: "Source cost is present exactly when it covers at least one request.",
    });
  }
}

function validateCostOutcome(
  outcome: {
    basis: string;
    status: string;
    amount_microusd: string | null;
    calculated_rows: number;
    reported_rows: number;
    unpriced_rows: number;
    unpriced_truncated?: true | undefined;
    unpriced: readonly { rows: number }[];
    assumptions: readonly string[];
  },
  context: z.RefinementCtx,
) {
  const pricedRows = outcome.calculated_rows + outcome.reported_rows;
  if (!Number.isSafeInteger(pricedRows)) {
    context.addIssue({ code: "custom", path: ["calculated_rows"], message: "Row count overflow." });
  }
  const expectedBasis =
    outcome.calculated_rows > 0 && outcome.reported_rows > 0
      ? "mixed"
      : outcome.calculated_rows > 0
        ? "calculated"
        : outcome.reported_rows > 0
          ? "reported"
          : "none";
  if (outcome.basis !== expectedBasis) {
    context.addIssue({
      code: "custom",
      path: ["basis"],
      message: "Cost basis must match calculated and reported row counts.",
    });
  }
  const expectedStatus =
    outcome.unpriced_rows === 0 ? "complete" : pricedRows > 0 ? "partial" : "unavailable";
  if (outcome.status !== expectedStatus) {
    context.addIssue({
      code: "custom",
      path: ["status"],
      message: "Cost status must match priced and unpriced row counts.",
    });
  }
  if (pricedRows > 0 !== (outcome.amount_microusd !== null)) {
    context.addIssue({
      code: "custom",
      path: ["amount_microusd"],
      message: "Cost amount is present exactly when at least one row is priced.",
    });
  }
  const detailedUnpricedRows = outcome.unpriced.reduce((sum, item) => sum + item.rows, 0);
  if (
    outcome.unpriced_truncated
      ? detailedUnpricedRows > outcome.unpriced_rows
      : detailedUnpricedRows !== outcome.unpriced_rows
  ) {
    context.addIssue({
      code: "custom",
      path: ["unpriced"],
      message: "Unpriced item counts must sum to unpriced_rows.",
    });
  }
  if (new Set(outcome.assumptions).size !== outcome.assumptions.length) {
    context.addIssue({
      code: "custom",
      path: ["assumptions"],
      message: "Cost assumptions must be unique.",
    });
  }
}
