// Generated by scripts/generate-provider-catalog.mjs — do not edit.
// Source: packages/provider/src/catalog.ts

import { z } from "zod";

export const PROVIDER_IDS = ["codex", "claude", "grok", "openrouter", "deepseek", "kimi", "litellm"] as const;
export type ProviderId = (typeof PROVIDER_IDS)[number];
export const ProviderIdSchema = z.enum(PROVIDER_IDS);
