// Generated by scripts/generate-provider-catalog.mjs — do not edit.
// Source: packages/provider/catalog.json

import Foundation
import QuotaWire

/// Catalog Statuspage v2 URLs this build polls. `kind: none` rows are omitted.
public enum ProviderStatusPages {
  public static let endpoints: [(ProviderID, URL)] = [
    (.`codex`, URL(string: "https://status.openai.com/api/v2/status.json")!),
    (.`claude`, URL(string: "https://status.claude.com/api/v2/status.json")!),
    (.`kimi`, URL(string: "https://status.moonshot.cn/api/v2/status.json")!),
    (.`cursor`, URL(string: "https://status.cursor.com/api/v2/status.json")!),
  ]
}
