// Generated by scripts/generate-provider-catalog.mjs — do not edit.
// Source: packages/provider/catalog.json

use serde::{Deserialize, Serialize};

#[derive(Clone, Copy, Debug, Deserialize, Eq, Hash, PartialEq, Serialize)]
pub enum ProviderId {
    #[serde(rename = "codex")]
    Codex,
    #[serde(rename = "claude")]
    Claude,
    #[serde(rename = "grok")]
    Grok,
    #[serde(rename = "openrouter")]
    OpenRouter,
    #[serde(rename = "deepseek")]
    DeepSeek,
    #[serde(rename = "kimi")]
    Kimi,
    #[serde(rename = "litellm")]
    LiteLlm,
    #[serde(rename = "cursor")]
    Cursor,
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct ApiKeyConfig {
    pub supports_base_url: bool,
    pub requires_base_url: bool,
    pub allow_private_http: bool,
    pub mask_label: &'static str,
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct BrowserSessionConfig {
    pub login_url: &'static str,
    pub cookie_hosts: &'static [&'static str],
    pub cookie_names: &'static [&'static str],
    pub browser_priority: &'static [&'static str],
    pub exclusive: bool,
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct ProviderCatalogEntry {
    pub id: ProviderId,
    pub display_name: &'static str,
    pub order: u8,
    pub default_visible: bool,
    pub setup_action: &'static str,
    pub brand_icon_asset: &'static str,
    pub account_sync: bool,
    pub account_sync_protocol: Option<u8>,
    pub environment_keys: &'static [&'static str],
    pub credential_config: Option<ApiKeyConfig>,
    pub browser_session: Option<BrowserSessionConfig>,
    pub default_base_url: Option<&'static str>,
    pub base_url_environment_key: Option<&'static str>,
}

pub const PROVIDER_CATALOG: &[ProviderCatalogEntry] = &[
    ProviderCatalogEntry {
        id: ProviderId::Codex,
        display_name: "Codex",
        order: 0,
        default_visible: true,
        setup_action: "codex login",
        brand_icon_asset: "openai",
        account_sync: true,
        account_sync_protocol: Some(2),
        environment_keys: &["CODEX_HOME"],
        credential_config: None,
        browser_session: Some(BrowserSessionConfig {
            login_url: "https://chatgpt.com/",
            cookie_hosts: &["chatgpt.com", "www.chatgpt.com"],
            cookie_names: &[
                "__Secure-next-auth.session-token",
                "__Secure-next-auth.session-token.0",
                "__Secure-next-auth.session-token.1",
                "__Secure-next-auth.session-token.2",
                "__Host-next-auth.session-token",
                "__Secure-authjs.session-token",
                "authjs.session-token",
                "_account",
            ],
            browser_priority: &[
                "safari", "chrome", "edge", "brave", "arc", "dia", "chromium", "firefox",
            ],
            exclusive: false,
        }),
        default_base_url: None,
        base_url_environment_key: None,
    },
    ProviderCatalogEntry {
        id: ProviderId::Claude,
        display_name: "Claude Code",
        order: 1,
        default_visible: true,
        setup_action: "claude auth login",
        brand_icon_asset: "claude",
        account_sync: true,
        account_sync_protocol: Some(2),
        environment_keys: &["CLAUDE_CONFIG_DIR"],
        credential_config: None,
        browser_session: Some(BrowserSessionConfig {
            login_url: "https://claude.ai/",
            cookie_hosts: &["claude.ai", "www.claude.ai"],
            cookie_names: &["sessionKey", "lastActiveOrg"],
            browser_priority: &[
                "safari", "chrome", "edge", "brave", "arc", "dia", "chromium", "firefox",
            ],
            exclusive: false,
        }),
        default_base_url: None,
        base_url_environment_key: None,
    },
    ProviderCatalogEntry {
        id: ProviderId::Grok,
        display_name: "Grok",
        order: 2,
        default_visible: true,
        setup_action: "grok login",
        brand_icon_asset: "grok",
        account_sync: true,
        account_sync_protocol: Some(2),
        environment_keys: &["GROK_HOME"],
        credential_config: None,
        browser_session: Some(BrowserSessionConfig {
            login_url: "https://grok.com/",
            cookie_hosts: &["grok.com", "www.grok.com"],
            cookie_names: &["sso", "sso-rw"],
            browser_priority: &[
                "safari", "chrome", "edge", "brave", "arc", "dia", "chromium", "firefox",
            ],
            exclusive: false,
        }),
        default_base_url: None,
        base_url_environment_key: None,
    },
    ProviderCatalogEntry {
        id: ProviderId::OpenRouter,
        display_name: "OpenRouter",
        order: 3,
        default_visible: false,
        setup_action: "Configure in QuotaBar",
        brand_icon_asset: "openrouter",
        account_sync: true,
        account_sync_protocol: Some(2),
        environment_keys: &["OPENROUTER_API_KEY"],
        credential_config: Some(ApiKeyConfig {
            supports_base_url: false,
            requires_base_url: false,
            allow_private_http: false,
            mask_label: "OpenRouter",
        }),
        browser_session: None,
        default_base_url: Some("https://openrouter.ai/api/v1"),
        base_url_environment_key: None,
    },
    ProviderCatalogEntry {
        id: ProviderId::DeepSeek,
        display_name: "DeepSeek",
        order: 4,
        default_visible: false,
        setup_action: "Configure in QuotaBar",
        brand_icon_asset: "deepseek",
        account_sync: true,
        account_sync_protocol: Some(2),
        environment_keys: &["DEEPSEEK_API_KEY", "DEEPSEEK_KEY"],
        credential_config: Some(ApiKeyConfig {
            supports_base_url: false,
            requires_base_url: false,
            allow_private_http: false,
            mask_label: "DeepSeek",
        }),
        browser_session: None,
        default_base_url: Some("https://api.deepseek.com"),
        base_url_environment_key: None,
    },
    ProviderCatalogEntry {
        id: ProviderId::Kimi,
        display_name: "Kimi Code",
        order: 5,
        default_visible: false,
        setup_action: "Configure in QuotaBar",
        brand_icon_asset: "kimi",
        account_sync: true,
        account_sync_protocol: Some(2),
        environment_keys: &["KIMI_CODE_API_KEY", "KIMI_API_KEY"],
        credential_config: Some(ApiKeyConfig {
            supports_base_url: false,
            requires_base_url: false,
            allow_private_http: false,
            mask_label: "Kimi",
        }),
        browser_session: Some(BrowserSessionConfig {
            login_url: "https://www.kimi.com/code/console",
            cookie_hosts: &["www.kimi.com", "kimi.com"],
            cookie_names: &["kimi-auth"],
            browser_priority: &[
                "safari", "chrome", "edge", "brave", "arc", "dia", "chromium", "firefox",
            ],
            exclusive: false,
        }),
        default_base_url: Some("https://api.kimi.com"),
        base_url_environment_key: None,
    },
    ProviderCatalogEntry {
        id: ProviderId::LiteLlm,
        display_name: "LiteLLM",
        order: 6,
        default_visible: false,
        setup_action: "Configure in QuotaBar",
        brand_icon_asset: "litellm",
        account_sync: true,
        account_sync_protocol: Some(2),
        environment_keys: &["LITELLM_API_KEY", "LITELLM_BASE_URL"],
        credential_config: Some(ApiKeyConfig {
            supports_base_url: true,
            requires_base_url: true,
            allow_private_http: true,
            mask_label: "LiteLLM",
        }),
        browser_session: None,
        default_base_url: None,
        base_url_environment_key: Some("LITELLM_BASE_URL"),
    },
    ProviderCatalogEntry {
        id: ProviderId::Cursor,
        display_name: "Cursor",
        order: 7,
        default_visible: false,
        setup_action: "Sign in with browser",
        brand_icon_asset: "cursor",
        account_sync: true,
        account_sync_protocol: Some(3),
        environment_keys: &[],
        credential_config: None,
        browser_session: Some(BrowserSessionConfig {
            login_url: "https://authenticator.cursor.sh/",
            cookie_hosts: &[
                "cursor.com",
                "www.cursor.com",
                "cursor.sh",
                "authenticator.cursor.sh",
            ],
            cookie_names: &[
                "WorkosCursorSessionToken",
                "__Secure-next-auth.session-token",
                "next-auth.session-token",
                "wos-session",
                "__Secure-wos-session",
                "authjs.session-token",
                "__Secure-authjs.session-token",
            ],
            browser_priority: &[
                "safari", "chrome", "edge", "brave", "arc", "dia", "chromium", "firefox",
            ],
            exclusive: true,
        }),
        default_base_url: None,
        base_url_environment_key: None,
    },
];

impl ProviderId {
    /// Every local collector. Use metadata.account_sync_protocol as the managed protocol boundary.
    pub const ALL: &'static [Self] = &[
        Self::Codex,
        Self::Claude,
        Self::Grok,
        Self::OpenRouter,
        Self::DeepSeek,
        Self::Kimi,
        Self::LiteLlm,
        Self::Cursor,
    ];

    pub const fn as_str(self) -> &'static str {
        match self {
            Self::Codex => "codex",
            Self::Claude => "claude",
            Self::Grok => "grok",
            Self::OpenRouter => "openrouter",
            Self::DeepSeek => "deepseek",
            Self::Kimi => "kimi",
            Self::LiteLlm => "litellm",
            Self::Cursor => "cursor",
        }
    }

    pub fn parse(value: &str) -> Option<Self> {
        match value {
            "codex" => Some(Self::Codex),
            "claude" => Some(Self::Claude),
            "grok" => Some(Self::Grok),
            "openrouter" => Some(Self::OpenRouter),
            "deepseek" => Some(Self::DeepSeek),
            "kimi" => Some(Self::Kimi),
            "litellm" => Some(Self::LiteLlm),
            "cursor" => Some(Self::Cursor),
            _ => None,
        }
    }

    pub const fn metadata(self) -> &'static ProviderCatalogEntry {
        match self {
            Self::Codex => &PROVIDER_CATALOG[0],
            Self::Claude => &PROVIDER_CATALOG[1],
            Self::Grok => &PROVIDER_CATALOG[2],
            Self::OpenRouter => &PROVIDER_CATALOG[3],
            Self::DeepSeek => &PROVIDER_CATALOG[4],
            Self::Kimi => &PROVIDER_CATALOG[5],
            Self::LiteLlm => &PROVIDER_CATALOG[6],
            Self::Cursor => &PROVIDER_CATALOG[7],
        }
    }
}

#[cfg(test)]
mod tests {
    use super::ProviderId;

    #[test]
    fn provider_ids_preserve_catalog_wire_values() {
        for provider in ProviderId::ALL {
            let encoded = serde_json::to_string(provider).expect("serialize provider id");
            assert_eq!(encoded, format!("\"{}\"", provider.as_str()));
            assert_eq!(
                serde_json::from_str::<ProviderId>(&encoded).expect("deserialize provider id"),
                *provider
            );
        }
    }
}
