// Generated by scripts/generate-plan-display.mjs — do not edit.
// Source: packages/protocol/catalog/plan-display.json

export const KNOWN_PLANS: Readonly<Record<string, string>> = {
  free: "Free",
  plus: "Plus",
  pro: "Pro",
  prolite: "Pro Lite",
  max: "Max",
  max5x: "Max 5x",
  max20x: "Max 20x",
  team: "Team",
  business: "Business",
  enterprise: "Enterprise",
  edu: "Edu",
  education: "Education",
  supergrok: "SuperGrok",
  supergrokheavy: "SuperGrok Heavy",
  super: "Super",
};
